### ISSUE TITLE
xRAT client deployer

### ISSUE THREAD

**Issue by OpenSourceCS** [quasar/QuasarRAT#102]
We can make an app only having app logic to download the main xRAT Client.exe ( say from an ftp server) so that the deployer application will not be flagged as virus. Moreover, this can be used as an updater and also a persistence which checks if the client.exe runs and if that client.exe is not running, it will start it again.

**Comment by MaxXor** [comment]
Sure, can be useful. But not important at the moment. If someone wants to do this, feel free to do it and send a pull request.
