### ISSUE TITLE
Remote Webcam Capture

### ISSUE THREAD

**Issue by yankejustin** [quasar/QuasarRAT#271]
We probably need a library to capture the webcam and stream it to the server.

Library for webcam:
- AForge.Video.DirectShow
- AForge.Video

https://code.google.com/p/aforge/

**Comment by DragonzMaster** [comment]
i think there are .net open source libraries able use to do this .. so we don't need c++

**Comment by yankejustin** [comment]
@DragonzMaster Please back that statement up with a link because I have been searching for some time now. x)

**Comment by DragonzMaster** [comment]
you can stream webcam using "AForge.Video.DirectShow" 
-  "AForge.Video" libraries 
you can also stream microphone using "Naudio" library
I hope you find these links useful

-----------------
https://code.google.com/p/aforge/
https://github.com/naudio/NAudio

**Comment by MK73DS** [comment]
Yes please add these features :) It would be really helpful :)
I didn't have enought skills to add them myself, so if someone can do that it would be very great :D

**Comment by DragonzMaster** [comment]
What about this issue ?? Is there any chance to be solved soon ? @yankejustin  @MaxXor

**Comment by MaxXor** [comment]
No, probably not.

**Comment by yankejustin** [comment]
I don't have a webcam either. :(

**Comment by MK73DS** [comment]
You can emulate a WebCam to test it, no?

**Comment by MaxXor** [comment]
@MK73DS Yes that's possible.

Well, this issue has IMO low priority, maybe we can add this in some months.

**Comment by MK73DS** [comment]
OK thank you :D 
Yes add it when you want no problem ;)

**Comment by KarlBaumann** [comment]
I vote for this feature :+1:  
And I could also send you a webcam as a gift :)

**Comment by SandPox** [comment]
well... i'm working on it, calling native method instead of external lib

**Comment by MaxXor** [comment]
@SandPox When you send a pull request please take care of removing some of your whitespaces...
Like @d3agle removed here: https://github.com/quasar/QuasarRAT/commit/0988187c25720a7f5435980076587f08bc92955d

You should read [this](https://github.com/quasar/QuasarRAT/blob/master/CONTRIBUTING.md) to make it easier for me to integrate your code into Quasar.

**Comment by yankejustin** [comment]
Some time in the future I will get a webcam. When I do, I will probably just pick up where SandPox left off on. :hankey:

**Comment by SandPox** [comment]
@yankejustin no, do it by another API, my API is deprecated and can't pickup what webcam we want to capture from

**Comment by d3agle** [comment]
This looks clean and simple to use: http://www.codeproject.com/Articles/125478/Versatile-WebCam-C-library

**Comment by SandPox** [comment]
@d3agle no, they using external c++ lib

**Comment by d3agle** [comment]
What about AForge.NET? The three libraries needed would come to ~100KB and they are all managed DLLs.

Link: https://code.google.com/p/aforge/downloads/detail?name=AForge.NET%20Framework-2.2.5-%28libs%20only%29.zip&can=2&q=

**Comment by SandPox** [comment]
using external dll are easy... but we try to keep everything at minimal so... it got to be native API
... or we could upload to client the webcam capture module when we need it

**Comment by d3agle** [comment]
We are using a project for the keylogger that has mouse capturing capability that isn't implemented :P  Also, we make tons of calls to native libs xD.  I don't see why we wouldn't use AForge.NET.. It has the capability to do exactly what we are trying to accomplish.

We could send it over the network like you say, and load the module instead of packing it into the client assembly.  Wouldn't it be easier just to pack it in the assembly?  I don't think the size of the assembly should be too much of a problem..

**Comment by webiummedia** [comment]
Would it be possible to avoid the "Webcam already in use" warning if the client wish to use skype or something while the server is streaming?

**Comment by SandPox** [comment]
@webiummedia no, windows only allow 1 application recording only

**Comment by webiummedia** [comment]
In that case, would be great to set up an offline motion detection video recorder (when internet is off) of and amount of Xgb setted in the builder. It would create an mp4 that could then be downloaded later on a little like the keybord log. That way while viewing the video where not actually using the webcam.

**Comment by SandPox** [comment]
@webiummedia then it will recording webcam all the time to detect motion

**Comment by webiummedia** [comment]
Yes but nobody uses the webcam when theirs no internet connection. With a motion detection you don't record hours of emptiness.

**Comment by yankejustin** [comment]
I don't like the idea of motion detection at all. Besides being difficult to implement efficiently, it is more of a feature geared towards malicious use. The non-malicious uses of such a feature likely is not worth the time needed to implement it. :(

**Comment by SandPox** [comment]
well.. motion detection is handy if you use webcam as home security monitor.. or such thing.. but yea.. it's really hard to implement

**Comment by webiummedia** [comment]
There's tons of open source project we can use for that
http://www.codeproject.com/Articles/10248/Motion-Detection-Algorithms

**Comment by Eredanne** [comment]
I would love to see this implemented. Any updates?

**Comment by SandPox** [comment]
no, this API is deprecated so this would not be implemented

**Comment by Eredanne** [comment]
How about some other API?

**Comment by MaxXor** [comment]
This has been added in #464.
