### ISSUE TITLE
[Plugin Support] Architecture discussion

### ISSUE THREAD

**Issue by Abdullah2993** [quasar/QuasarRAT#277]
I'm currently working on plugin support for xRat. So far what I have in mind is something like UploadAndExecute where you send the plugin assembly over to the client. The client then execute the Plugin Method and sends the response back to the server where it is handled using the same plugin assembly. The architecture so far is quite messy so I'm open to any suggestion or architectural  change.

**Comment by yankejustin** [comment]
Hmmm.
Out of curiosity, what will the plugin support offer that UploadAndExecute won't?
The beauty of the above feature is that we have a basic client we build, then we can execute any custom functionality we wish via the existing UploadAndExecute.

**Comment by Abdullah2993** [comment]
@yankejustin well UploadAndExecute is dumb you give it an exe it downloads it to AppData and the executes it and nothing.
With plugin system you can write any kind of functionality with custom display and whatever and all of this will be in memory first you send your plugin to the client which will load it using Assembly.Load and execute the functionality and sends the response back to the server which will handle it using the same plugin handler.
So it will work as any other feature of xRat like ShowMessageBox, GetSystemInformation etc

**Comment by yankejustin** [comment]
Oh. Implementation of a dynamic loading system is actually easier than UploadAndExecute.
Also, saying UploadAndExecute is dumb because it does exactly what it is named is a bit odd.
Anyways, I would finally like to clarify that this is not like UploadAndExecute. It is dynamic loading and is actually rather easy.
<br />
After sending the assembly for the client to load, the client loads it in and waits for another packet. The next packet will contain the name of the method to attempt to invoke, then the client attempts to invoke it.
<hr />
More extensive dynamic loading is a more difficult task than keylogging, because extensibility and control is emphasized so hard. I wish you luck.

**Comment by yankejustin** [comment]
A relevant idea is to add some form of shadow copying functionality.

**Comment by MaxXor** [comment]
A plugin system would be great, it should be really simple. The Server sends the client the plugin and then it adds new functionality to the client, like it can receive new commands etc.

**Comment by d3agle** [comment]
Would it be ideal to load modules dynamically, or would it be viable in this case to store the modules on the client machine to be loaded each time the client has started?

**Comment by yankejustin** [comment]
@d3agle The client should store it <i>if possible</i>. Whenever a Client receives a plugin use request from the server, it makes sure it exists, requesting the whole thing from the server if it does not.
<hr />
<h1>Little Example</h1>
Server has a module named <code>TestModule</code>. The module is selected for the Client object (server-side). The Server sends an inquiry to the Client to check if it already has the module. If the Client does not have the module, send it.
After the Client (receives and) loads the module in successfully, it informs the Server. The Server will then add the relevant information about the plugin into a <code>List</code> or something similar.
The rest is actually more a matter of implementing an elegant system to gently guide reflection into making invocation of the desired method as simple as possible.

**Comment by yankejustin** [comment]
<h3>Note</h3>
We should really make sure to make a separate <code>Form</code> for the user. Perhaps we can use a <code>ListView</code> for the plugins.   :)

**Comment by bitterypaul** [comment]
Just to clarify, do you want xRAT client to be barebones version and add features like remote desktop, keylogger etc as plugins. Or like adding extra features on top of the existing feature set?.

**Comment by MaxXor** [comment]
@bitterypaul If the plugin system is working great, we can make remove most of the features from the client and add them as plugins.

**Comment by bitterypaul** [comment]
So we can implement the plugin system on top of the xRAT client deployer as mentioned in #102

**Comment by bitterypaul** [comment]
Will the plugin system be only for the client but also for the server? I also think about making the forms for keylogger, reverse proxy etc as plugins for the server so that we can have a fully modular RAT. Also this hides the forms for features in the server which are not supported by the client. This also makes updates for specific features easy.

**Comment by MaxXor** [comment]
Plugins add functionality to the client & server, how are we supposed to use the Remote Desktop for example when we have no Form for it? :smile: 

Anyways I think making this RAT fully modular with plugin support is a huge step, we should plan this for a complete new release of this RAT maybe.

**Comment by Abdullah2993** [comment]
@MaxXor the Form for Remote Desktop can be packed within the plugin :)

**Comment by MaxXor** [comment]
@Abdullah2993 Yes of course, lol. That was sarcasm regarding the question from @bitterypaul.

**Comment by yankejustin** [comment]
@MaxXor I definitely agree. This should be for xRAT R6 as it would require a fair amount of untangling, abstracting, and dynamic plugin addition functionality (making it work, and not allowing it to break easily).

**Comment by yankejustin** [comment]
Modularity and large amounts of abstractions are likely to best be implemented after recreating the user interface using WPF. If the usage of MVVM is correct, abstractions are likely to be necessary at a minimal level and modularity should be exist quite easily. After the switch to WPF, it is likely that this should then be toyed with more.

**Comment by rabbitsmith** [comment]
wpf is not supported on linux.

**Comment by MaxXor** [comment]
@rabbitsmith thanks, good to know!

Anyways, we must put off our plugin system plans. It would require so many changes to the Server & Client that we could start from the beginning. Maybe in Quasar 2.0.^^
