### ISSUE TITLE
What FPS do you get in Remote Desktop?

### ISSUE THREAD

**Issue by itapi** [quasar/QuasarRAT#310]
i didnt really know where to post it so i would do it here :).

just wanted to hear from you guys whats the fps ur runing the remote desktop connection? let say on 100 quality. give me an average number. (use lan because i dont calculate the network factor).
my for example is between 18~20.

**Comment by MaxXor** [comment]
You should measure the FPS when streaming a YT video.

**Comment by itapi** [comment]
@MaxXor allright i will. im asking this becuse i want to help this project.i developed a pairely nice algorithm for finding differences(using parralel and threads so it goes exteremly fast.) i'll post it here if its okay of you?

**Comment by MaxXor** [comment]
@itapi You can create a fork and implement it, maybe it's better than the one xRAT has currently.

**Comment by d3agle** [comment]
Streaming a YT video with Remote Desktop full screen I'm getting ~7 frames which is sufficient enough for me :)

**Comment by yankejustin** [comment]
@d3agle How good is your processor?

**Comment by d3agle** [comment]
@yankejustin, I have an i7 2600k @ 4.5GHz

**Comment by yankejustin** [comment]
@d3agle Wow. I'd imagine the FPS would be higher...

**Comment by d3agle** [comment]
@yankejustin, Well the client machine was 1920x1080 so it makes sense :P  Would have to wait for the client to process a large image then send to server/receive from server

The remote desktop is fairly quick as it is. I've done some testing with Teamviewer (TCP) and the Remote Desktop (xRAT) is a little bit slower, but not by much.  I'd say its pretty comparable.

**Comment by d3agle** [comment]
Perhaps we could scale the image instead of stretching it?  Not sure..

**Comment by itapi** [comment]
@d3agle  scaling the image using c# would probably reduce the quality of the image.
Secod thing,why should maximizing the form affect the frame rate? it  make sense when you run both client and server on the same machine so its taking a screenshot of itself,but if you run the client on another computer ,it shouldnt bother at all...

**Comment by MaxXor** [comment]
@itapi The problem is when maximizing the form the drawing/resizing of the image takes a lot of time. Either we stay with this or we use DirectX to draw the image (maybe we can use this wrapper: https://github.com/sharpdx/SharpDX).

**Comment by d3agle** [comment]
@MaxXor, We could go with SharpDX, or we could scale the image (like teamviewer does).  I've been messing around with scaling the image and it seems like the fps when maximizing the form doesn't drop as much.  Sure, the image quality may be a little bit less (lower res on client, higher res on host/server), but it would work well.  I have the code to scale the image to the size of the RapidPictureBox control and maintaining the aspect ratio of the Client machine, but I am having trouble keeping the image centered in the control.  I'm going to work on it for a little bit today, and if I can get it working I could send a PR so you could test.  What do you think?

**Comment by MaxXor** [comment]
We are already resizing the image to the size of the `RapidPictureBox` [here](https://github.com/MaxXor/xRAT/blob/master/Server/Controls/RapidPictureBox.cs#L133).

**Comment by d3agle** [comment]
Right.. but maintaining the aspect ratio (Scale) of the Client resolution instead of making the image stretch to the control.

**Comment by d3agle** [comment]
Here is an example of what I mean by maintaining aspect ratio:
http://i.gyazo.com/3bf3c41b086d9c621c9507975e2c4209.mp4

What I am having trouble figuring out how to do is keeping the image centered in the PictureBox control

**Comment by d3agle** [comment]
Going to look into implementing SharpDX today.  Saw that Gyo released Babylon RAT for free and noticed he had implemented SharpDX a few weeks ago.  The frame rates are very nice on LAN.  On my network up to 150 frames per second.  We would need to determine whether or not to keep this current client <-> server packet throttling as it is or to revert it to the previous implementation to get a high frame rate.  What do you think?

**Comment by MaxXor** [comment]
Can you send me a link to this RAT? I wanna take a look, I think then we can add sharpdx.

**Comment by d3agle** [comment]
@MaxXor, sent you a pm on hf

**Comment by MaxXor** [comment]
Thanks, maybe I'm going to add it tomorrow. :)

**Comment by d3agle** [comment]
Sounds good :D I looked into it a few days ago and I couldn't figure out what classes we needed for implementation.  I know we need a DirectX device, some rending properties to be set, and possibly bitmap conversion, but I haven't figured out exactly how to go about using these DLLs.  I've asked Gyo if he could provide some tips or snippets, but waiting for his reply.  If you can figure it out though, it will be a great addition :D

**Comment by Vigorian** [comment]
bad deobfuscated source from babylon rat, got trouble with cflow :) but maybe it help
http://rghost.ru/6lpyBWFkq

**Comment by itapi** [comment]
@d3agle  according to this video https://www.youtube.com/watch?v=oc12JSIPVVo their remote desktop seems slow as hell.. but if you say so..

**Comment by itapi** [comment]
@d3agle  by the way im also working hard to optimize this code:
you can see my question just asked today here  haha http://stackoverflow.com/questions/31990488/c-sharp-cut-rectangle-blocks-from-image

**Comment by d3agle** [comment]
@itapi, it's actually pretty fast on my network.  But of course we would have to test it to see what impacts it would have.  And the code you posted on stackoverflow, what you are trying to accomplish would only minimize network traffic.  This could be useful, but still fast changing images couldn't be drawn to the control when they are larger/stretched to fit the control.

**Comment by itapi** [comment]
@d3agle alright I understand.  Can you  send me the sources of Babylon?  I would like to have a look too

**Comment by itapi** [comment]
@d3agle ?

**Comment by d3agle** [comment]
@itapi Look above at Vigorian's comment.  I don't have the source lol

**Comment by itapi** [comment]
@d3agle  it doesnt let me build the project even... lol.
is it working for you?

**Comment by d3agle** [comment]
Right you wouldn't be able to.. He just posted the deob'd source for reference.. You can see what objects were used for SharpDX

**Comment by itapi** [comment]
@MaxXor  are you going to work on that man?

**Comment by yankejustin** [comment]
@MaxXor This can probably be closed.
