### ISSUE TITLE
New icon needed for Quasar

### ISSUE THREAD

**Issue by MaxXor** [quasar/QuasarRAT#337]
After renaming xRAT to Quasar we'll also need a new icon for it.
This issue can be used to discuss & preview new icons.

If there is someone with a graphics talent feel free to submit an icon (64x64 only).

**Comment by d3agle** [comment]
Here is my take on it :)  

http://august4th.us/up/5f72650a7e1f1e0573f4258cab7def25.ico

**Comment by XenocodeRCE** [comment]
![](http://u.cubeupload.com/XenocodeRCE/quazartest01.png)

**Comment by werkamsus** [comment]
Wow, that looks fantastic XenocodeRCE!

**Comment by yankejustin** [comment]
@MaxXor You forgot to update <code>build-debug.bat</code> and <code>build-release.bat</code> with the correct name of the Solution file.

**Comment by MaxXor** [comment]
@d3agle Thanks for your submission!
@XenocodeRCE Wow, this icon looks extremely good!! Can you change the size of it to 64x64?
@yankejustin Thanks, fixed.

**Comment by itapi** [comment]
@MaxXor awesome icon indeed.  May I ask did you change the name?  Are there any new updates coming soon? ;)

**Comment by MaxXor** [comment]
@itapi Yes, I did change the name. Quasar v1.0.0.0 will be released shortly (yes, the versioning is different now :smile:). We're maybe going to change the GUI theme. Discussion about this is here: https://gitter.im/quasar/QuasarRAT

**Comment by XenocodeRCE** [comment]
![](http://u.cubeupload.com/XenocodeRCE/quazartest0164x64.png)

64px - 64px as asked by Maxxor on skype; looks more chubby now but it's still decent

**Comment by werkamsus** [comment]
Well, i'd recommend just resizing it by leaving some borders on the sides in order to contrain its proportions, like so:
![687474703a2f2f752e6375626575706c6f61642e636f6d2f58656e6f636f64655243452f7175617a61727465737430312e706e67](https://cloud.githubusercontent.com/assets/1510843/9385594/91df7af2-4757-11e5-82fa-1f63962bff05.png)

**Comment by d3agle** [comment]
Looks very nice!
![](http://puu.sh/jIcQF/c5cc846ad2.jpg)

**Comment by d3agle** [comment]
![quasar3](https://cloud.githubusercontent.com/assets/7505306/9388848/9feefec6-472d-11e5-811b-1f49ec39d81c.png)
