### ISSUE TITLE
Client with a long up-time doesn't return the correct up-time

### ISSUE THREAD

**Issue by yankejustin** [quasar/QuasarRAT#346]
<h1>Issue Context</h1>
I have a machine that I rarely shut down (normally place into a sleep state). The up-time is around 7-9 weeks.
<h1>Issue Description</h1>
An up-time greater-than ~48-49 days will not correctly be returned to the server; the server will reveal an up-time that is not accurate.
<h1>Cause of the issue</h1>
Because <a href="https://github.com/quasar/QuasarRAT/blob/master/Client/Core/SystemCore.cs#L200"><code>Environment.TickCount</code></a> is an <code>int</code>, it is not capable of functioning after ~48-49 days. It is giving me a negative value for the days due to my up-time.
<h1>Solution</h1>
A functional alternative can be found <a href="http://stackoverflow.com/questions/4645171/environment-tickcount-is-not-enough">here</a>. It is a method that is very similar to the methods we use to obtain other information of the client's machine.

**Comment by yankejustin** [comment]
While on the topic of system information, I just wanted to point out this: perhaps the client should append each <a href="https://github.com/quasar/QuasarRAT/blob/master/Client/Core/SystemCore.cs#L159">antivirus</a> name that is not null or empty to a <code>StringBuilder</code> (using a newline after each valid name) before returning. Might be good to know if a client has multiple anti-viruses installed.

**Comment by MaxXor** [comment]
I'm aware of this. For me it's not even returning the correct value when I have my Win8.1 in VM running for 1h. This needs to be fixed asap.

**Comment by yankejustin** [comment]
Alrighty. :)

**Comment by MaxXor** [comment]
Can you tell me if it's working with your long-uptime system? My longest uptime is just 35 days.^^
