### ISSUE TITLE
[Client only] WOW64 and the problems

### ISSUE THREAD

**Issue by MaxXor** [quasar/QuasarRAT#352]
Some weeks ago we've switched Quasar's Client to compile for `x86`, instead of `AnyCPU`.

`AnyCPU` had the advantage that it would run the Client as 64-bit process on 64-bit systems and as 32-bit process on 32-bit systems.

Now after the switch it runs on 32- and 64-bit systems as a 32-bit process (on 64-bit system in WOW64 environment). We needed the switch for loading 32-bit DLLs required for the Firefox Password Recovery.

**These are the new problems we're facing now on 64-bit systems:**
- Problems with accessing Registry Keys at `HKEY_LOCAL_MACHINE\\SOFTWARE`
- `Environment.SpecialFolder.System` returning wrong directory (fixed with https://github.com/quasar/QuasarRAT/commit/5e868eb05e953c26591df99524996c9f9c9b83f9)
- Reference: https://en.wikipedia.org/wiki/WoW64#Registry_and_file_system

**What can we do to solve it?**
- **Solution 1**: Implement this: http://www.rhyous.com/2011/01/24/how-read-the-64-bit-registry-from-a-32-bit-application-or-vice-versa/ (also needs change for writing)
- **Solution 2**: Change target framework to .NET Framework 4.0 (Client Profile) (many benefits overall!)
  - More options for `Environment.SpecialFolder`, see [this](http://bit.ly/1PP1aqM), i.e. `SystemX86` or `ProgramFilesX86`
  - Fixes the problems with registry access, see [this](http://bit.ly/1JTnv7M)
- **Solution 3**: Remove support for Firefox Password Recovery and change back to `AnyCPU`

<h1>Please vote for your preferred solution!</h1>
Or if you have another solution, don't hesitate to post it here!

**Comment by yankejustin** [comment]
<b>Solution 2</b>. No reason to re-invent something that has already been made (and likely <i>intensively</i> debugged and perfected before implementation into the framework). On top of that, it offers more modern ways to other ways of approaching things.

**Comment by Panthere** [comment]
Yes, solution 2 sounds fine. You'd be working with Win8 by default then, and most Win7 PC's already have .net 4.0.
Would also cut out illegitimate use of this software as most crypters/packers work with .net 2.0.

Remaking something big, as yanke said is quite cumbersome.
Not exactly sure whats up with firefox recovery and why it requires x86.

**Comment by Vigorian** [comment]
just downloaded new firefox it dont have msvcr100.dll, now it use msvcr120.dll, its not the best solution but we can create plugin system and put the libs from firefox devoloper x64 editon to plugin library(compressed), pinvoke from nss have not changed. Maybe i play some whith it today.

**Comment by SandPox** [comment]
Solution 2 better, now I think all windows 7 computer already have .NET 4.0 and it installed by default on windows 8, windows XP still can install .NET 4.0

**Comment by Vigorian** [comment]
.NET 4.0 is good, but rat written in 3.5, and many features to make a friend, in 4.0 they can be made much smaller.
Plus of  .net 4.0
Easy To do Registry Edditor
Easy To do Plugin System
minus
not all systems have it

**Comment by SandPox** [comment]
@Vigorian server is fine... it does not need change...
same with 3.5, not all windows 8 have it

**Comment by MaxXor** [comment]
Some information about .NET Framework versions and dependencies: https://msdn.microsoft.com/en-us/library/bb822049(v=vs.110).aspx

**Comment by KarlBaumann** [comment]
Actually looks like it is best to use 4.6

**Comment by MaxXor** [comment]
@KarlBaumann No, I don't think this.

@Vigorian When we change the target framework, we're going to change it for both, Client & Server.

**Comment by SandPox** [comment]
@MaxXor no!

**Comment by Panthere** [comment]
Dropping firefox recovery is an option, but 4.0 is a fine choice for things.

**Comment by MaxXor** [comment]
Alright! I'm preparing the changes on the branch `net40`.

**Comment by Panthere** [comment]
I like it, less illegitimate use, more commerical use.

**Comment by rabbitsmith** [comment]
I think its better to stick on to .net 3.5 as 4.0 is not installed in all pcs

**Comment by yankejustin** [comment]
@rabbitsmith Don't assume 3.5 <b>is</b> installed on all Windows machines. By default, .NET v3.5 is <i>not</i> installed on Windows 8/8.1/10.

**Comment by yankejustin** [comment]
@rabbitsmith Strangely enough, Microsoft actually defaults .NET v4.5/4.5.1!

**Comment by SandPox** [comment]
@yankejustin to cut of old version, it will huge setup image size if they include all version to windows... they still can install when they need it

**Comment by yankejustin** [comment]
@SandPox Exactly. The image size is already bloated enough anyways. :laughing: 
Installing the Client Profile version of the framework really isn't as bad anyways.

**Comment by rabbitsmith** [comment]
Setup files for .net 3.5 are already included in the windows installation disks in win8

**Comment by MaxXor** [comment]
We are going to change the target framework to .NET Framework 4.0 Client Profile.
See the updates in `net40` branch.

**Comment by d3agle** [comment]
@Vigorian, that is not a bad idea, but I think there are better ways of handling it.  We could have a surrogate process as a helper for these cases, but firefox doesn't seem to want to release 64-bit publicly yet as there most likely is still a lot of work/testing.

Also like you said, the NSS call interestingly enough I believe works for all versions of firefox.  The earliest version I tested was 3.5.1 and it recovered the data perfectly.  If we really wanted to support every version, we could test the appropriate hierarchy to load the DLLs for each version and adjust the loading of the DLLs accordingly. :D
