### ISSUE TITLE
Error when closing Qasar

### ISSUE THREAD

**Issue by warezhafid** [quasar/QuasarRAT#364]
Hi Max!
I'm having this popup everytime when i close Qasar
![2015-08-28_11-58-36](https://cloud.githubusercontent.com/assets/14013973/9543882/c0547830-4d7c-11e5-962c-cd72eb9dda4c.png)

**Comment by MaxXor** [comment]
Hey, thanks for reporting this, can you compile from the latest commit and confirm it's fixed?

**Comment by warezhafid** [comment]
Fixed!

**Comment by MaxXor** [comment]
Wonderful, thanks for reporting back! :grinning:

**Comment by warezhafid** [comment]
Thanks for the fast fix!
