### ISSUE TITLE
Enter file version bug

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#367]
When i try to build the server i get this message:
"Please enter a valid version number! Example: 1.0.0.0"
I tryed using the 1.0.0.0 example but i still get the same message

![capture](https://cloud.githubusercontent.com/assets/4869819/9692414/f38170f6-5316-11e5-84ed-5c0151adca8d.PNG)

**Comment by MaxXor** [comment]
You need to enter a valid product version... you wrote 2016 in there.

**Comment by webiummedia** [comment]
I tryed that but then i get this:

![capture](https://cloud.githubusercontent.com/assets/4869819/9693004/fb5227c2-531a-11e5-8d77-7d06ad64159e.PNG)

**Comment by webiummedia** [comment]
Also while where at it, if the 2016 was really the issue, the error message should not say valid version numver but product version number cause it gets confusing on the last 2 options "Product version and File version". Also the builder gives the same error when i try to build with the assebly information checkbox unchecked ...

**Comment by MaxXor** [comment]
Be sure to keep the `client.bin` file in the same directory as `Quasar.exe`. Its required for the building process.

**Comment by webiummedia** [comment]
Your right ... it was missing ?! ... thx for the great support ;-)
