### ISSUE TITLE
Renaming question

### ISSUE THREAD

**Issue by Rottweiler** [quasar/QuasarRAT#369]
In http://github.com/quasar/QuasarRAT/blob/master/Server/Core/Build/Renamer.cs

            if (typeDef.Namespace.StartsWith("xClient.Core.Compression")
                || typeDef.Namespace.StartsWith("xClient.Core.Networking")
                || typeDef.Namespace.StartsWith("xClient.Core.NetSerializer")
                || typeDef.Namespace.StartsWith("xClient.Core.ReverseProxy")
                || typeDef.Namespace.StartsWith("xClient.Core.MouseKeyHook")
                || typeDef.Namespace.StartsWith("xClient.Core.Packets")
                || typeDef.Namespace.StartsWith("xClient.Core.Recovery")
                || typeDef.HasInterfaces)
                return;

What is this based off of? Like what in those namespaces isn't compatible with renaming?

**Comment by d3agle** [comment]
I started working on this, but if you wanted to look into it, load up the assembly in a .NET decompiler and you will see what is currently renamed. The namespaces won't be ignored when the design improves.  Basically, any class that implements an interface that we don't have access to modifying (IDisposable) we need to ignore renaming the type, and the virtual methods that interact with the interface.  I haven't determined what else we need to be careful of but if you want to delve into this go for it :P

Here is where I left off if you, or anyone else decides to work on this.

```C#
private void RenameInType(TypeDefinition typeDef)
{
	//if (typeDef.Namespace.StartsWith("xClient.Core.Compression")
	//    || typeDef.Namespace.StartsWith("xClient.Core.Networking")
	//    || typeDef.Namespace.StartsWith("xClient.Core.NetSerializer")
	//    || typeDef.Namespace.StartsWith("xClient.Core.ReverseProxy")
	//    || typeDef.Namespace.StartsWith("xClient.Core.MouseKeyHook")
	//    || typeDef.Namespace.StartsWith("xClient.Core.Packets")
	//    || typeDef.Namespace.StartsWith("xClient.Core.Recovery"))
	//    return;

	if (typeDef.Namespace.StartsWith("xClient.Core.NetSerializer")
		|| typeDef.Namespace.StartsWith("xClient.Core.ReverseProxy")
		|| typeDef.Namespace.StartsWith("xClient.Core.Packets"))
		return;

	_typeOverloader.GiveName(typeDef);

	typeDef.Namespace = string.Empty;

	MemberOverloader methodOverloader = GetMethodOverloader(typeDef);
	MemberOverloader fieldOverloader = GetFieldOverloader(typeDef);
	MemberOverloader eventOverloader = GetEventOverloader(typeDef);

	if (typeDef.HasNestedTypes)
		foreach (TypeDefinition nestedType in typeDef.NestedTypes)
			RenameInType(nestedType);

	if (typeDef.HasMethods)
		foreach (MethodDefinition methodDef in typeDef.Methods.Where(methodDef => (!methodDef.IsConstructor && !methodDef.IsVirtual)))
			methodOverloader.GiveName(methodDef);

	if (typeDef.HasFields)
		foreach (FieldDefinition fieldDef in typeDef.Fields)
			fieldOverloader.GiveName(fieldDef);

	if (typeDef.HasEvents)
		foreach (EventDefinition eventDef in typeDef.Events)
			eventOverloader.GiveName(eventDef);
}
```

**Comment by MaxXor** [comment]
It should be more flexible now.

**Comment by DragonzMaster** [comment]
@StingRaptor you can see this as it might help you.

**Comment by yankejustin** [comment]
@ghost I doubt the change in namespace would mess up deserialization. Perhaps serialization.
Honestly have not taken the time to look into why we need to exclude those namespaces. Would be nice to be able to remove it so we can allow users to obfuscate if necessary without issues . . .
