### ISSUE TITLE
Registry Editor Visuals

### ISSUE THREAD

**Issue by yankejustin** [quasar/QuasarRAT#370]
<h1>Help Wanted</h1>
It would be appreciated if someone could make some images for the Registry Editor I am working on. If you find another's images and suggest I use them, do make sure it is public domain (respect others' work).
I don't have a definite list of images I will need because there are quite a few, but just take a peek at Windows' Registry Editor and see the graphics there as a reference. :)
<hr/>
If you wish to submit your own graphics, I expect that you authorize us at Quasar or anyone contributing to Quasar the right to use or use work derived from your works. I ask for your explicit consent to these terms. Thank you for your cobtributions (suggestions, additions, comments/feedback, and all other forms of contributions). :)

**Comment by d3agle** [comment]
I have an idea I want to throw out there.  What about using the host's icons?  :D  Use the icons as they appear on the host (for the icons with file exts.)

**Comment by yankejustin** [comment]
Good idea, but it probably wouldn't work for linux, right?

**Comment by d3agle** [comment]
That is true, would probably be better not to then xD
