### ISSUE TITLE
Help needed (no connections)

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#371]
Hi i just wanted to make a request for somebody to finish the How to part of the wiki. 

I am having a bad time gething this to work so I might be missing something ... i created a no-ip, port forwarded used the same info in the builder and started the listener using the same info then provided but even after infecting my laptop i still dont see it online...

**Comment by MaxXor** [comment]
The wiki is already on the to-do list.^^

Please check with [this neat website](http://canyouseeme.org/) if your port is correctly opened, then check if your no-ip service points to your current IP.

**Comment by webiummedia** [comment]
Success: I can see your service on **.**.**.161 on port (4782)
and yes no-ip points correcly. I tested the no-ip host here:
http://www.yougetsignal.com/tools/open-ports/
And the port is online
No idea why i am not seeing it online ... My router has everything set up... When i start the listener i get a UPnP error thought. I checked the rooter and UPnP is activated. No idea if that could be the issue ...

**Comment by MaxXor** [comment]
When it says it's open your router is not the issue. Can you test if it's connecting by using your current WAN IP?

**Comment by webiummedia** [comment]
I created a new server with 192.168.2.65 using the same port 4782. Then reinfected my laptop and it still does not come online in the viewer. Firewall and AV (Mcaffe and windows defender) are both turned off.

**Comment by d3agle** [comment]
What version of Quasar are you using?  A released version or compiled version?  What router are you using?  If UPnP is enabled, it should work fine, just don't start the listen server too quickly after opening Quasar, it takes a little bit to broadcast and collect device data.  If you get the UPnP error message, try stopping the listen server and start listening again.

Make sure your local IP is the correct IP that has access to the port.  Depending on your router, it should tell you in either the UPnP settings or if you have forwarded the port manually, somewhere in those settings

**Comment by webiummedia** [comment]
I am using "Quasar v1.1.0.0" from the release section. Should i build the server from the source? I am using a modem/rooter provided by my ISP. Port forward shows that it works. It's been 2h since i first infected my laptop and the listener is not piking up. The UPnP error pops back everytime. Is it required knowing that the forward is set up correcly?

![capture](https://cloud.githubusercontent.com/assets/4869819/9705977/f86b86ee-54a4-11e5-9fb7-de6610b67c84.PNG)

**Comment by d3agle** [comment]
You are probably getting the UPnP error because you already have the port forwarded.  The router is probably trying to create a port that already exists.  Modem/router combinations have always been iffy in my eyes.... Maybe you can try disabling your port forwarding rule, and try using the UPnP option by itself?  I don't know if this will make a difference, but it is worth a try.

**Comment by webiummedia** [comment]
Good sugestion but that did not do the trick. I disabled the port forwarding and made sure UPnP was on the stoped the listener and restarted but i get the same message ...

![capture](https://cloud.githubusercontent.com/assets/4869819/9706000/0310399a-54a6-11e5-8fa0-7d4c976112cb.PNG)

**Comment by d3agle** [comment]
Read my edit above ^, I would also restart the modem gateway just to make sure the settings are fresh on boot.

**Comment by webiummedia** [comment]
Hmm ... well i turned off the rooter, turned off and on the UPnP and now i don't get the UPnP error anymore. Now i can see the server using the 192.168.2.65 but not with the internet IP witch is the most important one i guess lol

**Comment by d3agle** [comment]
What do you mean you can see the server using your local IP?  Do you mean the client connected to the server and in the server you see that?  Or you see it in your router settings under UPnP?

**Comment by webiummedia** [comment]
Well Max sugested earlier that i should try using my local IP instead of the no-ip to see it that works and thats the one that i can see online in the list. I tryed to update the client with the one that uses the no-ip only but it's not going back online.

**Comment by d3agle** [comment]
Ok I understand.  The problem is most likely one of these three things: 
1) The router isn't sending outbound connections to WAN on that port (likely due to a firewall settings in the router), 
2) Your no-ip DNS isn't configured properly (Don't use that site to verify, on your laptop open command prompt and type "ping xxxx.no-ip.org" replace the xxxx.no-ip.org with your DNS).  Make sure the command prompt is getting a reply from that command.  If it says "Requests timed out" something isn't set right. 
3) An application (AV/Firewall) is blocking the connection (On your laptop)

**Comment by d3agle** [comment]
You have the port successfully forwarded and you know the problem isn't with your host machine.  All your troubleshooting can be done now on your laptop.

**Comment by webiummedia** [comment]
Hmmm ... The ping request works from the cmd and also from ping.eu. The IP is also the good one. As for the firewall, It's desabled (Mcafee and windows defender). I can see the process running on the laptop. Theres no firewall on the rooter firmware that i can see.

**Comment by d3agle** [comment]
If I had to guess it would probably be McAfee O_O even though application level it says the firewall might be disabled... I think McAfee is a strong AV and they have modules/services running all the time.  Try googling things like "McAfee + Firewall"

**Comment by webiummedia** [comment]
Hmm ... if that was the case, why did it work with the 192 ip earlier? I crypted the server using fastcrypt.us Do you know one that would completly bypass a laptop running mcafee? Cause i will have to turn it back on at some point lol

**Comment by d3agle** [comment]
Not sure but if I had to guess (assuming I'm right), is that local network socket connections would be allowed, where WAN connections wouldn't be.  Not sure man, sorry!  Hope you get it figured out.

**Comment by webiummedia** [comment]
So closse but yet so fare lol thx for the help dud. Maby Max can take a look into this later

**Comment by d3agle** [comment]
Try adding an exception in McAfee for the Client application

**Comment by webiummedia** [comment]
lol i tryed that 5 minutes ago no result. How can we delete quasar? I will delete everything and infect it with a fresh one ... perhaps all the infections i tryed is blocking the connextion. I think i might have infected it 8 times lol

**Comment by MaxXor** [comment]
@webiummedia Kill the processes with the right "Installname" you chose and delete the files.

**Comment by webiummedia** [comment]
Done ... craps a fresh one did not do the trick ...

UPnP - Working (No message from quasar)
NoIP - Working (Pings)
Port forwarder - Working (tryed on and off)
AV - Killed (unistaled)
Firewall - Killed (unistalled)
Process running (also installed it self in the subdir)

I think I am running out of options ... Is the release in the release section up to date?

**Comment by MaxXor** [comment]
The latest release is not the problem, but if you wish you can always try the [latest build](https://ci.appveyor.com/project/MaxXor/quasarrat/build/BUILD125/job/egcwjb21xahl5i58/artifacts). I just tried it with my DNS and port forwarding and Windows Firewall deactivated (@ Server), worked.

**Comment by webiummedia** [comment]
nope still no luck ... if it's not Quasar then it has to be my rooter ... But it's frustrating cause all the settings are good... And when i check the ping it works fine as well as the port check and no UPnP message. I will try an other network and see how that works out.

**Comment by webiummedia** [comment]
wow that was crazy ... I finally got it running!

So what i did was boot up in kali linux, hacked the WEP key of my neighbor, booted back on windows and use that internet connection for the client. I used my own connection for my PC where the server is. It cam up right away. I guess for some reason, it does not work if both (the client and the server) is on the same IP unless you do it in locally with the 192.x.x.x address. 

Lesson learned ;-) Thx for the help!

**Comment by MaxXor** [comment]
Glad you got it working, well for me it's also working when both are on the same IP.^^

**Comment by royal125** [comment]
I also use quasar rat and it shows my pc but when i restrat pc it doesnt show i think it doesnt hve startup

**Comment by jademanworld** [comment]
Dude the thing that worked for me was to let the program through the firewall by adding it. Then everything worked fine.
