### ISSUE TITLE
Remote hidden file streaming

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#373]
I have an other feature request. I know there's a feature where you can execute a local file on the remote client in hidden mode ... But what we're missing is the ability to execute a remote file (exe) already on the client's computer and see the window output of that file on the servers end but keep it hidden for the remote client. To integrate this feature, when you right click a file in the file manager, add "Remote hidden file streaming". The file would be executed with out the client noticing. It would work a lot like the desktop streaming feature but you would only see that window.

**Comment by rabbitsmith** [comment]
Yes i support this . Its a good idea. This can be very useful.

**Comment by MaxXor** [comment]
Sorry, but I don't think this is possible.

**Comment by webiummedia** [comment]
Yes this is possible. I think the CIA 1.3b rat does this. It's old but this is definitely possible.
http://www.megasecurity.org/trojans/c/cruelintentionz/Cruelintentionz1.3.html
