### ISSUE TITLE
File manager: change the number of simultanious file download / Change speed

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#378]
The file manager can currently download 2 files at once. On low connections that can be a problem. Being able to download only one file at a time would be better to keep the internet unaffected. But on high speed connection, being able to download up to 10 files at a time would really be appreciated. In the file transfer view, It would be really appreciated if we could test the internet speed (a little like speedtest.net) And apply the best optimal setting or manually give the number of threads we would like between 1 and 10. Also being able to set the download speed would be a good thing if you really don't want to lag the end user. A new pannel on the left side of the file manager called "Settings" would be a good place to add all that.

**Comment by MaxXor** [comment]
added to #262
