### ISSUE TITLE
File transfer: File size and estimate download time / pause and resume

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#379]
In the transfer window, please add the file size and estimate download time. Also adding a pause and resume would be a great feature. When a list of files is added to the download window, would it be possible to save the status in case quasar is closed or lost of connection and automatically resume on the next connection?

**Comment by webiummedia** [comment]
I just confirmed that the file manager does not save the progress or even the list of files to be downloaded when we lose connection. Everything is emptied no resume at the moment.

**Comment by yankejustin** [comment]
I agree about this suggestion. Especially in the case where a block isn't correctly sent and ruins the whole progress of a potentially large file. :(

**Comment by d3agle** [comment]
This could be implemented easily and would be a nice addition

**Comment by MaxXor** [comment]
added to #262
