### ISSUE TITLE
File manager: Video streaming / FTP access

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#381]
When it comes to large video files (mp4, avi [...]) of 1gb + it would be great to be able to stream the video to a player capable of reading such like VLC. Perhapse a stream URL could be made based on the users IP?

**Comment by yankejustin** [comment]
This is very very difficult due to the need to keep packet order and because packet loss can cause issues with the video that could mess it up. :"(

**Comment by webiummedia** [comment]
What if the server installs and apache like server that make the file reachable in some way?
x.x.x.x:80/c/video/video.mp4

**Comment by MaxXor** [comment]
Sorry, this will not be added.

**Comment by webiummedia** [comment]
@MaxXor, I really think an FTP access would be very useful as a backdoor but also when you need a more advanced file manager. Please reconsider ...

There's tons of open-source class's that could be easily integrated ...
http://www.codeproject.com/Articles/2558/A-Complete-FTP-Server

**Comment by MaxXor** [comment]
The client would require an opened port in order to access the running FTP-Server...

**Comment by webiummedia** [comment]
@MaxXor what if we do something like this:
http://bytes.com/topic/c-sharp/answers/431643-upnp-code-open-ports-nat-firewall

**Comment by MaxXor** [comment]
It will not work on Routers which have no UPnP enabled. The second link is no solution or option for this.

**Comment by webiummedia** [comment]
In the pwnat source, theirs really nothing we can use to avoid the router problem for this?
https://github.com/samyk/pwnat

pwnat, pronounced "poe-nat", is a tool that allows any number of clients behind NATs to communicate with a server behind a separate NAT with *no* port forwarding *no* DMZ setup, and no 3rd party involvement. The server does not need to know anything about the clients trying to connect.

Seems very "on topic" to me ... How do they do it?
