### ISSUE TITLE
File transfer: Preview download mode

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#383]
In the bitcomet torrent downloader client there's an option you can use called "Preview download mode" where the selected file is downloaded in the correct sequence (from start to end). With that box ticked, you can play the temp file in VLC and view what was downloaded before the file is even finished. Right now when i try to play a video temp file it's unplayable until the file is completely downloaded.

**Comment by yankejustin** [comment]
For these suggestions, perhaps you could demonstrate your suggestions best with a little video of your concept so it is clear to everyone. I think I get what you mean, though.

**Comment by MaxXor** [comment]
Sorry, this will not be added.
