### ISSUE TITLE
Remote Shell: Install/Uninstall MSF button

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#395]
In the remote shell window, It would be great if there was a one button to install/Uninstall MSF on the remote machine. Being able to use MSF commands could help advanced users to gain extra features not yet implemented in the rat.

**Comment by MaxXor** [comment]
Not sure what MSF is, but how about Windows PowerShell (if installed) instead of command line?

**Comment by Crash129** [comment]
I think he means Metasploit Framework
1. It's detected by most AV's
2. It's too large
3. Not really useful. Just create a Meterpreter Payload and upload&execute it.

**Comment by webiummedia** [comment]
PowerShell is a great alternative

**Comment by yankejustin** [comment]
While I won't add something like this anytime soon, it would perhaps be a great plugin for penetration testing.
As I said, it would make a great <i>plugin</i>. I will likely consider this after abstracting. :)

**Comment by MaxXor** [comment]
MSf is too heavy, as an alternative just use powershell in the remote shell by executing "powershell".
