### ISSUE TITLE
Additional Keylogger Settings

### ISSUE THREAD

**Issue by Crash129** [quasar/QuasarRAT#396]
It would be nice to be able to have a checkbox to hide the log directory and a textbox to set the name for the log directory.
Logs could also be encrypted on the harddrive with the AES key used for traffic encryption.

**Comment by yankejustin** [comment]
I like your suggestions to the keylogger.

**Comment by MaxXor** [comment]
I think the keys for the logs should be more dynamic, like the traffic encryption key + date of the log. :+1:

**Comment by yankejustin** [comment]
Sounds neat. I'm about to start work on the Registry Editor now so I can finish it then get to tackling some of these issues.

**Comment by Crash129** [comment]
Traffic encryption key + date of the log would be easy to guess and wouldn't be worth the work needed for doing this. I think the traffic encryption key should be enough.
