### ISSUE TITLE
File manager: Ask only one to delete multiple files

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#398]
I wanted to deletes 10 files so i multiselected and deleted ... but Quasar asked to corfirm for each one of them lol

**Comment by yankejustin** [comment]
@MaxXor Perhaps a <b><code>behavior</code></b> tag should be for suggested changes to the behavior of certain features. This is more of a behavior issue than an enhancement, but I wouldn't qualify it as a bug. x)

**Comment by MaxXor** [comment]
I think `improvement` is this. Then we have `enhancement, improvement and bug`. I will fix this asap.

**Comment by yankejustin** [comment]
Good, thank you. Mind if you assign this to yourself?
