### ISSUE TITLE
I cant make the client work

### ISSUE THREAD

**Issue by ExodusTime** [quasar/QuasarRAT#405]
i can only make it work on my own windows. whenever i try to run it on virtual machine (outside my lan, i didnt try on a vm on my lan) i get the client opening things (PING.EXE and renaming itself to chrome.exe, all ok) but just after that im always getting "chrome.exe stopped working"
always the same, but i can connect myself on my own host.
it doesnt work also on the host outside the lan

**Comment by yankejustin** [comment]
So it does correctly connect to the server, correct?

**Comment by ExodusTime** [comment]
i think not, im trying to do it via noip.com

**Comment by ExodusTime** [comment]
OK! just nothing, found that was my router, it has an own firewall that blocks all non previously requested ports. even with them open, just listening wont pass the firewall, you need to first send something before receive from the requested ports.

I'll close, and Thanks yankejustin
