### ISSUE TITLE
File Manager: Download Folder feature (all files in folder and it's subfolder)

### ISSUE THREAD

**Issue by hakonamatata** [quasar/QuasarRAT#406]
Hi
A nice feature that should be easy to implement is to allow downloading of a folder. Or more presiscly, to recursively download all files in the folder and sub-folders. 

I suggest that when you select a folder and click download, that a pop-up appear asking if you really want to download all files in that folder. Maybe there should be an option to "download files in sub-folders", or just the files in the selected folder. 

PS. I will try implement this myself. Maybe sometime this weekend.

**Comment by yankejustin** [comment]
Good suggestion. A menu box with the following choices:
1. Download folder and (item count) files.
2. Download all files only (item count).
3. Download folder only.

**Comment by MaxXor** [comment]
Added it to the list #262.

**Comment by 0xE232FE** [comment]
Hello there,

is someone on this Task?

I am currently redesign the File-Manager, when its done it would look like FileZilla FTP Client. ;-)

Functionality Planned:
- Download / Upload Folders
- Delete Folders its and content
- Resume Download / Upload
