### ISSUE TITLE
Registry question

### ISSUE THREAD

**Issue by webiummedia** [quasar/QuasarRAT#413]
I need to execute a .cmd file on computer startup. It needs to be invisible (no dos window).
I am pretty sure i can do that from the regedit in quasar but I am unsure how to do it. 

C:\Users\info\start.cmd

thx in advance

**Comment by yankejustin** [comment]
This functionality is not yet implemented onto the Registry Editor. I plan on adding such functionality when I have free time. Most likely over winter break. :)

**Comment by webiummedia** [comment]
untile such a feature exists, how can i do it manually?

**Comment by yankejustin** [comment]
Through Quasar, that would not be possible through the Registry Editor for now.
You could upload a file to the client then add a startup registry key by a different feature on Quasar. :100:
