### ISSUE TITLE
Windows Cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item

### ISSUE THREAD

**Issue by zzredalert** [quasar/QuasarRAT#414]
Hello guys,

Can you guys help me out here? I think i doing something wrong.

Im trying to execute the Quasar client on my computer and always getting this message when exeute the generated client:

"Windows Cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item".

I have no Anti-Virus installed on my Windows 10 computer, also the Windows Defender is turned off and i also excluded the Quasar folder from the Windows Defender scanning.

Thanks in advance.

**Comment by yankejustin** [comment]
Hi zzredalert: could I please have the following information?
1) A few of the settings related to where you have the client saved.
2) Is this client installed on the machine?
3) Is the client executing correctly or does the error message show up then cause the client to exit?
4) Have you tried re-building the client binary? (client.bin)

**Comment by zzredalert** [comment]
Thank you for the reply Yankejustin, i wll try to rebuild it in a couple days and bring the news for you.

**Comment by yankejustin** [comment]
This can be opened once again if it is still an issue for you.
