### ISSUE TITLE
Remote Desktop - Speedup

### ISSUE THREAD

**Issue by datyin** [quasar/QuasarRAT#415]
Instead of using picture box for Remote Desktop Preview you can use this RDP lib (http://sandaruwmp.blogspot.mk/2014/05/remote-desktop-application-with-rdp.html) it is a lot more faster :)

**Comment by yankejustin** [comment]
Perhaps the implementation <i>could</i> be changed to this in the not-so-close future, but I see no big reason to change to this method currently. We get good performance already for this feature.
On a side note, I would be willing to look at benchmarks if you'd be willing to provide them. If they are that significant, I would actually be willing to switch the implementation after I finish the Registry Editor and fix a few bugs in Quasar.

**Comment by yankejustin** [comment]
I also want to put these related thoughts out there for reference:
1. It is very likely that there will still be bottlenecks experienced for similar reasons that are already seen in the current implementation that are unavoidable.
2. RDP clients could likely be another layer of abstraction (i.e.: higher complexity) for a low pay-off.
3. By using such a feature, will we still be able to add features to it (such as the ability to use the mouse pointer)? I feel as though we could, but it would be more difficult.
<b>4. Is it truly a notable improvement on performance?</b>

**Comment by yankejustin** [comment]
@datyin Thank you for your suggestion. If you'd be willing to provide some further information, perhaps it will be moved up our list of priorities. :100:

**Comment by datyin** [comment]
@yankejustin yes, improvement on performance is truly notable. I use your RAT to manage my network computers and even if i loose low quality image it still lags, but with this module you wont notice any lag. :)

**Comment by yankejustin** [comment]
@datyin Would it be possible to provide a little demonstration by forking the repository and providing a basic implementation of such a feature so it can be benchmarked?

**Comment by datyin** [comment]
This method works only for LAN
