### ISSUE TITLE
Could not get password 

### ISSUE THREAD

**Issue by hanbim520** [quasar/QuasarRAT#416]
I use the password function ,but i can't get password on win 10. I down one's code which could get password for chrome ,but not work on ie. I check your code which part on ie and find it does not work too.My english is not good.

**Comment by yankejustin** [comment]
Could you perhaps include your issue in your native language for those of us that perhaps speak it for clarity? :)
<hr />
1. What exactly do you see happening? Does anything come up or do you get no results?
2. Does the password recovery feature function at all on the computer?
3. Have you tried running the application as an administrator?

**Comment by hanbim520** [comment]
Ok,Chinese language.我只是想和你一样研究这些技术，并非用来做一些坏事。我在研究IE密码的时候，发现好像IE的加密方式改变了（Windows 10 OS上），于是Google查资料，接着就找到了您的git 项目，我在win10上编译了这个项目，其他的诸如远程桌面之类没发现什么问题，但是在获取密码的时候出现了问题，抛了异常（对象尚未实例化），接着我调试了代码，发现是获取密码的时候 sqlite里面一个变量未被初始化，是一个空指针（null 指针)。我只调试了chrome部分，然后我改了您的代码，采用了System.Data.Sqlite和微软的安全库，解决了chrome密码的问题（带来了另外的问题就是dll库，应该采用代码方式，我只是用于测试）。IE的我还没搞定。您写的这个工具很棒。另外可以加上法国一位写的Windows密码的获取(C语言实现)，这样在Windows上感觉在密码部分算是差不多完美了。邮件部分的密码、网络密码以及其他的特定的存储本地密码都可以得到。不过使用C或C++写是不是会更好点呢？ 而且要是可以做跨平台的特别是在Linux上操作Windows方面。这些仅我个人看法哈，可能会比较狭隘。

**Comment by XenocodeRCE** [comment]
Put

**Comment by yankejustin** [comment]
I appreciate your comment and suggestions, @hanbim520 
I will get back to you soon regarding both this issue and your suggestions.
Just to be sure, may I have the following information to help resolve this issue please?
1. Operating system and build of the operating system.
2. The browsers that this affects (Chrome, Internet Explorer, Firefox, etc.) and the version of the browser.
3. Do you still have the issue if you run the client program with administrator privileges?

**Comment by hanbim520** [comment]
很抱歉，我最近丢失我的iPhone 6 plus，骇客经常对我的邮箱发钓鱼邮件，也往我的手机发钓鱼短信，目的是想获取我的appleid的密码，从而激活iPhone，我找到了这个hack，但是警方没有能力去调查，他们的技术不够，而我的取证不能作为法律上有效的取证。

OS is WINDOWS 10  professional
it don't work on any browser
I run the client with  administrator privileges (run vs with administrator privileges),but not work.

**Comment by hanbim520** [comment]
C:\Users\zhanghaijun\AppData\Local\Google\Chrome\User Data\Default\Login Data
The first pic showed the path  @XenocodeRCE

**Comment by hanbim520** [comment]
The value is C:\Users\zhanghaijun\AppData\Local\Google\Chrome\User Data\Default\Login Data @XenocodeRCE

**Comment by hanbim520** [comment]
![12 2](https://cloud.githubusercontent.com/assets/7490792/11864637/46a9db88-a4d9-11e5-9bed-b0dcd69369f2.png)

![13](https://cloud.githubusercontent.com/assets/7490792/11864655/6f5b2f3c-a4d9-11e5-82e9-c565ccdd3c70.png)


这两个网站的管理员邮箱给我发钓鱼，国外的（英国和美国），我无法联系这两家公司。请看到的美国朋友，联系下这两家公司！

**Comment by hanbim520** [comment]
Received: from 184.173.153.36 (unknown [184.173.153.36])
	by newmx24.qq.com (NewMx) with SMTP id 
	for <710605420@qq.com>; Thu, 17 Dec 2015 16:09:46 +0800
X-QQ-FEAT: ac+oSjEisxVZO081NbwL1vc/qoje9GNSAFz13TqXPlK1vT2d9063Q7cnb7NZ2
	IOq82KlCn3WyYseWSLOHXFo3Z5zWTRYj0ijDc8G3J95pDAhjha6pmbCHjPSFmaFU+Fh+cc7
	Y1MoBwzvH6EZDwun3ex7w7nmQ1mQ2ADkpHRrI+Ov7Pa8V8NzNSQs42OxgD7K6GgJUp3Dm36
	+fSyxa90Tb6gbm4h1iR7rHLqZTNc40C3ud37GDMcqtwYKSOvl6Ucjv9JDACQ7R8Y=
X-QQ-MAILINFO: Nj4k/6lmmRCS0X3djWa4eN6nEkmznJxnyGP6qQJYWn8C9CD6zAOgIDYHc
	IF2AoGvzhS1YuXtxb9vSenTIUcXWL5jy9vChAxflpNNKTdethQ5m9oInBRGSgbHNmturst0
	dQcbYXSc/JLY6nUc2or8JlszgrH9NdsIig==
X-QQ-mid: usamxproxy14t1450339812tpg1iqe
X-QQ-CSender: mailgun.org#admin@aminio.com
X-QQ-ORGSender: bounce+ecd0af.337a37-710605420=qq.com@mailgun.org
X-KK-mid:usamxproxy14t1450339812tpg1iqe

**Comment by hanbim520** [comment]
Haven't fix the bug yet

**Comment by hanbim520** [comment]
Run on windows 10

**Comment by HasanYeah** [comment]
Could this possibly help? https://github.com/ashumkin/Chrome-passwords

**Comment by HasanYeah** [comment]
Or maybe this? http://www.codeforge.com/article/249225
