### ISSUE TITLE
Interface enhancements

### ISSUE THREAD

**Issue by bitterypaul** [quasar/QuasarRAT#418]
I think QuasarRAT will work well with [ MaterialSkin ](https://github.com/IgnaceMaes/MaterialSkin) It suports WinForms and hence compatible with Mono on Linux

[OxyPlot](https://github.com/oxyplot/oxyplot) to add a graph for inbound and outbound transfers.

**Comment by yankejustin** [comment]
Thank you for the suggestion, but we will not be using WinForms.
