### ISSUE TITLE
Windows service

### ISSUE THREAD

**Issue by bitterypaul** [quasar/QuasarRAT#419]
[winsw](https://github.com/kohsuke/winsw) can be used to run quasarRAT as a service.

**Comment by yankejustin** [comment]
In the future, it would be more preferable to just make a comment for the issue that this is under. Thank you for the suggestion, though!

**Comment by SandPox** [comment]
It will not possible to capture screen if you're running on SYSTEM privilege, the screen will totally black out because SYSTEM desktop is not real. Unless you could execute a separated screen capture module as regular user

**Comment by tidusjar** [comment]
Is NSSM not an option?

**Comment by yankejustin** [comment]
Could you please explain that acronym? I try to make the least amount of assumptions. :)

**Comment by tidusjar** [comment]
Haha sorry! [NSSM](https://nssm.cc/)
