### ISSUE TITLE
Webcam Example Project

### ISSUE THREAD

**Issue by DragonzMaster** [quasar/QuasarRAT#424]
Hi,
First of all I know there is already an issue opened about webcam
but I successed to make a small program to get webcams and their resolutions and I've tested it and works perfectly (I've used some examples available on AForge website). 
What good about this that it dosen't need any other dlls or files - even in resources - as I have used Aforge.NET framework and I've included the needed namespaces (Video & Video.DirectShow) to the project so no dlls are needed.
Finally I tried to add it to server/client but I failed so If anyone can do this and make Quasar support webcam , **I will upload the project If someone wanted to give it a look.**
So Please can one of you do this @yankejustin & @MaxXor & @SandPox ??
Project files : http://s000.tinyupload.com/index.php?file_id=94309153948467441039

**Comment by MaxXor** [comment]
Thank you for this. I've downloaded the project files and will look into it over the next few days.

**Comment by yankejustin** [comment]
I have access to a webcam now. I will look into this at some point as well. Thank you! :smile:

**Comment by DragonzMaster** [comment]
I hope you find this useful. :smile:

**Comment by MK73DS** [comment]
Hi :)
I'm very hyped about this feature and I want to know if this is still on work ^^
I'd love to help you (I would already make it if I know how to do that ^^) but unfortunatly my skills are limited to just "Enter your name : " .. "Hello [NAME] !" ^^

Anyway, thank you very much for your work on it and I hope this will be integrated soonly in Quasar :)
And sorry for my english too ^^"
