### ISSUE TITLE
Obfuscation prevents RegistryEditor from working properly

### ISSUE THREAD

**Issue by StingRaptor** [quasar/QuasarRAT#426]
After some research on issue: #425, I have found that the crashes most certainly are caused by the obfuscation that is performed during the build process of the client.

The client-side serializer will in this case generate a representation  of the registry that cannot be deserialized on the server, and through this causes a exception to be thrown that disconnects the client.

**Comment by DragonzMaster** [comment]
Did you mean the renamer ??
It is not the first time that renamer cause problems in release config.
I remember that the keylogger face such problem and it was solved by excluding some of keylogger namespaces so we can try the same with registry editor namespaces but first we have to know which one cause this problem.

**Comment by StingRaptor** [comment]
Yes, the `Renamer` is the root cause of the problem. To confirm this I added a check to prevent the `Renamer` from obfuscation the Registry namespace which seems to have solved the problem.

**Comment by DragonzMaster** [comment]
you can see #369 , I don't know if it will hep you or no.

**Comment by StingRaptor** [comment]
Thanks, @DragonzMaster this is how i solved the problem. I'll try and get everything pushed to my fork later today and hopefully make a pull request tomorrow.
