### ISSUE TITLE
Question about adding new packets

### ISSUE THREAD

**Issue by DragonzMaster** [quasar/QuasarRAT#429]
I've tried to add new feature to the project and I've used Task Manager as an example and I added 
- [GetConnections] to server packets
- [GetConnectionsResponse] to client packets

and added a handler for both packets but the server throw the following Exception : 

+	Exception thrown: 'System.InvalidOperationException' in Quasar.exe ("Unknown type xServer.Core.Packets.ServerPackets.GetConnections")	System.InvalidOperationException

and the client disconnect and reconnect again but nothing happens.
So please can anyone help and tell me what's wrong !!

**Comment by MaxXor** [comment]
Did you add the packets to the client & server?

**Comment by DragonzMaster** [comment]
yes, I do. I've added packets to both client and server (Core/Packets).

**Comment by MaxXor** [comment]
Could you show me in your fork what you've added?

**Comment by DragonzMaster** [comment]
OK, give me a couple of minute and I will inform you when it is ready.

**Comment by DragonzMaster** [comment]
You can find the code here
https://github.com/DragonzMaster/QuasarRAT/tree/TCP-con
Sorry, I know that the code may be bad but I'll try to clean it up.

**Comment by LostSoulFly** [comment]
It doesn't look like you've added them into the Serializer for both the Client and Server under QuasarClient.cs ad QuasarServer.cs

**Comment by MaxXor** [comment]
@LostSoulFly is right.

**Comment by DragonzMaster** [comment]
@MaxXor - @LostSoulFly Thank you for your help, now I can try again and see if it is working.
