### ISSUE TITLE
I can't edit forms of the project

### ISSUE THREAD

**Issue by korom42** [quasar/QuasarRAT#434]
Hi all .. I am not familiar with c# 
When I try to edit any thing on main form (even ContexMenu) and build the project it become without listview like this ... how to fix this plz
![1kg40vy](https://cloud.githubusercontent.com/assets/18078699/14056803/2ad7bde2-f2f1-11e5-8d07-6306b577bb1b.png)
Thank is advance

**Comment by DragonzMaster** [comment]
Quasar use custom ListView (AeroListView) and it is working fine for me

**Comment by korom42** [comment]
I really do not know why I have this problem , just downloaded the rar again and extract at first I always have this error , when I try to edit any thing the main form became like in first post screenshot
![screenshot_31](https://cloud.githubusercontent.com/assets/18078699/14060086/9cbfaa02-f358-11e5-9347-e0ced4af74d5.jpg)

**Comment by DragonzMaster** [comment]
Aha, You can easily solve this problem by running the server for at least one time in debug config then open frmMain design and it should works now :smile:

**Comment by korom42** [comment]
Thanks mate it works , I can't believe how stupid I was thank you very much again .

**Comment by DragonzMaster** [comment]
You are welcome. No problem sometimes we miss somethings like that :smile: 
Please, Now can you can close this issue ??
