### ISSUE TITLE
Advanced Fun Panel - Improvement

### ISSUE THREAD

**Issue by korom42** [quasar/QuasarRAT#435]
Hey,
I am suggesting to add an advanced fun panel , something like in picture below , I've all necessary codes if needed for both client and server :) 

![1ed7gsq](https://cloud.githubusercontent.com/assets/18078699/14086742/91ab0e46-f51e-11e5-9a99-da1ca0eff5d9.png)
![6hbucwv](https://cloud.githubusercontent.com/assets/18078699/14086745/926bea76-f51e-11e5-84a0-ac91c1e1024d.png)
![kdhtsnf](https://cloud.githubusercontent.com/assets/18078699/14086746/927584d2-f51e-11e5-8bf2-7655c58bc3ec.png)
![kydpqiy](https://cloud.githubusercontent.com/assets/18078699/14086747/92f9bf22-f51e-11e5-86eb-03fd07257149.png)

**Comment by Trapaceiro** [comment]
These functions are really good ...
I suggest that "Lock / Unlock Mouse" and "Lock / Unlock Keyboard" options are separated! Also on the MessageBox, there is a "none" option so that no icon appears in the message.

**Comment by MaxXor** [comment]
Sorry, a fun panel will not be added.
