### ISSUE TITLE
pupy Explit & QuasarRAT C# ClassLibrary DLL INJECTION POSSIBLE?

### ISSUE THREAD

**Issue by kainpark7894** [quasar/QuasarRAT#436]
QuasarRAT C# ClassLibrary DLL INJECTION POSSIBLE?

Default -> C# Client.exe -> Bulid Client.bin PE File 

My Class Library Compile DLL ->Explorer.exe and Anyway 32bit&64bit DLL injection No execute Code

Hide injection Client.Bin ->  DLL comfile Possible?

ex) reflective dll injection

https://github.com/dismantl/ImprovedReflectiveDLLInjection

**Comment by MK73DS** [comment]
Does that mean that the client will launch as administrator when explorer.exe is launched ?

**Comment by kainpark7894** [comment]
pe format file taskmgr.exe View No Hidden
but dll format file Reflective INJECTION Hide Code injection(explorer.exe,iexplorer.exe,etc systemfile)
C# file Reflective Injection impossible? or Hide Client.exe -> DLL Injection What support?

**Comment by 0xE232FE** [comment]
What about System Integritychecks. Change explorer.exe and run the sfc /scannow command from commandprompt. The modified explorer.exe will be replaced over the original one.

If you want to gain Administration privilage try to figure out which Antivirus Programm the client uses and give him an Update. Remote Execute an Loader Programm that gain Administration privilage, Download the Latest version of the Virusscanner and Fake an important Update of the already installed Virusscanner. Once you have got Admin prviliage with your Loader you can modify the Privilage of Quasar at the same time. So the victim doesn't know whats going on ;-) and might give you admin privialge. Even if the client cancel the installtion after the admin priviallage you already modfied the privilage of Quasar and the Setup is only a side effect. ;-)
