### ISSUE TITLE
Client loses Administrator privileges on restart

### ISSUE THREAD

**Issue by MK73DS** [quasar/QuasarRAT#440]
Hi :)

Is it possible to autostart the client as administrator ?
It's quiet annoying to always request administrator's rights, and wait for my little brother to accept it ^^

Thank you :)

**Comment by DragonzMaster** [comment]
I think you can easily edit the client manifest.

**Comment by MaxXor** [comment]
There is an issue I'm already aware of. When the client is installed with administrator privileges, once the machine is restarted it loses this and only has user privileges. :/

**Comment by MK73DS** [comment]
Thank you for giving more details and I hope someone will be able to fix this :)

**Comment by MaxXor** [comment]
I'm going to work on this next week, no problem.

**Comment by MK73DS** [comment]
Okay thank you very much :)

**Comment by LostSoulFly** [comment]
I've done research on auto-elevating in the past and I wasn't able to find a legit solution other than digitally signing the EXE or running it as a service.

What are your ideas to make this work?

**Comment by MK73DS** [comment]
I don't know anything about signing but why can't this be implemented ?

**Comment by yankejustin** [comment]
@MK73DS Quite certain that signing it costs money.

**Comment by darknet1990** [comment]
@yankejustin Hi how i can contact you ? maybe we have some deal

**Comment by yankejustin** [comment]
@darknet1990 MaxXor would be the one to contact regarding those decisions about the project since it is his. :)

**Comment by yankejustin** [comment]
@darknet1990 Thank you though.

**Comment by Rottweiler** [comment]
Are tasks available in XP and below? Try experimenting with tasks, I think there are some solutions to this problem here http://stackoverflow.com/questions/5427673/how-to-run-a-program-automatically-as-admin-on-windows-startup

**Comment by Pandry** [comment]
Maybe this would work:
http://www.sevenforums.com/tutorials/11949-elevated-program-shortcut-without-uac-prompt-create.html
:D

**Comment by dmgamingstudios** [comment]
What did work for me was adding it to windows services in the registry, not to the default, do note that at the time I tested it windows actually thought it was a critical service, so when the program was exited or crashed, the whole system crashes with a nice bsod: critical process died

I think this is where you need to add it: LocalMachine\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System

**Comment by mehmetgoksu** [comment]
how you fix it ,ı look the code but ı cant see can you explain maxxor ?

**Comment by MaxXor** [comment]
When executed with administrator privileges, Quasar now creates a scheduled task (which is executed on user logon) to acquire administrator privileges after reboot/logout. At the moment Quasar is being installed as "per-user", this means when the user with installed Quasar is not logged in, the remote control functionality is not accessible. I'll soon start adding support for installing Quasar as a windows service, so remote control is always available when the machine is booted.

**Comment by mehmetgoksu** [comment]
thank you for answer
