### ISSUE TITLE
Qussion About (For each client c in SelectedClients)

### ISSUE THREAD

**Issue by darknet1990** [quasar/QuasarRAT#443]
Hello Everyone i just need an answer for my Qussion and to understant more 
Here is my code  !!

Foreach (Client c in SelectedClients)
{

 //# Here can i put any command wich every client will make it ??  Like >>

  System.IO.Directory.Delete("C:\Jony", true);

  //# every client in the list will delete this folder ??

}

**Comment by DragonzMaster** [comment]
It should send the command to each client that is selected in the Listview in main form.

**Comment by darknet1990** [comment]
Thank You @DragonzMaster   I mean there is no need to write any class in (client and server ) this code will excute what i want ? @DragonzMaster

**Comment by DragonzMaster** [comment]
yup you don't need to do that, but remember that this command will only will be sent **ONLY** to selected clients (may be 1,2 or 20 ... etc...) **NOT** all of them (except you have selected all the clients).
You can add a new item to context-menu and double click on it to add the code like you mentioned in the first comment.

**Comment by darknet1990** [comment]
i think this code will send this message box to all the conected clients maybe i have more than 300 clients )));

foreach(Client c in GetConnectedClients())
            {
                MessageBox.Show("Hello ,,,,,");
            }

**Comment by DragonzMaster** [comment]
Sorry, this code won't work. you should do what I've mentioned before (adding new packets ,edit handler and add packets to serializer.

**Comment by DragonzMaster** [comment]
This project uses this style to manage and add packets and make it serliazable.

**Comment by LostSoulFly** [comment]
Looks like you just want to delete a specific folder on each of the connect clients?

You wouldn't need to add your own packet, just use .DoPathDelete

`        private void deleteToolStripMenuItem_Click(object sender, EventArgs e)
        {
            int count = lstDirectory.SelectedItems.Count;
            if (count == 0) return;
            if (MessageBox.Show(string.Format("Are you sure you want to delete {0} file(s)?", count),
                "Delete Confirmation", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                foreach (ListViewItem files in lstDirectory.SelectedItems)
                {
                    PathType type = (PathType)files.Tag;

                    switch (type)
                    {
                        case PathType.Directory:
                        case PathType.File:
                            string path = GetAbsolutePath(files.SubItems[0].Text);
                            if (_connectClient != null)
                                new Core.Packets.ServerPackets.DoPathDelete(path, type).Execute(_connectClient);
                            break;
                    }
                }
            }
        }`

**Comment by darknet1990** [comment]
Yes Thanks for all answers i understand at the end that i can write my code (**foreach**) and put my command like **my code**  between it ..
@LostSoulFly it was just an example i want to execute a long script in all **connected clients** but my command line is very long and complicated this why i asked this Qussion  to avoid making any classes and serializer / packets ... if i am wrong please explain more ...

**Comment by DragonzMaster** [comment]
Unfortunately as I've mentioned before you have to add **new packets/edit handler/add packets to serializer** to make the code run on your clients, I think you can't just add your code between **for-each** block as ** the server only send packets NOT code blocks **

**Comment by darknet1990** [comment]
yes you are true i actually tried just now and it **dont work**  !! 
it is just working on my one computer but others on my network **no**

**Comment by LostSoulFly** [comment]
@DragonzMaster is correct, I was misunderstanding your goal. If you are only putting your code between a "for each", it's only going to run on the server itself and not the clients.

**Comment by DragonzMaster** [comment]
I will try to simplify how it works.
The server only send and recieve packets and these packet hold data between the server and client, some of them are server packets like **GetConnections** and the others are client packets like **GetConnectionsResponse** and must be added to both of server and client.
These packets are serialized using NetSerializer to make easy to travel over network and of course they are compressed.
Then there are the handlers as there mission to deal with the data received from/sent to => server/client and do most of the magic using these data like adding them to listview or delete file .... etc.
Now I hope you understand how it is working so simply you can't just add the code between **foreach** block as the code will only executed on your machine and doesn't even travel over network.

**Comment by darknet1990** [comment]
Yes @DragonzMaster thank you for your Explain i thout it will be easy but it seems i need some time to understant how it works spichaly this all of classes and packets i am c# porgramer but its my first time work in an client and server Project >>>

**Comment by DragonzMaster** [comment]
No problem, I've faced the same thing the first time I tried to add a new feature but It's very easy and not that complicated. :smile: and you can guide with any existed feature and you will know how it works.
May be I can help you with the feature you want to add.

**Comment by darknet1990** [comment]
@DragonzMaster how can i contact you via what ? wich feature do you added ?

**Comment by DragonzMaster** [comment]
You can fork the project and see if I can help you. I've added TCP Connections feature.

**Comment by darknet1990** [comment]
online i cannot put **my project **
