### ISSUE TITLE
Why The clients Dont work without Admin Permission ?

### ISSUE THREAD

**Issue by darknet1990** [quasar/QuasarRAT#444]
Hi if anybody wants to open the client.exe in the windows 10 its working and its shows in the task manger after 15 secounds its gone without showing any connected client in the listview

But if we open the client as admin in windows its working normaly 
there is a command line i think where the client dont work without this permission how can i desable it?
i think this admin permission is not so good for clients spichaly at network of an large company >>  most computers dont have the ** adminstartor permision**

**Comment by yankejustin** [comment]
In large companies, generally the IT administrators will grant permission where necessary. Large companies tend to have well-configured permissions on company machines. :smile: 
I do wonder if first part is a bug though... Hmmm...

**Comment by darknet1990** [comment]
@yankejustin  hi i have some deal with you how can i contact you ?

**Comment by darknet1990** [comment]
@yankejustin how can i remove this admin permission ?

**Comment by MaxXor** [comment]
The client doesn't need admin privileges, even on Windows 10. Did you chose to install the client to a directory which requires admin privileges?
