### ISSUE TITLE
Memory leak when using remote desktop.

### ISSUE THREAD

**Issue by lixiaoyan** [quasar/QuasarRAT#446]

**Comment by MaxXor** [comment]
Can you provide more information?

**Comment by lixiaoyan** [comment]
By using Perfmon, I found the Process Handle Count continues to increase
when using remote desktop.

**Comment by lixiaoyan** [comment]
<https://github.com/quasar/QuasarRAT/blob/master/Server/Core/Utilities/FrameCounter.cs#L53-L58>

**Comment by MaxXor** [comment]
Hm, I can't see why this line should cause a memory leak.

**Comment by yankejustin** [comment]
Last I checked, I believe that remote desktop still leaks a little bit. But I do not think the leak is from that line of code. I do not see how it would.
