### ISSUE TITLE
Not being able to elevate client permissions

### ISSUE THREAD

**Issue by MK73DS** [quasar/QuasarRAT#447]
Hi :)

When I want to elevate client permissions, every thing bugs and I have to reconnect to my client :(

Thank's for helping :D Both me and my client are on Windows 10 :)

**Comment by MaxXor** [comment]
What do you mean by "every thing bugs"? Does it bug on server or client side?

**Comment by MK73DS** [comment]
I mean, I got disconnected from my client and I have to restart Quasar.
But now it's working fine, I don't know what happened this time ^^

So you can close this issue :) Thank you anyway for answering :)

**Comment by MaxXor** [comment]
When elevating the client permissions, the client will be restarted. :smile:
