### ISSUE TITLE
Not being able to find the clients country.

### ISSUE THREAD

**Issue by SpanishCat** [quasar/QuasarRAT#451]
I have no clue if it's just me but every time I test the client to make sure it works it doesn't show the country it keeps say 'Unknown [-]' and that's about it. Plus it doesn't even show an icon it only shows a '?'

**Comment by MaxXor** [comment]
Yep, it's using this site for geolocation: https://freegeoip.net/
... and it's down. :(

**Comment by SpanishCat** [comment]
Is it possible to b changed? If so, then how?

**Comment by MaxXor** [comment]
Sure, but we'll need to find a new service for providing the information.
Here are the lines of code which need to be changed then: https://github.com/quasar/QuasarRAT/blob/master/Client/Core/Helper/GeoLocationHelper.cs#L121

**Comment by SpanishCat** [comment]
I found these websites: 

https://www.iplocation.net/

http://www.ipfingerprints.com/

http://www.ip-tracker.org/

Are these good?

**Comment by Jaakus** [comment]
The site is up now.

**Comment by MaxXor** [comment]
@Jaakus Thanks, good news!
