### ISSUE TITLE
Client Builder Exception on Windows XP SP3

### ISSUE THREAD

**Issue by JhonnyU** [quasar/QuasarRAT#452]
Hey everyone, what's up?! I'm having trouble creating the server in windows xp SP3.. This screen appears. What should I do?!

![dibujo](https://cloud.githubusercontent.com/assets/19156286/14992588/0fccf188-113d-11e6-97db-fa32c57ccf2c.JPG)

Regarding webcam support, will the function to see the infected's computer webcam be included??

I look foward to hearing from you.
Thank you

**Comment by MaxXor** [comment]
Please extract all files from the zip file or when you build in release mode, be sure to keep the client.bin file in your quasar folder.

Webcam support will be included soon.

**Comment by JhonnyU** [comment]
Thank you so much!
