### ISSUE TITLE
Form not showing correctly

### ISSUE THREAD

**Issue by hakonamatata** [quasar/QuasarRAT#453]
When I open, run or compile the program it always looks like this: 

![Image of Yaktocat](http://i.imgur.com/LudCkbc.png)

The forms are not shown correctly.

**Comment by MaxXor** [comment]
What resolution does your monitor have? And do you use DPI scaling?

**Comment by hakonamatata** [comment]
I have a large 4k display, 3840 x 2160 resolution. In Control Panel\Appearance and Personalisation\Display\ The scaling level is set to 150% by default.

**Comment by MaxXor** [comment]
Okay, guessed it. Can you try removing line 23-27 from [this file](https://github.com/quasar/QuasarRAT/blob/master/Server/app.manifest), recompile it and tell me if it worked?

**Comment by hakonamatata** [comment]
Yeah, that worked! Thanks! 

It also works with: 
` <dpiAware>false</dpiAware>`

I am not familiar with this setting, why was it used?

**Comment by MaxXor** [comment]
It was a suggested fix for issue #423, but it was only for the Client and I accidently added it for the Server too.
