### ISSUE TITLE
try to portforward using UPnP(Enabled) - BUG

### ISSUE THREAD

**Issue by reymarbc** [quasar/QuasarRAT#457]
Settings -> try to portforward using UPnP (Enabled) -> Start listening to port -> save.

program hangs after exiting it.
but not actually terminating, it just remains running in the screen.

**Comment by MaxXor** [comment]
Hm, I can't really reproduce this issue. Can you tell me the exact steps to reproduce this behaviour on your PC. Could you please describe it with a fresh installation and default settings?

Thanks!

**Comment by reymarbc** [comment]
*Open Quasar Server
*Settings
*Try to portforward using UPnP(Enabled/Checked/Ticked) 
*Start listening to any port
*Save
*Exit Quasar Server
*Bug

**Comment by MaxXor** [comment]
For me it's not freezing when I follow your steps. Are you sure your router has UPnP support enabled?

**Comment by reymarbc** [comment]
Maybe its my router issue,  I already enabled the UPnP feature in my router.
