### ISSUE TITLE
Quasar isnt listening correctly.

### ISSUE THREAD

**Issue by omerbadawy11** [quasar/QuasarRAT#470]
I have my port 2008 forwarded and UPnP on, when i make a rat on localhost:2008 it works fine, But when i make it on my own IP or a DNS it doesn't work. i tried can you see me and it says "could not see your service",Any help ? Thanks.

**Comment by MaxXor** [comment]
Check if your router has UPnP enabled or open the port manually. Quasar is listening correctly.

**Comment by omerbadawy11** [comment]
Rude.. Actually the problem was cause of firewall it was blocking quasar..  You closed the the issue without even bothering to ask if your solution worked.

**Comment by MaxXor** [comment]
Sorry, if it sounded rude. I'm glad you found the problem.
