### ISSUE TITLE
Compile client for windows xp (.net framework 2.0)

### ISSUE THREAD

**Issue by hackereg35** [quasar/QuasarRAT#477]
when i change the Target framework to ".NET framework 2.0"
the compiler get about 91 error most of them is
`The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)`
is there is anyway to do that

**Comment by MaxXor** [comment]
Compiling for other frameworks than 4.0 is not supported. You can fully replace all instructions from the Linq namespace manually by foreach loops.

**Comment by hackereg35** [comment]
ok i can do that, but i dont know how to resolve this error
`Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute`
in 
`private static bool IsNameOrValueNull(this string keyName, RegistryKey key)`

**Comment by MaxXor** [comment]
.NET 2.0 doesn't support extension methods. You'll need to replace them all with static helper methods. Anyways I don't give support for downgrading Quasar to an outdated framework version.
~Closed
