### ISSUE TITLE
Wrong Country Detection

### ISSUE THREAD

**Issue by anonymousssssssss** [quasar/QuasarRAT#482]
![](http://i.imgur.com/KZkZyyq.png)

**Comment by MaxXor** [comment]
This is out of my range as I use the API provided by https://freegeoip.net/

**Comment by anonymousssssssss** [comment]
It seems that there is a bug in your code.
When I go to https://freegeoip.net/xml/<IP> i get a valid response including a (the correct) country code.
In QR it doesn't work.
I would suggest using another API like http://ip-api.com which also supports the ISP.

Keep up the good work.

**Comment by MaxXor** [comment]
You say, you get a valid response from freegeoip.net. Can you send me it (& anonymize ip). Important is only the country code.

**Comment by anonymousssssssss** [comment]
Here it is, I found it in my history.
I'm not sure this is going to help though.
![image](https://cloud.githubusercontent.com/assets/20488468/17256482/f70c36c0-55bd-11e6-8ca5-88d3410cd759.png)

**Comment by anonymousssssssss** [comment]
There is definitely a bug somewhere, because the last day I had a client with the same IP once from `Sweden`, and a few hours later he was from the `US`.
