### ISSUE TITLE
No new connections when running client on different PC's

### ISSUE THREAD

**Issue by TrintionBruh** [quasar/QuasarRAT#497]
I can't see any new connections when running the RAT client on different PC's. Once I was done building it, I took the client and put it onto another computer in my home and when I ran it, there wasn't any connection on my other computer which was running the rat program itself. I get connection refused on port 4782 even though I portforwarded and I allowed it through my firewall, with the program itself too. I dont know if I need to use my local ip address or my ipv4 address for no-ip. Also, does the hostname/IP in the connections tab need to use the no-ip address or the ip address? thank you.

**Comment by MaxXor** [comment]
It's definitely your firewall what's blocking Quasar. Please open the port 4782 TCP in Windows Firewall and your router to. Configure your router to forward port 4782 to your local computer to the same port.

**Comment by TrintionBruh** [comment]
Ok also, in my ipv6 firewall settings in my router, should I click enable incoming traffic at the bottom?
https://gyazo.com/9c3d5ea20773debe9a72308223cb8de6

**Comment by TrintionBruh** [comment]
I also get this in my routers firewall settings https://gyazo.com/25d9b619694ea19af130f4881c63034e

**Comment by TrintionBruh** [comment]
I just tried everything and it didn't work for me. Still no new connections when I try to add the no-ip to the host in the builder. https://gyazo.com/726341ecc6d7fa10e82f22af6bd532af also says connection refused again and it says everywhere the port is still closed. https://gyazo.com/1eb5b5ebf5b404ccd7970d5cc17b268a

**Comment by TrintionBruh** [comment]
it just started saying the port is successfully going but I still also get the request timed out in CMD https://gyazo.com/8ee9bf477ab8d2b61453a7fef8abe96e

**Comment by TrintionBruh** [comment]
Not exactly sure what I'm doing wrong. https://gyazo.com/6699d9cf80ee5c01b7df99d399525ee4 here's a screenshot of everything. Port is forwarded, port is allowed through firewall and it is also showing that it's being used when I'm listening. But I still get the request timed out.

**Comment by MaxXor** [comment]
Try it out to see if it's working, it doesn't matter if your IP is reachable via ICMP (ping). It should work now.

**Comment by TrintionBruh** [comment]
Alright it works, I had to get a friend to test it out by using his own network/IP and it worked.

**Comment by TrintionBruh** [comment]
Thank you.

**Comment by TrintionBruh** [comment]
Am I able to use control PC's on my own network though? Like if I infected another machine on my wifi will I be able to control it from my main machine with the program on it?

**Comment by MaxXor** [comment]
Of course you can use Quasar only in your local area network. Internet connection is not needed for it to work. For example if your server is running on the LAN IP 192.168.172.2 then just build a client which connects to the server IP and then install it on every computer in your LAN. Your dynamic dns is not needed for it to work on LAN.

**Comment by TrintionBruh** [comment]
Alright thank you for your help, Appreciate it. I've gotten my problems answered.

**Comment by MaxXor** [comment]
No problem! Thanks for using Quasar. :)
