### ISSUE TITLE
License Consideration

### ISSUE THREAD

**Issue by Abdullah2993** [quasar/QuasarRAT#499]
Consider using a more Open License like MIT, Apache or BSD

**Comment by MaxXor** [comment]
Ehm, I'm not sure about this. But can you explain the benefits of changing the license? I like the part of the current license that everyone who publishes a modified version of Quasar has to provide the source code with it too.

**Comment by Abdullah2993** [comment]
Well GPLv3 was nice at early stages to build a community around quasar but now the community is built. Now its time for a more open license which allows users to modify it privately for their use cases. MIT is the way to go.

**Comment by yankejustin** [comment]
If I am thinking of the correct license, you should be able to modify the code and such as long as you do not distribute it commercially (for money), right? If so, I think that the current license is sufficient...
