### ISSUE TITLE
Geolocation via ip-api.com not available in China

### ISSUE THREAD

**Issue by 1135** [quasar/QuasarRAT#500]

**Comment by 1135** [comment]
because the GFW ,the website http://ip-api.com could not be visited in China.

**Comment by MaxXor** [comment]
What about the fallback?
https://github.com/quasar/QuasarRAT/blob/master/Client/Core/Helper/GeoLocationHelper.cs#L115

**Comment by 1135** [comment]
@MaxXor   I'm sorry, I don't understand.
In fact if a website is blocked by GFW, can only send request but cannot got the response.

Is there a help?
https://en.wikipedia.org/wiki/Great_Firewall


ps:  I'm in China. I was able to access Facebook and Wikipedia, because I used the VPN.

**Comment by hanbim520** [comment]
recommend http://www.ip138.com/ in Mainland China ，中国大陆基本采用这个就可以了。长城防火墙阻挡了很多网站。最好判断下当前的时区位于哪个国家，也可以判断操作系统的语言。然后选择查询IP地址的网站。Translate these words with Google

**Comment by kmahyyg** [comment]
Why not try the IP2Location LITE DB?

**Comment by kmahyyg** [comment]
close this issue , plz

**Comment by hanbim520** [comment]
#Close

**Comment by hanbim520** [comment]
Close #1135

**Comment by hanbim520** [comment]
closed #1135

**Comment by hanbim520** [comment]
closed #500

**Comment by MaxXor** [comment]
Fixed in https://github.com/quasar/QuasarRAT/commit/574713307d37d69d710a404d861380ce83753495
