### ISSUE TITLE
Any chance creating a C++ client?

### ISSUE THREAD

**Issue by dummy0stud** [quasar/QuasarRAT#503]
It is very boring to install .net, consider creating a C++ client!

**Comment by yankejustin** [comment]
Besides the huge pain that would come with converting to C++, there are run-time components that would have to be installed for C++ regardless, so no. I very seriously doubt there is a chance of it. If someone was willing to convert it to C++, that would be neat to see though.

**Comment by MaxXor** [comment]
We use many C# libraries in Quasar, for example Mono or NetSerializer. When converting the client to C++ we need to find replacements for these libraries or redo them from scratch. As @yankejustin said, this is very unlikely someone will actually do this. I'm not going to do it.
