### ISSUE TITLE
"Cannot find client.bin" 

### ISSUE THREAD

**Issue by Korons** [quasar/QuasarRAT#508]
When run with mono 4.4.2.11 on linux (Ubuntu 16.04) the builder errors out with "Cannot find client.bin".

**Comment by MaxXor** [comment]
Please extract all files from the zip if you are using a release from [here](https://github.com/quasar/QuasarRAT/releases).

**Comment by Korons** [comment]
@MaxXor I built it from source. It seems that `if (!File.Exists("client.bin"))` in 'Forms/FrmBuilder.cs' is returning true no matter if the file exists or not.

**Comment by MaxXor** [comment]
Can you check if the file exists on your system after building it in `release` configuration? `File.Exists` returns also false when you got no permission to access the file.

**Comment by MaxXor** [comment]
Can you try opening terminal inside the directory and then execute the Server by `mono Quasar.exe`?

**Comment by Korons** [comment]
@MaxXor If I launch it with `mono Quasar.exe` it seems to work fine and can build the client, but if I right click and select `open with mono` it fails. I have no idea what's causing this but it's safe to say it isn't a bug in Quasar

**Comment by MaxXor** [comment]
The cause for this is that for the building process the working directory needs to be the Quasar directory. I think when you select to open it with mono, it uses a different directory.
