### ISSUE TITLE
Client without .net

### ISSUE THREAD

**Issue by dummy0stud** [quasar/QuasarRAT#516]
Looking at loaded modules at process explorer it is possible to see all dlls loaded by client.exe, if we take these loaded dlls and put in the same directory of client.exe in other machine without .net will it work? 
There is any way to make client.exe working without the whole .net4.0?

**Comment by UbbeLoL** [comment]
I'm working on a c++ quasar client that will work on systems without .NET installed and also operating systems other than Windows. No promises though.

https://github.com/UbbeLoL/Native-QuasarClient

**Comment by mvrozanti** [comment]
What I've been doing is to create a standalone with the bytes of the client + .NET 4.0 Client Profile installation wizard. By running it with "/q /norestart" it is invisible and at the same time won't restart the target machine. If the machine has .NET installed the standalone just executes the client.

**Comment by dummy0stud** [comment]
@mvrozanti is your .NET 4.0 Client Profile installation wizard 40mb? can you provide some sample?

**Comment by mvrozanti** [comment]
Yes the 40 MB one. I can't upload at the moment but it's easy enough in Visual Studio. Create a project
Add the wizard by dragging it to the project in Project Explorer. Set in that object's properties to embed to application. This will pack the file you included to be inside the exe. You can then extract the file to the disc by calling Assembly.GetExecutingAssembly().GetManifestResourceStream("wizardFileNameInsideProject"). This will return you the Stream associated with the embeded file. Read that to the end and you got the bytes of the wizard. With File.WriteBytes you can now run it in the target machine with the arguments mentioned before. I can explain a little further if you have trouble. Good luck

**Comment by dummy0stud** [comment]
@mvrozanti 40mb is too big I don't think I will do it but thank you, @MaxXor there is any way to port Client to .net 3.5?

**Comment by mvrozanti** [comment]
If target machine has internet connection then you could download the client and then exec it. I think we cannot port it to 3.5 without ridding it of some functionalities. I understand the pain brother, win7 :x

**Comment by dummy0stud** [comment]
@mvrozanti I changed project configs to .net 3.5 and did not get too much errors, I think I am going to port it to .net 3.5

**Comment by 54Pany** [comment]
@dummy0stud 
.net 3.5 is 231.5M,so you changed the project configs to .net 3.5 is unusefulness

**Comment by dummy0stud** [comment]
@54Pany but windows 7 ships with 3.5 so there is no need to download it, it looks like it is more complicated than I thought to port quasar to 3.5 if anyone can help me I thanks

**Comment by mvrozanti** [comment]
If I understand correctly your problem is that you want to port to 3.5 _because_ of the incompatibility with Windows systems that do not have the 3.5 .NET framework am I right? If that's the case why don't you have your program download _and_ execute the Client Profile Installer of your choice? "Oh but what if the computer is not connected to the web or the download fails?" - then you could try and have the same program written in C++ instead of C#. Then you will be able to be .NET-free. In C# you may not. Maybe if you use third party software like Xamarin, TurboStudio or alikes (I'm guessing here, you'll have to Google that further because I didn't find jack).

**Comment by dummy0stud** [comment]
@mvrozanti thank you I am going to think about your words

**Comment by hanbim520** [comment]
https://github.com/hanbim520/PasswordLibrary.git  Now it' empty ,this saturday i'll push the project
