### ISSUE TITLE
How to debug Client ?

### ISSUE THREAD

**Issue by TadbirPaydar** [quasar/QuasarRAT#519]
Hello.
I want to Debug client.
Please tell me how ?

**Comment by MaxXor** [comment]
Build it with your [desired settings](https://github.com/quasar/QuasarRAT/blob/master/Client/Config/Settings.cs#L13) in debug configuration. If you want to debug it with installation enabled you have to attach the Visual Studio Debugger once it's installed and running.

**Comment by TadbirPaydar** [comment]
Thank you for fast answering.
You mean i set desired settings in client and after that build the project.
and run client and attach VS debugger to it.
Yes ?

**Comment by hanbim520** [comment]
set client project as active

**Comment by MaxXor** [comment]
Exactly.
