### ISSUE TITLE
Reverse Proxy Enhancement | Need this ASAP! Please, help!

### ISSUE THREAD

**Issue by AdeptMT** [quasar/QuasarRAT#521]
I recently downloaded Quasar, only to test the reverse proxy feature and I was pleasantly surprised with its stability and speed.

The feature as it is already works like a charm but I'd make a few modifications. Sadly, I lack the technical know-how to do so myself.

This is what I personally need and would love to see implemented:
The ability to reserve local server ports for selected clients and when they connect they are immediately available as a reverse proxy at the assigned port. Essentially, it's an on-connect/on-join reverse proxy.

How I imagine this being done:
Have a file named "proxies.xml" in the Quasar directory.
Its contents would look something like this:
```
<proxies>
<hwid>port</hwid>
<74534224>3843</74534224>
<proxies>
```
Whenever the client with hardwareID of "74534224" connects, he/she is automatically started as a reverse proxy on local server port 3843 and I can connect to it at 127.0.0.1:3843.

Could you kindly show me how to modify the source code in order to achieve the above. I will very gladly send some PP your way if you help me out.

**Comment by MaxXor** [comment]
I don't think this is useful for anyone else than you, so I'll close this here.
