### ISSUE TITLE
Some changes work in DEBUG but not RELEASE

### ISSUE THREAD

**Issue by TadbirPaydar** [quasar/QuasarRAT#522]
Hello
I added one feature.
When i test it in Debug mode it works correctly.
But when i use it in Release mode it doesnt work.
I also added this feature in assembly to be True or False.

What is problem ?

**Comment by MaxXor** [comment]
I can only guess. Show me the code.

**Comment by 0xE232FE** [comment]
Same for File-Explorer feature. When I use the Release Version of Quasar Server I don't get Directory Listing in the ListView of the File-Explorer Window. When i click the Refresh button the Client Disconnects.

If I use the Debug Version of Quasar Server the File-Explorer works without any problems!

**Comment by d3agle** [comment]
I noticed this as well, happens when running `release mode configuration in IDE`.  Some features will not work correctly, others will.

**Comment by MaxXor** [comment]
The release configuration is not meant to be used in the IDE, debugging won't work too. Only use the release configuration when you also want to build your client via the in-built builder, otherwise use the debug configuration.

**Comment by Perturabo** [comment]
If live-debugging isn't working in Visual Studio, how are you debugging your client ?

**Comment by MaxXor** [comment]
Use debug configuration.

**Comment by MaxXor** [comment]
@0xE232FE @d3agle What exactly do you mean? I've built the client & server both in release and debug mode and everything works flawlessly, even tested to connect the debug client to the release server. The File Manager worked in all cases. Can you tell me the steps to reproduce the issue?

**Comment by Perturabo** [comment]
I have encountered issues while playing with the code.
If client/server packets are differents, the Serializers (client/Server side) will be differents.
=> The TypeMapping will be different too, so if you send an GetAuthentication() packet from the client, the server will understand it as a DoClientUninstall().

Use step-by-step debugging & check if Serializer() (both client/server side) have the same number of registered/mapped packets.

It was the solution for me.

**Comment by MaxXor** [comment]
@Perturabo Yes, that's intended as NetSerializer provides no versioning of the types but is therefore faster and has a smaller footprint. Every change to the packets will break the communication with the old server.

**Comment by Perturabo** [comment]
Imo the system is fine.

Back to the original problem, you should first check differences between DEBUG & RELEASE mode.
Try finding all occurences in Visual Studio of 'DEBUG'.
Code like "#if DEBUG [...]" might change the behaviour of your app in debug/release mode.
