### ISSUE TITLE
Faster way sending and receiving packets

### ISSUE THREAD

**Issue by dummy0stud** [quasar/QuasarRAT#524]
I implement my own class to comunicate with client using the same client instance of FrmRemoteDesktop

```
FrmRemoteDesktop frmRDP = new FrmRemoteDesktop(c);
frmRDPT = new MyForm(c);
```
and I save it in frmRDPT:
```
_connectClient = c;
```

sending the packet:
```
new Core.Packets.ServerPackets.DoShowMyClass(data).Execute(_connectClient);
```

the client receives and sends back:
```
new Packets.ClientPackets.SetStatus("Log "+ tt.data).Execute(client);
```

Everything works fine but it takes 2-3 seconds to send and receive data (testing in my virtual machine)! The question is, why it is taking so long to send it back? Can I send/receive it faster?

**Comment by dummy0stud** [comment]
I "solved" my problem executing the code async in the client, anyway, I Am using the correct way to comunicate with client?

**Comment by MaxXor** [comment]
Yep, looking good.
