### ISSUE TITLE
Scheduled task only runs when on AC

### ISSUE THREAD

**Issue by GodsVictory** [quasar/QuasarRAT#525]
This is fine for desktops, but when a laptop is ran on battery, the client will not startup.

There are 2 alternatives that I have found:

1) Create a XML file when building the clients containing the scheduled task

2) Use a windows service instead

I posted a solution to creating windows services on an old post. It replaces the schtasks command in startup.cs with this:

```
ProcessStartInfo startInfo = new ProcessStartInfo("sc")
{
    Arguments = "create \"" + Settings.STARTUPKEY + "\" binpath= \"" + ClientData.CurrentPath + "\" start= auto",
    UseShellExecute = false,
    CreateNoWindow = true
};

Process p = Process.Start(startInfo);
p.WaitForExit(1000);
if (p.ExitCode == 0) return true;
```

Edit: The service does not currently work correctly. Windows waits for a "Service Started" message within 30 seconds of starting the service. I will see if I can figure out how to implement ServiceMain to support it.

**Comment by dummy0stud** [comment]
"but when a laptop is ran on battery", are you sure about this?

**Comment by GodsVictory** [comment]
yes?

**Comment by MaxXor** [comment]
This belongs to #244 second point:
> Add ability to install Client as Windows Service
