### ISSUE TITLE
Suggestion: Session Hijacking functionality

### ISSUE THREAD

**Issue by kkar** [quasar/QuasarRAT#526]
It would be nice if a pentester had the ability to dump browsers' cookies, to conduct a session hijacking attack.

**Comment by MaxXor** [comment]
This tool is not really for pentesting, you can use the file manager and upload your tools on the remote computer.

**Comment by kkar** [comment]
Oh believe it! It is being used for pentests, and it's actually on top of my pentest tools! :) But a session hijacking module... would be great!
