### ISSUE TITLE
Client crash when no network connection is available.

### ISSUE THREAD

**Issue by Dantrum** [quasar/QuasarRAT#529]
I've encountered a crash when running the client on a Windows 7 VMware machine with the Network Adapter option set to not connected. Basically this sets the Windows 7 LAN connection to "Network cable unplugged".

> Problem signature:
>   Problem Event Name:   CLR20r3
>   Problem Signature 01: clienttest.exe
>   Problem Signature 02: 6.1.7600.16385
>   Problem Signature 03: 57dc97ba
>   Problem Signature 04: System
>   Problem Signature 05: 4.6.1075.0
>   Problem Signature 06: 56cfa343
>   Problem Signature 07: 781
>   Problem Signature 08: 12
>   Problem Signature 09: System.Net.Sockets.Socket
>   OS Version:   6.1.7601.2.1.0.256.1
>   Locale ID:    2067
>   Additional Information 1: 0a9e
>   Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
>   Additional Information 3: 0a9e
>   Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

I've been trying to reproduce the error in visual studio with the client in debug mode (don't use a 127.0.0.1 or internal IP) but so far it just exits with the following:

> The program '[10636] Client.vshost.exe: Program Trace' has exited with code 0 (0x0).
> The program '[10636] Client.vshost.exe' has exited with code 0 (0x0).

**Comment by MaxXor** [comment]
` CLR20r3` indicates you are using the wrong target framework. Did you compile the client or try to run it on .NET Framework version below 4.0? Quasar doesn't support this.

**Comment by Dantrum** [comment]
Build and ran on the latest .NET Framework, I suspect it has something to do with how VMware handles network connections since I'm unable to reproduce outside of VMware.

**Comment by MaxXor** [comment]
I can not reproduce this on VMWare Workstation 12.
