### ISSUE TITLE
Native Language & Small Bug?

### ISSUE THREAD

**Issue by BSOfficial** [quasar/QuasarRAT#530]
This is just probably a typical bug report, but "AccountType" is a bit buggy. It still shows User even when I'm Admin. I've seen many rat softwares have problems with this, but some do not. Do you have a better solution or method on how to check for admin.

Also, How do you check the Language like "(LANGUAGE) (COUNTRY)" I found out how you worked the format with United States [US]

The way this is setup, I doubt you can help me with the requesting language, thats just a guess because normally you would use CultureInfo, but the code is not setup like that because I attempted to that, and it did not go as planned..

**Comment by MaxXor** [comment]
Even when your windows user account is the only administrator on your computer doesn't mean it will start every application with administrator permissions and that's what Quasar checks. It's feature, not a bug.

It's the geolocation of the IP. See here: https://github.com/quasar/QuasarRAT/blob/master/Client/Core/Helper/GeoLocationHelper.cs
