### ISSUE TITLE
Version 1.3.0.0 will be released soon ?

### ISSUE THREAD

**Issue by luckystr1keno7** [quasar/QuasarRAT#532]
Hi MaxXor,

Any news about a new version of QuasarRat this year ? 1.2.0.0 is almost a year old, any thoughts about continuing this project ?

**Comment by MaxXor** [comment]
Actually I wanted to release v1.3.0.0 last month, but it will be 100% this month. You can already check out the preview here: https://ci.appveyor.com/project/MaxXor/quasarrat/build/BUILD272/job/qnv54o0wrfvqo8ai/artifacts

**Comment by luckystr1keno7** [comment]
Great news...can't wait to see the new 1.3.0.0 soon, hopefully it will be full on enhancements and new features...

**Comment by MaxXor** [comment]
The changelog is already here: https://github.com/quasar/QuasarRAT/blob/master/CHANGELOG.md#quasar-v1300-tba

**Comment by MaxXor** [comment]
There you go: https://github.com/quasar/QuasarRAT/releases/tag/v1.3.0.0
