### ISSUE TITLE
Socket Error 10107

### ISSUE THREAD

**Issue by blacker123** [quasar/QuasarRAT#533]
I Have problem with start listening
![default](https://cloud.githubusercontent.com/assets/22390735/18779955/f25ba736-8183-11e6-88d2-cb9c92fef12a.png)

**Comment by MaxXor** [comment]
Never seen this error before, try running Quasar as administrator.

**Comment by Panthere** [comment]
http://stackoverflow.com/questions/30107597/node-js-10107-a-system-call-has-failed
Looks like you simply need to reset winsock.
