### ISSUE TITLE
Client must be compiled with .Net 1.1 or at last 2.0

### ISSUE THREAD

**Issue by kevinalbarton** [quasar/QuasarRAT#540]
As you know Windows XP comes with .Net framework 1.1 installed and Windows 7 and later come with .Net framework 2.0 and later.
So to easier run and distribute client, it is recommended to change the Client code in a way that can be compiled with .Net 1.1 or at last .Net 2.0
Because if someone are to run client on a Win 7 he/she must first install .Net framework 4.0 and it is frustrating.
Any way thanks for your nice work.

Regards,
Kevin

**Comment by MaxXor** [comment]
I don't see a problem to install .NET Framework 4.0 on Windows XP to 7 when you use Quasar for legitimate purposes. ;)

**Comment by kevinalbarton** [comment]
Hi,

But I am to install it on my son and daughter pc's, they are below 18
years, and I am to track their activities.
I can not install .Net framework on their machines but can ask them to run
an exe as a fake video player.
So it is legitimate.

Regards,
Kevin

**Comment by EnricoVogt** [comment]
Seems legit :-P
