### ISSUE TITLE
Use new icons

### ISSUE THREAD

**Issue by DragonzMaster** [quasar/QuasarRAT#544]
I've searched for new and modern icons to use and I found this site:
[FlatIcon](http://www.flaticon.com/)

It has really nice icons we can use them as they mention in this article:
[How I must insert the attribution?](http://support.flaticon.com/hc/en-us/articles/207248209)

**Comment by MaxXor** [comment]
I'll stick with my favorite icons ([Silk Icons](http://www.famfamfam.com/lab/icons/silk/)).
