### ISSUE TITLE
Operation did not complete successfully because the file contains a virus or potentially unwanted software.

### ISSUE THREAD

**Issue by manikantad** [quasar/QuasarRAT#545]
Hi ,

Not able to build the project ,when i was try to build the project facing issue like Found Some malware. windows defender removing it.
Even i have checked in defender logs ,that was showing like this "**This program is used to create viruses, worms or other malware.**"
Please find the screen shots below.
![issue4](https://cloud.githubusercontent.com/assets/22674966/19683138/a4d04f94-9ace-11e6-9c2a-25ab593eebd9.PNG)
![issue3](https://cloud.githubusercontent.com/assets/22674966/19683139/a4db4de0-9ace-11e6-92e6-212537b82c1c.PNG)

![issue2](https://cloud.githubusercontent.com/assets/22674966/19683048/0ed0e850-9ace-11e6-9460-c1206caf3ffa.PNG)
![issue1](https://cloud.githubusercontent.com/assets/22674966/19683047/0ecbd8d8-9ace-11e6-9aab-e844767d3273.PNG)

**Comment by Abdullah2993** [comment]
add an exclusion for project folder in your antivirus

**Comment by manikantad** [comment]
We can add that exclusion but as a security context this is showing high priority malware right,how we can over come this.

**Comment by dudelard** [comment]
In a security context, every client built will be detected as a potential virus.
If you don't want to add an exclusion, do not use Quasar.

**Comment by MaxXor** [comment]
Adding an exception for Quasar in your antivirus is the only way because Quasar is used for malicious purposes by some people...

**Comment by TommyWhite** [comment]
Is there any way to modify the Quasar in order to bypass AV? Make new PE signature wich will be undetectable.

**Comment by 0xE232FE** [comment]
You can crypt the Executable and run it with a Loader Programm that Decyrypt it in Memory and Execute the Assembly from Memory in Memory. AV is unable to scan other Memory Spaces. You can make a Loader in any language like C in my opinion is the best and easiest way. The simpler the loader is that harder is it for AV to detect. If you rise the complexity AV concerns something. You can block and re-Route Memory Access or Access by AVs. If your Loader isn't known or going Public on Virustotal you can be sure its safe!

First rule for Crypter is do not Copy & Paste!
Write your own Code and be as much creative as possible.
Do not encrypt or Obfuscate it with Standard tools. Create your own Obfuscate Algorithm.
If you want to fix AV Signature Detections you can change the Code within Assembler. For Heuristic Detections change program flow! Thats all. There is not 100% Guarantee to stay undetected forever but there is quiet a small chance for a Detection!

**Comment by TommyWhite** [comment]
That would be great wrap app agent with something like this,
https://stackoverflow.com/questions/826398/is-it-possible-to-dynamically-compile-and-execute-c-sharp-code-fragments
And invoke it dynamically, in run time.

**Comment by Scatterblak** [comment]
> add an exclusion for project folder in your antivirus

Incredibly bad idea. All you'll be doing then is building software that can only run on one machine,

**Comment by BurntDog** [comment]
> > add an exclusion for project folder in your antivirus
> 
> Incredibly bad idea. All you'll be doing then is building software that can only run on one machine,

If you're using it in a legit manner then a exclusion wouldn't be a issue.

**Comment by BurntDog** [comment]
> > > > add an exclusion for project folder in your antivirus
> > > 
> > > 
> > > Incredibly bad idea. All you'll be doing then is building software that can only run on one machine,
> > 
> > 
> > > If you're using it in a legit manner then a exclusion wouldn't be a issue.
> 
> It's an issue if you're writing software for a living, and someone else is going to run your software someday. Unless you're fine with asking all of your users to start adding exclusions just to get your software to run.

Look up how and what needs to be done to help keep software off AV list, it's very costly. No one in their right mind would pay those fees for software that is free. People misuse  tools like this and that's why they are detected in the first place.
