### ISSUE TITLE
Not an Issue, just a doubt: Is this RAT works only on router?

### ISSUE THREAD

**Issue by udaybhasker007** [quasar/QuasarRAT#550]
I used my WAN IP and forwarded port on router and also used No-IP for dns and ran in sandboxie, it's showing me the client. But when I run the client on other IP its not showing.

And also does it uses encrypted SSL/TLS traffic?

**Comment by 0xE232FE** [comment]
Encryption: yes
Client needs outgoing Connection only!
Server needs incoming connections over Public IP on the Internet!

All Devices that supports Mono or .Net should work. If your router is Linux Based and Mono is installed I see no Problem! But I would like to ask why you want to run the Server on Router...

**Comment by 0xE232FE** [comment]
Sorry this Rat only works on Windows,Linux and Mac who can execute Mono or DOT Net program!

**Comment by udaybhasker007** [comment]
I am working on Windows and I use TP Link. When I run in sandbox it's showing me the client. But when I use the client on other machine with different IP its not showing me the client. Both are connected on same ISP.

I checked in my router it showed me Mono for port listening.

**Comment by udaybhasker007** [comment]
I worked with a Dynamic IP and every feature is working like butter. Thanks for your replies.
