### ISSUE TITLE
can you add passive connections like radmin?

### ISSUE THREAD

**Issue by ckhker** [quasar/QuasarRAT#551]
i want contorl my web server,but i have no public ip. the server is public ip

**Comment by 0xE232FE** [comment]
Please don't get me wrong but for remote admin a Webserver or VPS or Dedicated Server please use ssh/vpn for this its more secure and you have direct connection!!! So far you can route your traffic through tor if you have to stay anonymous!

On Windows Servers you can just use Remote Desktop Protocol, or either setup a VPN and then use RDP.

Quasar is going to separate the server from the Admin Panel and the client is separated already!

You need Public IP for Quasar Server atm but you need only outgoing connection to connect to your Servers public IP everything else is doing your Carrier grade Nat.

Have a nice day.

**Comment by MaxXor** [comment]
See  #541
