### ISSUE TITLE
Client still accessible but keylogger has stopped 

### ISSUE THREAD

**Issue by Cowboy-Curtis** [quasar/QuasarRAT#554]
I've been testing quasarrat for a while now, and after almost exactly 10 days the keylogger is no longer outputting any new data.  I know the PC is in use, remote desktop surveillance, etc. all work.  Is there any way to reset the program remotely to try and fix this?  Will remotely executing the executable again work?

Update:  I had local access to the desktop in question so I just closed the process and ran the executable again, it's working now.  Would still like to know why it stopped in the first place.  I know the user sometimes uses a japanese keyboard (in windows) but it never had problems handling that input before (since the key presses are the same regardless).

Update 2:  Just noticed today that the system clock on the PC seems to be failing, it was showing a time quite a bit behind what it should be.  Would this screw up the keylogger?

**Comment by MaxXor** [comment]
It's possible that the failing system clock caused this issue. It's a bit hard for me to debug it cause of the 10 days runtime needed. Maybe you can find out if it's working with corrected system clock. Japanese keyboard should be no problem.

**Comment by Galaden** [comment]
Nope, nothing to do with the clock
![time](https://cloud.githubusercontent.com/assets/13715233/20651858/eb13d700-b4f5-11e6-8af2-37e1a76718ce.PNG)

**Comment by Cowboy-Curtis** [comment]
I'm assuming now that maybe it was writing to a log file from previous day or something if the clock was actually off, it wasn't something I was paying attention to at the time so I can't really check it now.  It hasn't had any problems since I reset it though so I'm not sure what the issue was.  I know this wasn't much info to go on, I was mostly just posting this to see if anyone had any thoughts.  One thing I should note was that the computer was put in sleep mode every day and not shut down or reset, and it also suffered from some pretty severe network connectivity issues, but I don't think either of those would have affected it (The logging stopped in the middle of a day).

**Comment by Cowboy-Curtis** [comment]
Another update:  I don't think this is the same issue as last time, but when I tried downloading logs today, the window would never update.  I checked with the file manager and the log file on the client pc was at 0 bytes, even though I know it had data as of the previous day (in the early AM).  I deleted the file and logging started working again.  Sadly I lost the data between then and last I checked but it wasn't a big deal.

**Comment by Cowboy-Curtis** [comment]
So this keeps happening and I'm not sure what's causing it, the logs never show anything that would be unusual keyboard activity right before it stops logging.  Since it's such a nebulous problem I had two suggestions, the first would be a way to get the PID of the process on the remote machine (probably something to implement in an enhanced task manager), and the second would be a way to restart the process remotely.  Right now my method is to find the PID and put it in a script that kills the current process and runs the executable again, it would be nice if this was a feature built into quasar just in case the program stops functioning client side.
