### ISSUE TITLE
Remote Webcam keeps crashing

### ISSUE THREAD

**Issue by ValonK** [quasar/QuasarRAT#555]
Maybe it is just me but the Remote Webcam keeps crashing. No image showing keeps crashing after button interaction.
I will try to fix this , just want to know if anybody got the same Problem?

Regards

**Comment by MaxXor** [comment]
Can you check if your webcam driver is installed correctly and can you test with other webcam if it's working?

**Comment by ValonK** [comment]
Ok i will test your suggestions and then give a feedback.

**Comment by ValonK** [comment]
Ive tested on 10 machines now with correct installed drivers. And different cameras. 
Always keeps crashing instantly
