### ISSUE TITLE
Things that is needed.

### ISSUE THREAD

**Issue by KX-Reaper** [quasar/QuasarRAT#557]
There are several things i miss from Quasar RAT, ill make a list.

-Disable windows firewall
-Disable Security Center
-Disable windows update
-Firewall bypass
-Persistent process
-Persistent installation
-Hide task manager ctrl+alt+del

I guess several people miss this and would love to have this added. Thanks for reading my opinion.

**Comment by MaxXor** [comment]
Persistence and other stuff like this will not be added (see #81).
The firewall bypass is pretty easy just use port 443 for your quasar server, no firewall blocks https traffic.

**Comment by KX-Reaper** [comment]
I got my questions ansvered, thanks for quick response.
