### ISSUE TITLE
Multiple desktop

### ISSUE THREAD

**Issue by chico-depressive** [quasar/QuasarRAT#562]
There is any way I can monitor events from other desktop using quasar(setwindowshookEx returns ERROR_ACCESS_DENIED), maybe creating some other process inside target desktop?

**Comment by MaxXor** [comment]
What do you mean? You can select the monitor if the client has multiple available.

**Comment by chico-depressive** [comment]
@MaxXor sorry, my english is not good, I am trying to run quasarClient inside another desktop, but when SetwindowshookEx is called(inside MouseKeyHook Library) an exception is raised with last error "ERROR_ACCESS_DENIED", I am not sure what is going on, because quasarClient is running inside another desktop as Elevated

**Comment by chico-depressive** [comment]
the other desktop had ACL, problem solved
