### ISSUE TITLE
Some Issues and Request: Server in Listening Mode

### ISSUE THREAD

**Issue by seventhplug** [quasar/QuasarRAT#564]
Hello.. I'm using this to monitor our School Computer Lab..  (I'm the Network Admin) ^_^ Sometimes When  the teachers/students  turn on the computer first when the server is still offline.. the client pc  post an error.  and the clients won't reconnect to server when i turn on the server (when they login few minutes earlier than me) i use your RAT (lightweight and free rather than the commercial monitoring software) to monitor the teachers activity and students during school hours. I hope you could add a feature that enables listening mode in client instead of the client connecting to server during start up. Thank You!

PS. I'm having issues with this when using deepfreeze the client wont reconnect to server during thawed mode (having and RPC error or somesort) and after freezing the client wont reconnect again. Thanks.. other than that your program is awesome.. thanks

**Comment by yankejustin** [comment]
Hmmm... My initial guess is because the client expects the server to already be online when the client is functioning...
1) You stated that the client pc posts an error. What was that error that it gives?
2) Do you still experience the first issue when you are not running deepfreeze?

**Comment by seventhplug** [comment]
Hi.. Sorry i've been out because of Christmas Season and now i'm back.. I figured out why the clients Wont Connect and cause an error when the clients are started before the server.. Because i used IP and PC Name as a Connection Host.. Now i use only IP.. and about the Clients not connecting sometimes and not working  its because the client is starting the client program twice .. 1 in Scheduler and the other one is in HKCU .. i removed the HKCU entry and its working fine.. About the deepfreeze no issue when in frozen state.. only in thawed mode i'm having issues with.. in order to overcome this i boot on thawed and in safemode and remove the client program then reboot in normal mode thawed and its ok again.. then before i freeze it again i reinstall the client ^_^ its a bit troublesome but i'll try to test it again on the week ends when there's no class. thanks
