### ISSUE TITLE
Crypter

### ISSUE THREAD

**Issue by wellos** [quasar/QuasarRAT#566]
Im trying to pack the client in a crypter, but when i do so i receive an error message, that redirects me to this page: https://support.microsoft.com/de-de/kb/2715633.
As far as i understood this means, that the payload could not be executed, since it is written in IL for the CLR of .NET. 
Did someone successfully crypt the payload ? If yes, I would be happy to know :)

**Comment by MaxXor** [comment]
You are wrong here.
