### ISSUE TITLE
Multiple Desktop Connections

### ISSUE THREAD

**Issue by chico-depressive** [quasar/QuasarRAT#567]
I was thinking, there is any way to connect 2 clients from different desktops from the same machine?

ex: clientDesk1.exe and clientDesk2.exe connected to a server.exe?

Concatenating desktop name with instance mutex should work, but what about the connection?

**Comment by seventhplug** [comment]
i think you can do that.. in Client Builder just build 2 different client for 2 different server

Ex. 
	client 1... change client tag and mutex, connection settings --> connection host.. put the 1 server.. 
	then in the Installation Settings Set the Install directory to System 
	
	then create another client with different client tag mutex, connection host put the other server.. then in the installation settings change the install directory to "Program Files" so it wont overwrite the other one.

	since the startup is set in the registry and in the scheduler

	
	1 client ----> connecting to 2 monitoring Servers ^_^

	i think this will work .. tho i havent tried it yet..

**Comment by MaxXor** [comment]
Yes, as @seventhplug said. Just change the mutex and installation name (so they don't override each other).
