### ISSUE TITLE
File Manager Options - Job Offer

### ISSUE THREAD

**Issue by luckystr1keno7** [quasar/QuasarRAT#569]
Hey everyone,

This program needs an update for the file manager and a "search for file" option....when using the File Manager to navigate through the files and folders, you never know when the folder was created or last modified...if you are looking at lots of folders you are always in the dark because you don't know what stuff is new and what stuff is old...you definitely need to add the file attribute :  file date modified, just like the ones in DarkComet.....

Another very good option just like the one in DarkComet would be to add a "search for file" menu and the search results found to be clickable and openable in the File Manager  ...

 eg : replacement for dir  *.pdf  /s  in remote shell ( the results found to be clickable, so that the directory that holds that specific search result to be opened in File Manager )

P.S - I know all these (file attributes and search) can be done through Remote Shell but hey, we all know that takes a lot of time and in many ways time is a luxury when using this program :)
I will offer a donation of $250 via BTC for anybody who wants to implement this through Pull Requests, MaxXor can merge the request when he gets some spare time, but I will definitely use it till than....it will be my Christmas gift for everyone using this amazing tool

**Comment by ValonK** [comment]
Sure i can do that just tell me when to start

**Comment by UbbeLoL** [comment]
I'm also willing to do this. Add me on Skype: maddnias1 and we can discuss what features you'd like more in-depth.

**Comment by luckystr1keno7** [comment]
Project Assigned to UbbeLol since he has provided contact information (no offense ValonK, but on Github there is no way to contact other members unless they provide the details themselves)

Ok, UbbeLol, I will add your Skype and talk to you soon .  The email listed on your profile is active ? Because if it is I will drop you an email as well...C ya soon

**Comment by UbbeLoL** [comment]
It is active, yes.

**Comment by DragonzMaster** [comment]
Hope this help you @UbbeLoL 😉😉
[Search Files in CMD](http://stackoverflow.com/questions/8066679/how-to-do-a-simple-file-search-in-cmd)
*You can export results to txt file then add them to listbox 😁

**Comment by UbbeLoL** [comment]
Thanks @DragonzMaster but I don't think an external text file is the best solution here. :) I've already got a working search system just awaiting @luckystr1keno7 to discuss if there's anything else that needs to be added.

**Comment by luckystr1keno7** [comment]
Hey UbbeLoL,



Just sent you a message with my contact information. Happy Holidays Everyone !

**Comment by luckystr1keno7** [comment]
Hey guys,


Hope everyone likes the newly updated file manager. I invite everybody to start using it and post here all associated bugs, if any...Happy new year !

**Comment by luckystr1keno7** [comment]
Hi guys,





Soon the he File Manager will be getting most of the updates discussed in the File Manager suggestions, like Download/Upload Recursively, Download/Upload pause/resume , speed etc

https://github.com/quasar/QuasarRAT/issues/262

If you have other suggestions for the File Manager that are worth mentioning, please post them here and we'll see if they can be implemented

**Comment by MaxXor** [comment]
Please take discussions about further improvements to #262 and don't post them here.
