### ISSUE TITLE
Shutdown screen for profesional purposes

### ISSUE THREAD

**Issue by Axe-Usa** [quasar/QuasarRAT#575]
Hi, At fist i must to say this is a suggestion for good purposes not bad. For example i travel and i am using my computer of  my office where i work and sometimes i must to use fair. But some employee see what i do in my computer or access at my personal information. So i shut down the screen to avoid that other employees use my computer and avoid that they take my personal information. ( It's more like teamviewer ) i'm in my house and i want to use my computer of my office because i want to advance in my work obviously with approvation of my boss. And i want to other employees cant use my computer or can't see the things that i am doing. Thanks a lot for the project it's good alternative to teamviewer!

**Comment by ValonK** [comment]
```
        [DllImport("user32.dll")]
        private static extern int SendMessage(int hWnd, int hMsg, int wParam, int lParam);

        private void SetMonitorInState(MonitorState state) {
            SendMessage(0xFFFF, 0x112, 0xF170, (int)state);
        }

        public enum MonitorState {
            MonitorStateOn = -1,
            MonitorStateOff = 2,
            MonitorStateStandBy = 1
        }

```
That's what I use for shutting down my Monitors. Taken from http://stackoverflow.com/a/713504/2649087
