### ISSUE TITLE
Crypted connection

### ISSUE THREAD

**Issue by Lavarp** [quasar/QuasarRAT#576]
Hi ! 

I have look at other RAT source code and I find an interested function which crypt the server IP adress which is a good thing for safety. 

Will you add this kind of feature ? 

Thanks

**Comment by luckystr1keno7** [comment]
mmm....even if you do that,  I believe you can still trace the server ip by running it in a VM and tracing its connection to see where it points....if I am wrong that would be a nice addition indeed

**Comment by Galaden** [comment]
Hi, what rat u mean? All of them can be seen in Tcpview
