### ISSUE TITLE
Client connection proxy support

### ISSUE THREAD

**Issue by IPv777** [quasar/QuasarRAT#583]
Hello, can the Quasar clients run **under an HTTP proxy** ?

Thank you for your future replies.

**Comment by GuillaumeSX** [comment]
EDITED

**Comment by GuillaumeSX** [comment]
Up....pls

**Comment by matteke-games** [comment]
I'm fixing the tor proxy, might aswell add other proxies, you can follow the progress here: but its been a long time since @MaxXor did something so not sure if he's still here

**Comment by GuillaumeSX** [comment]
Okay thanks ;)

@MaxXor are you with us? :)
