### ISSUE TITLE
This version can run with .NET under 4.0? Like 3.5, 3.0.

### ISSUE THREAD

**Issue by hatienkma** [quasar/QuasarRAT#587]
I have a problem, how can i can run it with .NET 3.5 or 3.0?

**Comment by chico-depressive** [comment]
no, it requires .net 4.0, @UbbeLoL is working in a native version: https://github.com/UbbeLoL/Native-QuasarClient

**Comment by hatienkma** [comment]
Thank you. @chico-depressive
