### ISSUE TITLE
Keylogger Not Adding New Data After Restart for the same Date

### ISSUE THREAD

**Issue by seventhplug** [quasar/QuasarRAT#588]
Hi. I tested the Keylogger by typing "TEST 1" on chrome browser..  then i restarted the PC.. and checked if its connected to quasar client then  started chrome again and typed "TEST 2" and restart the PC again for the 3rd time and of course did the same thing start chrome and typed "TEST 3" and restarted the PC.. then i checked the Log Files only "TEST 1" is recorded.. the other inputs did not APPEND to the log files.. All test i made sure that the client and server are connected. Thanks

And also it stops logging for some time..

**Comment by virgiltu** [comment]
Yes I seen this also. It does not work. it will only create a file each day and then nothing gets added.
