### ISSUE TITLE
Gitter link

### ISSUE THREAD

**Issue by yankejustin** [quasar/QuasarRAT#591]
The group for Quasar on Gitter is no longer there so the link is now dead.

**Comment by MaxXor** [comment]
Yes, I've removed it. It was barely used.

**Comment by yankejustin** [comment]
Makes sense. Should probably remove it from the README too though. :)

**Comment by knackrack615** [comment]
We've created a Discord community for Quasar since the Gitter link was dead and plenty of people have joined already, @MaxXor it would be great if you could join

https://discordapp.com/invite/4vSJ372
