### ISSUE TITLE
Reverse proxy should increase the account password, which can enhance security! 

### ISSUE THREAD

**Issue by LiaoChangFei** [quasar/QuasarRAT#592]
Reverse proxy should increase the account password, which can enhance security!

**Comment by yankejustin** [comment]
What do you mean by this? Are you referring to the password length?

**Comment by LiaoChangFei** [comment]
[http://group.store.qq.com/qun/V149U9F30ExmQT/V3tkmLuG2Fh21iL9GQx/0](url)
Figure

**Comment by LiaoChangFei** [comment]
Connect to this SOCKS5 Proxy:127.0.0.1:3128(no user/pass)
Add an account password to verify the SOCKS connection, or SOCKS5 anyone can easily get. Very insecure!

**Comment by LiaoChangFei** [comment]
![Uploading 418(3RE$@3L6)}S[]]_{3}A.png…]()

**Comment by LiaoChangFei** [comment]
![418 3re 3l6 s _ 3 a](https://cloud.githubusercontent.com/assets/26694878/24443421/2609c046-1495-11e7-9eba-c4fd44085fd3.png)

**Comment by MaxXor** [comment]
This is not needed, the socks5 proxy server is only listening on localhost and thus not allowing connections from remote computers.
