### ISSUE TITLE
Reverse proxy proposal !

### ISSUE THREAD

**Issue by LiaoChangFei** [quasar/QuasarRAT#593]
Reverse proxy should increase the account password, which can enhance security!
Figure:

**Comment by LiaoChangFei** [comment]
![418 3re 3l6 s _ 3 a](https://cloud.githubusercontent.com/assets/26694878/24443828/c230bf32-1496-11e7-845c-a0ddcd2c5a0e.png)

**Comment by chico-depressive** [comment]
if connection with client is already estabilished with a password(AES crypted), why another pass for reverse proxy?

**Comment by MaxXor** [comment]
Duplicate of #592.
