### ISSUE TITLE
Malware & Antivirus Remove Buildclient.Exe on Another pc When Install.

### ISSUE THREAD

**Issue by Techvatsal** [quasar/QuasarRAT#596]
Hello.

When I build client and install generated .exe file on another PC then it is being deleted by antivirus (Malware) ? I don't know where exactly the problem is. Please guide me for proper way or solution.

Any help would be greatly appreciated.

**Comment by EnricoVogt** [comment]
Make a rule for your antivirus maybe

**Comment by zqguang3708** [comment]
Maybe it's a traditional issue

**Comment by LAzyFrAAnk** [comment]
Do FUD before deliver to your target.
