### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by pratik2pris** [quasar/QuasarRAT#597]
Hello

I hope you are doing well. I am very much impressed with this tool and want to expand this as per our requirement.

I have few questions regarding the license here

As per GPL License.

For example, if we distribute copies of this program, whether gratis or for a fee, we must pass on to the you the same freedoms that you received. We must make sure that you, too, receive or can get the source code. And we must show you these terms so you know their rights. this means that anything we change has to be publicly available.

with gpl3 anything i pay for has to be offered to the community. How do we fork this so that we can privately develop our own paths and features? Is there is a purchase source code option so that we may do so.

Summary I want to modify this as per our requirement and then we will publish to our partners and we want our own copyright option.

**Comment by Abdullah2993** [comment]
https://github.com/quasar/QuasarRAT/issues/499

**Comment by pratik2pris** [comment]
@Abdullah2993 Thanks for the information but we are not looking for this solution. We need to Purchase the source code and modify as per our requirement and distribute it. ( Do not want it to public )

@MaxXor as you are the owner let me know how can I reach to your for more discussion. Or could you update me with the solution please.

Looking forward for your response.

**Comment by Abdullah2993** [comment]
@pratik2pris its an open source project so let alone @MaxXor can't change the license. He has to get the consent from all the contributors...

**Comment by MaxXor** [comment]
@pratik2pris At the moment when you change the code of Quasar and want to sell it or just give it away for free you have to disclose the source code too. Not only for me, but for everyone. So you can privately develop it and then only publish the compiled software (binaries). To allow this non-public distribution I need to change the license. There is no purchase option for the source code.

@Abdullah2993 I consider changing the license to MIT to allow this.

**Comment by Abdullah2993** [comment]
@MaxXor that would be amazing

**Comment by pratik2pris** [comment]
@MaxXor so once you update to MIT license should I develop it privately ?

**Comment by Abdullah2993** [comment]
@pratik2pris sure. You can
