### ISSUE TITLE
Visual Studio and Dependencies

### ISSUE THREAD

**Issue by WebdesignRivolta** [quasar/QuasarRAT#602]
hello i have a question, i am also an c# programmer who wanted to open the solution in visual studio with the newest .net framework BUT it couldn't open without errors regarding dependencies for the whole code and forms. i also tested it with a downgrade to .NET 4.0 client profile, unfortunately without success.

best regards

angelo

**Comment by Abdullah2993** [comment]
Try to build it from the batch file in the solution.

**Comment by yankejustin** [comment]
You will have to build it using the .NET 4.0 (full version -- not the client profile). It can not be built only using the client profile version.

**Comment by MaxXor** [comment]
The client targets .NET Framework 4.0 Client Profile and the Server .NET Framework 4.0. Install at least Visual Studio 2010 to build it.
