### ISSUE TITLE
Other IP's someone an idea?

### ISSUE THREAD

**Issue by PrinzBel** [quasar/QuasarRAT#606]
Good evening,

I have a question, and I work again with Quasar etc, but whenever I am at the Quasar am working or researching dives any Ip Aderessen z.b (USA, Croatia etc on) has this a reason? Can this be dangerous to me? I ask for urgent advice.
 If someone can speak German, it would be even easier for me, because I usually have to translate over half, skype I have also the help resp. Answers would be really nice. have a nice evening

**Comment by yankejustin** [comment]
You can type it in German.

**Comment by PrinzBel** [comment]
You know vllt why that is

**Comment by ValonK** [comment]
Quasar is not for malicious use, it's to administrating remote Computers.
