### ISSUE TITLE
Best way to add clients

### ISSUE THREAD

**Issue by TheMime3** [quasar/QuasarRAT#608]
So i am just learning this and I was wondering was was the best spot to listen to and on what ports should i listen to. Thanks

**Comment by Wazup3005** [comment]
Oi boi do you even know what your doing lel

**Comment by Wazup3005** [comment]
Wat ya got to do m80 you got to build a client and run it on a computer  ya wanna control

**Comment by Wazup3005** [comment]
Also if your computer is not on ye local network then you have to set up port forwarding

**Comment by TheMime3** [comment]
... what?
And no i have no idea what i am doing

**Comment by Wazup3005** [comment]
Just watch a YouTube video or something on RATS and how to set it up
