### ISSUE TITLE
Is it able to bind  a tcp port?

### ISSUE THREAD

**Issue by Yousayiloveu** [quasar/QuasarRAT#609]
Does quasarRAT support bind  a tcp port and listen the income client to control ?

**Comment by EnricoVogt** [comment]
If, i understand your question right, then YES. Thats is what all reverse connection rats are doing:

Open a Socket, binding it on a specific port and listen for incomming Connection.

Please keep in mind: This is an issue-tracker and not a support-forum.


@MaxXor pls close.
