### ISSUE TITLE
Client, on build, being detected by Windows Defender as: Backdoor:Win32/Xiclog.A

### ISSUE THREAD

**Issue by seancroberts** [quasar/QuasarRAT#611]
I've been trying to remove features to find out where the offending code or API call is located, but no luck so far.
I've stripped out the recovery, key-logging, and webcam\video features and the output file form building Client.exe gets quarantined.

Anyone have any idea what I can do to STOP having Window Defender see this file as a threat?

**Comment by EnricoVogt** [comment]
Whitelist the client on windows defender

**Comment by seancroberts** [comment]
Thanks and yes, I know that adding client.exe to our firewall’s white-list will fix the problem, but I would still like to know which specific code or call is triggering Windows Defender.

Does anyone happen to know?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by EnricoVogt** [comment]
I think (not really sure) that Windows Defender has a Signature based detection. So you can try to Obfuscate the client build .. maybe its working. I dont know

**Comment by seancroberts** [comment]
I seem to have it working now without Windows Defender not seeing the client as a threat.

Most of the code that SEEMED to trigger that was located in and around ClientData – and functions related to the .exe copying itself to ProgramData and then using encryption

**Comment by AlienHack** [comment]
@seancroberts What's about other AV? Are they detect after you have modified that piece of code?

**Comment by seancroberts** [comment]
Once I got rid of the code that attempted to rename or hide the client.exe, Windows Defender (W10, 64-bit and W7, 32-bit) did not identify client.exe as malware nor did it try to quarantine the file.

I intend to use parts of the Quasar RAT code as a part of my legitimate domain support responsibilities, so there is no need to hide or rename client.exe.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by santoshcxs** [comment]
Please let us know the code changes you have done, for Windows Defender not seeing the client as a threat.

**Comment by Clevelus** [comment]
It is necessary to refine the mechanism of hiding the process. It is useless if any modern antivirus immediately detects it.
Also, you need to add a setting that allows you to disable this mechanism, since it is not needed by some users.

**Comment by seancroberts** [comment]
"It is necessary to refine the ways of hiding the process," writes Clevelus...
I am not interested in hiding the process - my intended use for parts of Quasar RAT are for my legitimate work-related admin responsibilities.
I find no value in being able to get passwords from browser settings, turn on web cams without alerting users, logging keys, nor hiding the process I'm trying to run.
I find incredible value in being able to see and manipulate a remote desktop and I find value in being able to access a computer's command console remotely.
The rest of what I need I can already do - run remote programs, silently or interactively, as local system or as the logged on user by installing a remote service, allowing it to interact with the desktop and then doing a little session\handle\API magic.
I have a remote registry editor that has full remote registry visibility through WMI, and it's also through WMI that I can report on just about anything on a computer system... all agent-less\client-less.
At the moment I am trying to see if I can implement remote desktop functionality using the same service I use to execute remote programs, but if I have to, I'll install the service and have it run a client temporarily.
So far, the one function I want but can't implement without a client is the remote command-console.
If anyone wants to work with me on any of this, please let me know because I would love to collaborate.

**Comment by sndcode** [comment]
@seancroberts 
what EXACTLY did you do to make the client compiling with windows defender ON ?

**Comment by seancroberts** [comment]
I rem’d-out or removed all code having to do with the client renaming itself or trying to hide its executable.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by matteke-games** [comment]
"remote command-console" What do you mean by this?

Also note that you can hide it from scans, but using any anti virus that checks behaviour. Like G-Data, bitdefender etc. It WILL be blocked since it probably installs? Into windows dir? And it makes a network connection, that will trigger any av with behaviour checks

**Comment by mkramer74** [comment]
@seancroberts - Is it possible to get your sources ?

Regards,
michael

**Comment by Rottweiler** [comment]
After obfuscating everything but the names in the assembly I think I can safely assume it’s the assembly names

**Comment by MaxXor** [comment]
Whitelist the file.
