### ISSUE TITLE
Where are stored the logs of the Keylogger?

### ISSUE THREAD

**Issue by whakru** [quasar/QuasarRAT#616]
Where are stored the logs of the Keylogger?
They have accumulated too much and I want to clear

**Comment by John-Constantine** [comment]
if you are asking about the keylogger logs , i think they are stored inside the Clients Folder which is located in the same path as of the Quasar Executable . 

"Quasar Exe Path"-->Clients-->ClientMachineName->Logs ((Each client log is stored in a separate folder named after client) )

**Comment by whakru** [comment]
no, I need to know the location of the client

**Comment by MaxXor** [comment]
The keylogger logs are stored at: `%APPDATA%\Logs`. Be aware the Logs directory could be renamed, this setting is editable.
