### ISSUE TITLE
Password recovery not working

### ISSUE THREAD

**Issue by FitnessRS** [quasar/QuasarRAT#617]
I was testing the rat and i came across that the password recovery wouldn't be able to get my passwords from chrome.. Here is a screenshot https://gyazo.com/be44f2521505737871c05836f91091bb

It doesn't show any details just blank.
Anyone know how i can fix this?

**Comment by sndcode** [comment]
youd have to reverse the browsers again for changes and update the code for the browser classes.

**Comment by matteke-games** [comment]
It's working fine, there is however 1 olddated thing I noticed in firefox to get the install path. But the problem is that it cannot get passwords from 64bit browsers since quasar is 32bit on its own, a 32bit process cannot load a 64bit dll

**Comment by MaxXor** [comment]
There are already multiple open password recovery issues, for example https://github.com/quasar/QuasarRAT/issues/589. It's up to someone else to fix the password recovery module.
