### ISSUE TITLE
Methods renaming

### ISSUE THREAD

**Issue by EhsanArio** [quasar/QuasarRAT#619]
Hi
I want to extend renamer.cs and rename all methods.
But may be there is some methods which renamed, client may crash or doesnt work correctly
Which methods MUST not be renamed ?

**Comment by matteke-games** [comment]
You can rename every method. Just be sure to rename all the references too

**Comment by yankejustin** [comment]
It doesn't matter if you change the method names. You would only experience issues if you began to restructure the code (changing the namespace of certain classes mainly).

**Comment by EhsanArio** [comment]
Yes 
But i want to obfuscate the code with some obfuscators like .Net Reactor.

Its is needed NOT ot obfuscate some parts of code because if obfuscate all Client doesnt work.

```
            if (typeDef.Namespace.Contains("NetSerializer") 
                || typeDef.Namespace.Contains("Registry") || typeDef.HasInterfaces)
                return;
```

Based on this only NetSerializer and Registry and typeDef.HasInterfaces can not be obfuscated.

Is it true ?

**Comment by MaxXor** [comment]
@EhsanArio Yes, classes from NetSerializer & Registry namespace and classes with interfaces can not be renamed. It does have no negative side effects.
