### ISSUE TITLE
Java based client

### ISSUE THREAD

**Issue by EhsanArio** [quasar/QuasarRAT#620]
Hi
I wanna write a java based client for Quasar Server.

Is there available some where ?

What is authentication process for client ?

**Comment by MaxXor** [comment]
You need to consider a few things to build your own client:
- AES in CBC mode
- QuickLZ lib
- Serialization

The outer layer of a packet which is sent over the wire looks like this:
https://github.com/quasar/QuasarRAT/blob/15b01116bf87a49742d4e6d65652d37fd34641cb/Client/Core/Cryptography/AES.cs#L47-L52

Once decrypted you need to decompress it with QuickLZ and the last step is deserialization which could be a little tricky as Quasar is using a non-standardized .NET library called [NetSerializer](https://github.com/tomba/netserializer).

When u got all this done, you are ready to build your own packets. Some basic authentication packet looks like this: https://github.com/quasar/QuasarRAT/blob/master/Client/Core/Packets/ClientPackets/GetAuthenticationResponse.cs


FYI: [UbbeLol coded a client in C++](https://github.com/ubbelol/Native-QuasarClient)
Maybe it can help you to get an overview about the basic functionality needed.

**Comment by EhsanArio** [comment]
Thanks
