### ISSUE TITLE
Set a fixed local Port on the client

### ISSUE THREAD

**Issue by Gyzzorn** [quasar/QuasarRAT#621]
I have seen that the client will cycle through a list of ports attempting to connect to the server with each - so far I have not been able to set this to a fixed port that I intend to use for testing. Anyone able to advise?

**Comment by yankejustin** [comment]
This was mentioned in the old Quasar chat room that we had -- does anyone remember?

**Comment by MaxXor** [comment]
I'm not sure if I understand your question correctly, but when you only enter one host:port combination, the client will always try to connect to this and not cycle through others.
https://github.com/quasar/QuasarRAT/blob/15b01116bf87a49742d4e6d65652d37fd34641cb/Client/Config/Settings.cs#L14

Or do you mean the local tcp client port? This is being decided by the system ([see here](https://stackoverflow.com/questions/5435779/is-the-port-used-by-a-tcp-client-to-connect-to-a-server-unavailable-for-other-tc)) and I'm not sure why you would like to stick with one port there.

**Comment by Gyzzorn** [comment]
It was mostly for testing purpose to test around outgoing firewall issues but that is fine thanks.
