### ISSUE TITLE
Can't remove the logs from the client! help

### ISSUE THREAD

**Issue by whakru** [quasar/QuasarRAT#625]
How to delete logs of the client? That is the client,not me.. the customer has accumulated a lot of logs that starts to fail.. to Find I can't searched the Logs folder and in my case (Logss) Here is a screenshot of the settings..
in C:\Program Files (x86)\windirs\ the client is also empty there is no logs folder...

![image](https://user-images.githubusercontent.com/22603145/31577227-5ecf95ac-b113-11e7-8c59-dda91883e6b4.png)
![image](https://user-images.githubusercontent.com/22603145/31577249-a50d8722-b113-11e7-9a2c-d42b49041aca.png)

**Comment by MaxXor** [comment]
Sorry for the trouble, the log directory is located at `%APPDATA%\Logs`
