### ISSUE TITLE
How to setup Quasar on windows

### ISSUE THREAD

**Issue by MichaelOK1** [quasar/QuasarRAT#627]
I’m sorry but I’m new to working with rat, from tutorial videos I’ve run into online after extracting the contents of the quasar zipped folder there’s a bin folder, but I can’t find any my download folder from the quasar repo.. pls I don’t know what I’m doing wrong, can someone help me ?

**Comment by MaxXor** [comment]
This issue tracker is only for technical issues with the software.
Latest release can be found here: https://github.com/quasar/QuasarRAT/releases/tag/v1.3.0.0
