### ISSUE TITLE
Add Stress Sock Flood

### ISSUE THREAD

**Issue by facescorpion** [quasar/QuasarRAT#633]
Hey guys,

I'm wondering if would be a new version of our Beautiful QuasarRat and that we need is
HTTP Flood
UDP Flood
TCP Flood

**Comment by trollmad3** [comment]
This would not be allowed because the creator of QuasarRAT wants ethical use not un-ethical use.

**Comment by MaxXor** [comment]
@trollmad3 Exactly, thanks.
