### ISSUE TITLE
Client not connecting

### ISSUE THREAD

**Issue by jennamarble** [quasar/QuasarRAT#634]
the rat simply won't show connection i tried on myself i checked everything works correctly on darkcomet and its detecting connection fine but not this why?

**Comment by cyclo-techtwister** [comment]
Same issue here. I have used this tool on a number of occasions last year but, now no matter if I use the update version or a older one it does not connect (loop back testing). Of course I have all dependencies needed and no firewall or AV is interfering with its function.  Other older stable R.A.T.S work fine. Anyone have any ideals?

**Comment by someonelikeme** [comment]
i have the some issue. Even with v1.3 was working so well. then about a week ago it stopped itself suddenly.

**Comment by MaxXor** [comment]
Quasar does indeed work with `localhost` and other valid hostnames or IP addresses. Often it's a firewall problem not forwarding the ports correctly. Please check your firewall configuration.
