### ISSUE TITLE
185.194.141.58:80, why?

### ISSUE THREAD

**Issue by wikijm** [quasar/QuasarRAT#637]
Every time I start a client, I've got a TCP connection on 185.194.141.58:80.

Is it possible to get an explaination about it?

**Comment by Abdullah2993** [comment]
geo location api

**Comment by wikijm** [comment]
Thanks for the quick answer.

I don't understand why the client do this.
Won't it be better to do that job by the server?
I'm worried about the fact that this way the GeoLoc API owner may know easily all my clients public IP adresses.

**Comment by MaxXor** [comment]
The initial thought I had when implementing this on the client was to reduce the load on the server.

**Comment by wikijm** [comment]
Thanks for your answer and the explaination.
I'will close this issue thanks to your answers.

Have a nice day 😃
