### ISSUE TITLE
Neither Builds are Creating an Executable

### ISSUE THREAD

**Issue by TheEnchantedCow** [quasar/QuasarRAT#639]
On two different systems with administrative privileges, I ran both build batch files getting an error shown below. I am not able to get an executable out of the batch file.

![image](https://user-images.githubusercontent.com/23041791/34584411-473831f4-f161-11e7-8a98-047fe9d5e810.png)

I checked the bin folder and this is all I found.

![image](https://user-images.githubusercontent.com/23041791/34584476-818be4e0-f161-11e7-96e4-aee888d63514.png)

I ran these as an administrator as my account on the windows device is one. Any fixes? This tool looks really cool, and I'd like to try it out.

**Comment by yankejustin** [comment]
Your antivirus is removing the built executable. Due to the tools included, antiviruses tend to get very angry.

**Comment by TheEnchantedCow** [comment]
Oh yeah, you're right. Thank you for your time and help!
