### ISSUE TITLE
No .bin Folder created.

### ISSUE THREAD

**Issue by Zyercas** [quasar/QuasarRAT#640]
- Hey. I downloaded the .zip Folder, and extracted that. I runned build-release, (Antivirus off) but no bin folder was created. I'm on Windows 10. 
# #
#
# 
###     
# 
## 
It is  
italian, it means: The configuration of solution specified: Release|CMD isn't valid. Please specify one configuration Using the properties Configuration and Platforms ( for exemple MSBuild.exe, Solution.sln, /p:Configuration=debug /p:Platform="Any CPU" or do not specify any Property and Use the standard Configuration.  [C:\Users\MyName\Downloads\QuasarRat-Masters\QuasarRat.slnj

**Comment by cyclo-techtwister** [comment]
Are you using Visual Studio 2015?

**Comment by Zyercas** [comment]
Nope, i unistalled it 2 moths ago. I didnt use the GitHub Program to download this, btw.

**Comment by cyclo-techtwister** [comment]
OK, I may be wrong but, I have Visual Studio 2015 installed and that is what I use (cause I make personal changes). However I tried running the build-release bat and all worked fine ,it built the exe's with no issues. 
Maybe you must have Visual Studio 2015 installed? Try installing it rerun build-release bat and let us know.. I hope this was helpful..

**Comment by Zyercas** [comment]
Ok, i'll try and i will update you 'bout the situation. Thanks for the support!

**Comment by Zyercas** [comment]
Ok, i'll try and i will update you 'bout the situation. Thanks for the support!

**Comment by Zyercas** [comment]
Uhm, Visual Studio 2017 is fine? And what addons should i install? (.vb,C++,C#...)

**Comment by Zyercas** [comment]
Uhm, nope, it doesn't work... Could you gave me the folder alredy the .exe builded?

**Comment by Zyercas** [comment]
Soo. Wait. I think i know what's going on..

**Comment by Zyercas** [comment]
http://prntscr.com/i32snd I'm installing Visual Studio. This is the right version, right?

**Comment by Zyercas** [comment]
Nope, i've installed Visual Studio 2015 but nothing.

**Comment by cyclo-techtwister** [comment]
So, you still can't build even using Visual Studio 2015 GUI software itself?

**Comment by cyclo-techtwister** [comment]
Have you opened the project in Visual Studio 2015 and did you get any errors?

**Comment by Zyercas** [comment]
I didnt build using Visual Studio. At first i tried running the .bat when Visual studio was installed, then i just opened the project but didnt do anything far then that.

**Comment by Zyercas** [comment]
I didnt build using Visual Studio. At first i tried running the .bat when Visual studio was installed, then i just opened the project but didnt do anything far then that.

**Comment by Zyercas** [comment]
How could build the client with Visual Studio?

**Comment by cyclo-techtwister** [comment]
I just double click the projects .sin file it opens Visual Studio by default. I then simple go to the solutions properties and under Configuration Properties I change Configuration to Release if set to Debug as it will not run after compiling if so.

**Comment by Zyercas** [comment]
I will try. And i'll update you as usual.

**Comment by Zyercas** [comment]
Ok, it creates a bin folder > Debug > then it is just empty

**Comment by Zyercas** [comment]
Yeah, now ti creates a Bin folder with the name release, but just empty too. I'll try turn off AV.

**Comment by cyclo-techtwister** [comment]
You're welcome...
