### ISSUE TITLE
Report A Bug About RemoteWebcam 

### ISSUE THREAD

**Issue by hucya** [quasar/QuasarRAT#642]
When I use the remote camera, throw  a Exception, The remote will automatically disconnect, Debugging **FrmRemoteWebcam.cs file** **_UpdateImage_** function exception, as follows:

**Source code：**

            public void UpdateImage(Bitmap bmp, bool cloneBitmap = false)
            {
                    picWebcam.Image = new Bitmap(bmp, picWebcam.Width, picWebcam.Height);
            }

**Change the code：**

            public void UpdateImage(Bitmap bmp, bool cloneBitmap = false)
            {
                picWebcam.Invoke((MethodInvoker)delegate
                {
                    picWebcam.Image = new Bitmap(bmp, picWebcam.Width, picWebcam.Height);
                });
            }

**Comment by MaxXor** [comment]
Thanks, please create a pull request and submit these changes.
