### ISSUE TITLE
Why the generated program does not correspond to the size of "bin"

### ISSUE THREAD

**Issue by 1zhanglingji** [quasar/QuasarRAT#647]
emmmmm
I stumbled upon a problem

I try to locate the feature code, but the final program will be detected by the antivirus software

So I want the generation program to be generated completely according to bin

I don't understand English and I do not understand the use of C# QWQ

I come from China and hope you can reply to this question

(our country is harms by the back door so hope not to have a back door =3= thank you)

**Comment by 1zhanglingji** [comment]
咳

**Comment by ViCrack** [comment]
其实我都看不太懂你说的是啥。
这种RAT工具本来就很容易被AntiVirus所杀，bin是用来辅助增加配置信息的，不可能生成之后完全一模一样，
还有这跟来自哪里没关系，就算不懂C#你也可以尝试抓包等来判断有无后门（何况人家都开源了）。

**Comment by MaxXor** [comment]
The names of numerous fields, methods and classes are being obfuscated when generating the client.
Check here phase 2 of the build process: https://github.com/quasar/QuasarRAT/blob/master/Server/Core/Build/ClientBuilder.cs#L122

Anyways, no discussion of making Quasar undetected by AV. Add an exception to your AV.
