### ISSUE TITLE
Any Client Get Connected

### ISSUE THREAD

**Issue by PentesterMalwareAnalizsing** [quasar/QuasarRAT#648]
I dont Know What is happening , I tried but it doesnt work I mean, anytime I create the payload, didnt connect back to server,   iven when I have the same ports , password Didnt Work I dont know why, why this could happen , I thinking that maybe could be an error on the instalaion , Im ussing windows 8.1.

here are some screen shots 
![image](https://user-images.githubusercontent.com/18033928/36772447-5dbfcd32-1c23-11e8-9d90-beb0a21dd36e.png)

Anyone could tellme What am i doing weong, I have some knowledge about this , I allowed the port on the firewall , I used a basic create payload from the build ooption, but why it is not working, By the way Im using on vmware machine windows 8.1  ty guys...

**Comment by Zolocofxp** [comment]
Server side seems to be working as expected. If I understood correctly, you are running the client on a virtual machine in the same PC. I would suggest to make sure you can reach the port by executing a "tcping" or "telnet" to port 2991. If you don't get a port open message, it might be a firewall issue.

**Comment by OmarCuadrado** [comment]
Ty @Zolocofxp  for your comment I understand What you say , But I think Thats is not the case I mean the machine where I am running the virus dont have any firewalls up, neither the infected machines , which means that isnt a restricction troubles , any ideas , what could happen? I really dont know what is happening TY

**Comment by Zolocofxp** [comment]
Here is what you should check in my opinion...
- Check that listening port matches Quasar(Process ID):
![1](https://user-images.githubusercontent.com/34036756/36820007-700faeb0-1cb1-11e8-983f-ee9a7924355e.JPG)
![2](https://user-images.githubusercontent.com/34036756/36819983-4a9a95be-1cb1-11e8-8e25-c1f7787958f0.JPG)
![3](https://user-images.githubusercontent.com/34036756/36819992-5cd1ba78-1cb1-11e8-8332-6aeb609615b8.JPG)

- If it seems ok, check for communication on the client host by probing the port. You must see the port open.
**NOT OK**
![5](https://user-images.githubusercontent.com/34036756/36820058-ace9dbc6-1cb1-11e8-8dc7-c792264bc403.JPG)
**OK**
![6](https://user-images.githubusercontent.com/34036756/36820080-ca44ca64-1cb1-11e8-9cf2-33d86d456775.JPG)

-If communication between client and server is ok, then is down to the built client. Make sure is was built right. This is what I use and works:
![4](https://user-images.githubusercontent.com/34036756/36820195-4a4b3a86-1cb2-11e8-9b78-7ca98a54f76a.JPG)
![7](https://user-images.githubusercontent.com/34036756/36820327-e93a0492-1cb2-11e8-9d65-3555ec00fbcc.JPG)

Hope you can get it working.

**Comment by OmarCuadrado** [comment]
@Zolocofxp  ty bro already working your awesome

![image](https://user-images.githubusercontent.com/18033928/36856993-6121f7d4-1d45-11e8-86b6-1b4814f8af4c.png)

its funny the problem was, I didnt have access to internet due to a DNS problem, i wasnt realise that i was using a vpn, ty so much :D 👍

**Comment by Ral721chanel** [comment]
The same thing happens to me and I can't solve the problem

**Comment by ko3nd3drumm3r** [comment]
> The same thing happens to me and I can't solve the problem

make sure you are using the ip4 ip adress

**Comment by mypetcheetah** [comment]
soo for me the client isnt connecting even though i opened the port on my router, when i use localhost it works but i need it to acces my game pc from school soo i need to use my public ip.

anyone got ideas, anything would help!
