### ISSUE TITLE
Fully UnDetectable(FUD), is it possible?

### ISSUE THREAD

**Issue by PentesterMalwareAnalizsing** [quasar/QuasarRAT#649]
I was thinking that the implementation of a C&C  its hard, but since the payload (cliente.exe) is detected by 25/32 anti-malware stuffs, I was wondering if is there a way to access to the source code of the payload? I mean can  i access to the payloads' code? the one that is generated from the building tap? I would like to know how all of this works, Im a programmer and i am trygin to get deeper in this about malware develomenpt and C&C architecture is really interesting , any idea I would be really glad to hear up could be the code or a way to make this payload guy FUD,, ty 
👍

**Comment by Abdullah2993** [comment]
The code is in the repo

**Comment by MaxXor** [comment]
No discussion of making Quasar FUD. For legit usage you can just add an exception to your AV.
