### ISSUE TITLE
Edit payload to be FUD

### ISSUE THREAD

**Issue by wilburforce666** [quasar/QuasarRAT#654]
Security analyst. What exactly must you change in the source to perhaps stop AV's from triggering it

**Comment by BackfireRAT** [comment]
1) Signatures
2) Use runtime encryption and decryption
3) Don' scan on virustotal
4) Polymorphic (Hard to achieve)
5) Stop trying if you are using the program to infect people

You could also use rootkit like functions to prevent it from being scanned

**Comment by MaxXor** [comment]
See #649.
