### ISSUE TITLE
QuasarRat non rileva pc

### ISSUE THREAD

**Issue by tommasodep** [quasar/QuasarRAT#655]
ciao a tutti, ho seguito molte guide su come far funzionare  QuasarRat ma con nessuna sono riuscito a arrivare ad un buon risultato. quando creo il file exe e lo apro dal mio portatile QuasarRat non ro rileva.   ho provato a vedere se la porta che stavo controllando era attiva ma non lo è. non so come fare. grazie in anticipo per le risposte

**Comment by 9-11insidejoke** [comment]
Ciao. Questo tutorial dovrebbe aiutarti a configurare QuasarRAT molto facilmente. Fammi sapere se ti aiuta.

https://m.youtube.com/watch?v=gQM-dxDrBbI

**Comment by tommasodep** [comment]
grazie mille per il link. purtroppo però ho visto molti tutorial così  e anche seguendo passo passo questo non sono riuscito a far funzionare l' exe.
 quando lo apro sul pc da dove l'ho creato e da dove ho aperto quasar funziona, ma quando provo ad aprirlo su un altro computer quasar non lo rileva. cosa posso fare?

**Comment by tommasodep** [comment]
ho trovato il problema... avevo tutte le porte di rete chiuse, non so come sia possibile ma sono riuscito a risolvere. avrei un altra domanda, come  faccio a rendere invisibile l' exe agli antivirus? ho già provveduto a bindare il file ma non saprei come renderlo invisibile, credo criptandolo? grazie mille

**Comment by tommasodep** [comment]
PROBLEMA: vi spiego: premetto che non ho condiviso con nessuno il file exe: ero a cena, e avevo  lasciato aperto quasarrat, quando sono tornato ho visto prima 3 connessioni dalla russia, di istinto sono andato su sicurezza e webcam ma niente allora ho provato con il desktop  e sono riuscito a vedere questo che aveva xp e dei file .ini .dll ee altra roba sul pc. poi ho visto altre 2 connessioni  e subito dopo si sono disconnessi..... cosa può essere stato? cosa devo fare? purtroppo non ho visto l' ip e so solo  che vengono dalla russia. da cosa può essere stato causato? pls help

**Comment by tommasodep** [comment]
ora altre  connessioni... aiutoooo


![senza nome](https://user-images.githubusercontent.com/38185539/38518779-3106b784-3c3e-11e8-98a1-87d724073a1c.png)

**Comment by tommasodep** [comment]
Potrebbe essere stato diffuso da siti di rilevamento virus online?

**Comment by 9-11insidejoke** [comment]
È molto strano che tu abbia avuto delle connessioni. Sì, è probabile perché le persone hanno scaricato per errore il file che hai scansionato online. Per far sì che il tuo RAT non sia rilevabile dagli anti-virus, devi "criptare" il tuo RAT. Non sono sicuro di come farlo ma ci sono molti tutorial su Youtube su come farlo.

**Comment by tommasodep** [comment]
Grazie mille

**Comment by MaxXor** [comment]
Please use english language for discussion here.
