### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by willyy12345** [quasar/QuasarRAT#662]
program based on your code sold by breaking your licenses

https://secretlogger.pl/

demo video on this website https://www.youtube.com/watch?v=5eTa7Gz7m5Q

forum for this program called secretlogger: https://haker.com.pl/threads/32112-Secretlogger-Stealth-1-3-0-Zdalna-Administracja-Komputerem

i have secretlogger downloaded from https://secretlogger.pl/ but today the file has been removed for known reason :)

**Comment by Galaden** [comment]
hm, what new you added to the ctrl+v project? name+icon and sell for 220$/y
shame

**Comment by MaxXor** [comment]
Thanks for informing me. Actually selling a modified version of Quasar is allowed in the MIT-license as long as you include the original license and copyright notice. And if I had to guess, it's probably not included. I'll try to get in touch with the author to get this resolved.

**Comment by willyy12345** [comment]
autor of secretlogger not include original license and copyright notice, if you want i will send you program called secretlogger downloaded from website secretlogger.pl, yestaerday when i wrote to autor secretlogger about MIT license, autor of secretlogger removed file from website, but he still selling it on forum haker.com.pl

**Comment by willyy12345** [comment]
this morning autor of secretlogger wrote on forum haker.com.pl about new version secretlogger 1.4.0 :D i think he change the code and license notice but i'm not sure

**Comment by willyy12345** [comment]
autor of secretlogger is na administrotar of this forum, change and modify users comments for advertising, shame
