### ISSUE TITLE
client code available as a library?

### ISSUE THREAD

**Issue by sadnub** [quasar/QuasarRAT#663]
Hello!
I am wondering if anyone has implemented the client code as a library? With all of the GUI code removed? If it is targeting .NET Core that would be a plus to!

Otherwise I can probably do this my hand, but just wanted to check if it had been done already.

Josh

**Comment by Floraly** [comment]
Are you serious?

**Comment by sadnub** [comment]
Yeah I am serious. I just started from scratch and did what I needed to do. I just needed an agent that runs as a service with no front end.
