### ISSUE TITLE
Random Client Connections

### ISSUE THREAD

**Issue by piqle** [quasar/QuasarRAT#664]
I haven't shared the client .exe any wheres, but somehow am having random computers connect. How is this possible? I've set an encryption key, and the only client is hosted locally.

**Comment by MaxXor** [comment]
This probably means you are using the default encryption key. Please chose a different one and additionally use a different port. There are bots out in the wild who scan the web for the default Quasar port and try to connect with the default encryption key.

**Comment by Antwns** [comment]
Why are bots doing that?
