### ISSUE TITLE
whats the different between build the client from visual studio and build it from the client builder 

### ISSUE THREAD

**Issue by jokerxbt** [quasar/QuasarRAT#665]

**Comment by jokerxbt** [comment]
![image](https://user-images.githubusercontent.com/36801065/40865677-35a468ac-6602-11e8-89c2-2a28591c4227.png)

and i want to know what is the key and what is the auth key and should i encrypt them in base64 before put them there ?

**Comment by jokerxbt** [comment]
and why (if #debug)?

**Comment by MaxXor** [comment]
When you compile with debug configuration the settings between `#if DEBUG` and `#else` are used. These are already working settings. If you look into the settings after the `#else` these are mostly empty and do not work out of the box. A client needs to be built first from the server builder when using the release configuration. When using the debug configuration you can just run the client and it will connect to the server on localhost.
The reason for this was to make debugging quicker without having to build a client again from the server first.
