### ISSUE TITLE
 how remove install propriety from the client ?

### ISSUE THREAD

**Issue by jokerxbt** [quasar/QuasarRAT#666]
i tried many times but the client crashed every time i try to do that

**Comment by jokerxbt** [comment]
and i want to remove other prop rites from the client but i can't

**Comment by jokerxbt** [comment]
and i want to remove other things (proprietors )from the client but i can't

**Comment by MaxXor** [comment]
Remove this and all places where this variable is referenced: https://github.com/quasar/QuasarRAT/blob/master/Client/Config/Settings.cs#L48
You also need to adjust this: https://github.com/quasar/QuasarRAT/blob/master/Server/Core/Build/ClientBuilder.cs#L87
