### ISSUE TITLE
AV Detection

### ISSUE THREAD

**Issue by DJTiqer** [quasar/QuasarRAT#670]
I work in an IT department of a small business.

I find it annoying that this is detected by our AV, because it means extra config time to get it deployed to our employees.

We need to keep track of what they do at work, to prevent workplace mischief.

**Comment by Floraly** [comment]
Dude Virus Scanner is not a problem!

You can run an encrypted payload like QRat and you can Execute it from memory Invoke might help you to find it but you can replace Invoke with your own C++ or ASM loader to place your payload on systems without triggering any Security Traps.

But keep in mind doing this will defently an security breech in your company!

So do not do this!!!

**Comment by yankejustin** [comment]
From a business standpoint, usage of this application can open up some security issues if not configured properly. I think it makes sense to require manual configuration- no secure business computer should be able to run a RAT on it without some configuration, or I would definitely question the security side of that IT department.
