### ISSUE TITLE
@MaxXor Where are you? 

### ISSUE THREAD

**Issue by XYDsoft** [quasar/QuasarRAT#671]
@MaxXor 
QuasarRAT  has not been updated for 2 years ,
There's a lot of Issues&Pull requests .
There's a lot of good a Pull requests .
Everyone wants you to update the next version !
A lot of people's hopes are on you ,
Please don't abandon us !

**Comment by yankejustin** [comment]
It is hard to support such a big project without monetary support. There just aren't enough developers that have the free time to implement new features or bug fixes.

**Comment by TomasHubelbauer** [comment]
Perhaps extending the options of donation to include Patreon and/or OpenCollective would convert some of these people who want @MaxXor to update the next version and put their hopes on him to paid supporters. Worth a shot? :-)

**Comment by MaxXor** [comment]
It's been a tough time for me, but I've got plans for Quasar and gonna remove features which can be abused easily like the Password Recovery or Keylogger. With this project I'd like to move the focus more to the general remote administration tasks and also tasks like supporting the users via remote desktop/chat. If you don't agree with this, you are free to fork the project. Basically I really like that Quasar is used by admins in small businesses (some contacted me and thanked me for the work, there is no telemetry in Quasar).

I will publish a roadmap for Quasar within a few days so everyone can check if this project is still going the same direction as they think.

@TomasHubelbauer Thanks, will check it out.

**Comment by yankejustin** [comment]
@TomasHubelbauer I like that idea. I would absolutely make modifications or new features if I could make a little bit out of it.

**Comment by maddinthegreat** [comment]
Hi,

i have enhanced the RDP logic. My version supports icon overlay and cursors of client machine. I also doubled the framerates.
There is also an issue with blocking SQLite-DB in the password reader code when the DB is in use, which can be fixed easily. I have also a fix for newer Firefox passwords. Current code doesn't work for new Firefox passwords.

Generally it would be better to exchange the SQLite class with the original SQLite.NET assembly. You may embed the .NET assembly and load it from resource stream. The native part you embed also and extract before the managed part will be loaded, Compress the native part of SQLite with UPX.
**The built SQLite is hell of shit**

Drop me a line.

Regards
Martin

**Comment by XYDsoft** [comment]
@maddinthegreat Please submit it to “ Pull requests”, @MaxXor The next version should be released soon , Countless people are looking forward to it !

**Comment by TomasHubelbauer** [comment]
@XYDsoft please be respectful or the maintainers time. It's clear that there is real demand for a new release, you yourself have reinforced that by starting this message thread, but we're talking about free software developed in the maintainers spare time (most likely), without funding (most certainly) and as such it should remain without a deadline, anything more is an unfair ask, I hope you understand.

**Comment by XYDsoft** [comment]
@TomasHubelbauer I also want to do my best to sponsor this project, but I can't find a way. The author did not leave the sponsorship information .

**Comment by MaxXor** [comment]
Here we go: https://github.com/quasar/QuasarRAT/blob/master/ROADMAP.md

Sorry for the delay.
