### ISSUE TITLE
Quasar I dont have any client files and i can't build

### ISSUE THREAD

**Issue by chegglychegg** [quasar/QuasarRAT#672]
I have set up everything fine, but I can't build because I don't have client.bin or any client files 
![screenshot_10](https://user-images.githubusercontent.com/40368652/41556081-02350fca-737d-11e8-95e5-e2e92be6b424.jpg)
![screenshot_11](https://user-images.githubusercontent.com/40368652/41556082-026aa34c-737d-11e8-96df-68b6446d557d.jpg)

**Comment by MaxXor** [comment]
https://github.com/quasar/QuasarRAT#building-a-client

Build with release configuration.

**Comment by yankejustin** [comment]
Be sure to check the closed issues since this has been asked quite a few times.

Have you checked your [antivirus](https://github.com/quasar/QuasarRAT/issues/552)?

**Comment by ISBaloch** [comment]
Even my all anti virus are disabled but still not found client.cin

**Comment by cutff** [comment]
Hi There! have you solved the problem as i have faced the same issue here! thank you.

**Comment by MaxXor** [comment]
Windows has an own antivirus software included called Windows Defender, be sure to add an exception for Quasar. Then build the project as usual.

**Comment by EitamShalom** [comment]
hi... i still got this issue client.bin could not be licated it should bein the same folder as quasar
