### ISSUE TITLE
Keylogger files on Client

### ISSUE THREAD

**Issue by kosta14** [quasar/QuasarRAT#673]
Hello
Why the keylogger files on the client looks liek this ? 	3sØ›j_uÇZÑ¦%Í„jD?3}AÂ­p
can i convert this or make this file readable for me ?

**Comment by yankejustin** [comment]
Not all languages are supported. Similar issue with remote shell.
________________________________

**Comment by MaxXor** [comment]
@yankejustin That's not the problem.
@kosta14 The log files on the client are stored encrypted. :)
