### ISSUE TITLE
A kitchen knife can be used to cut vegetables and can be used to kill people. 

### ISSUE THREAD

**Issue by XYDsoft** [quasar/QuasarRAT#675]
A kitchen knife can be used to cut vegetables and can be used to kill people. 
Hope to retain some of the necessary functions.

**Comment by MaxXor** [comment]
Most of the functionality will stay. Currently the plan is to remove just the password recovery. Also check the last item on the roadmap. The user will have the ability to check the status if a certain feature is active.
