### ISSUE TITLE
Illegal sale

### ISSUE THREAD

**Issue by capcrack** [quasar/QuasarRAT#677]
In this video, https://www.youtube.com/watch?v=0LifmKBpqCM, is shown your software with few modifications (design, language, few new features). This guy, "Mr. Alex", sells it as private software written by him self, without any license ("about" option is also removed) or link to the real author or source code.
Place where he sells this ware is: https://mr-alex.be/ (register is needed)
If you need sample of "his" software, i can send you one (old version).

**Comment by H4xl0r** [comment]
pls send old version to thebossis@safe-mail.net

**Comment by trollmad3** [comment]
This should be taken seriously and its not.

**Comment by MaxXor** [comment]
@trollmad3 The license of Quasar helps me only in a lawsuit to win that. But that's not worth it for me. The only thing I can do right now would be to kindly ask him to put a link to the original license of Quasar and the copyright.

**Comment by trollmad3** [comment]
@MaxXor Did you contact him already?

**Comment by H4xl0r** [comment]
give me the fucking old version , we will crack it , and share it here also ...
upload it to virus total..
thats it 
easy peasy 

so link pls

**Comment by MaxXor** [comment]
@H4xl0r I strongly disagree with you and also this is not the appropriate place to discuss such things.
@trollmad3 I will contact him and closing this issue now.

**Comment by UnknownUser002** [comment]
@H4xl0r 

https://mega.nz/#!rAEVTSiQ!Pde-OFA1SSBhuCI4p1J_ySN3J8Wcc2DW1yHa_fI0RwM is version 1.1.0.3, cracked

https://mega.nz/#!TOoXmSjA!ydCO_TZrngF4c-paxcOoYTcsIG41LfcQRhtIdITo0kw is version 1.1.0.5, not cracked

Good look

**Comment by trollmad3** [comment]
@UnknownUser002 What is this for? the illegal sale?

**Comment by UnknownUser002** [comment]
@trollmad3 
someone bought this software and distributed it, but its protected (second link) with login and password which i dont have.
H4xl0r wanted to crack this, i only for
