### ISSUE TITLE
Backdoor

### ISSUE THREAD

**Issue by wjkhappy14** [quasar/QuasarRAT#680]
launch warn "Backdoor"

Windows Defender    [backdoor：Win32/Xiclog.A]

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Backdoor%3aWin32%2fXiclog.A&threatid=2147721343

**Comment by MaxXor** [comment]
Duplicate of https://github.com/quasar/QuasarRAT/issues/676
