### ISSUE TITLE
Listening to port through RDP

### ISSUE THREAD

**Issue by nikitafed** [quasar/QuasarRAT#682]
Hi

I have Quasar Rat setup on both the client and server side, and it'sworking beautifully when I listen to th3 port from a local session. 

However today I tried RDPing to the same machine through the internet, and my server does not pick up the connection on the same port, on the same machine. I first tried via a VPN I set up, then I tried a direct connection using port forwarding. 

Either way ... i can't catch the client communication through RDP,  even through everything works fine on the same machine with a local session 

I'm fairly technical, but not a RDP expert. Anyone has ideas on what i should be investigating?

**Comment by glides** [comment]
Sounds like you need to brush up on your basic networking. 

When you say you tried "RDPing" to the machine through the internet....do you mean Remote Desktop Protocol or simply you tried to access the machine remote like Quasar.

Either way...it sounds like the machine you want to access remotely is behind a NAT and you will need to setup port forwarding. If that is a foreign concept to you (and it is, clearly) it makes me wonder what in the world you're doing compiling this code and trying to get it to run.....

**Comment by MaxXor** [comment]
Do you mean like port forwarding in ssh? I don't think MS RDP does support that.
