### ISSUE TITLE
Unusual issue with every rat tool I use

### ISSUE THREAD

**Issue by TrollNation** [quasar/QuasarRAT#683]
Okay, so no clients are showing up at all. It use to work perfectly fine until I restored my PC and now no matter what rat tool I use I can't connect to anyone not even my own virtual box. My router is shit and won't properly port forward so I use ngrok instead and it worked fine before but now it just won't do anything. Have any ideas why?

**Comment by MaxXor** [comment]
https://github.com/quasar/QuasarRAT/issues/653
