### ISSUE TITLE
quasar triple crash

### ISSUE THREAD

**Issue by blackdragon83** [quasar/QuasarRAT#688]
Hi Everyone

I tried to look up the issue first, but couldnt find a solution that helped me.

So i created a pastebin and hope for further ideas.

https://pastebin.com/9tFeqUFF

I already reinstalled kodi + rebootet the machine several times, that didnt help either...

Thanks
BD

**Comment by MaxXor** [comment]
This is the wrong Quasar repo, check here: https://github.com/scakemyer/plugin.video.quasar
