### ISSUE TITLE
Only localhost connection works

### ISSUE THREAD

**Issue by kipkat** [quasar/QuasarRAT#689]
If I build a client with the following connection: `localhost:1337` works perfectly if I run on my computer but if I use the following connection `*my ip*:1337` doesn't work on another computer. Must I use only a DNS? The listening is correctly and the passwords are correct. What am I doing wrong?

EDIT: Added 3 different dynamic DNS hostnames and now doesn't work even from my computer. Is there a special option?

**Comment by MaxXor** [comment]
Check https://github.com/quasar/QuasarRAT/issues/653#issuecomment-378073374
