### ISSUE TITLE
Application not found

### ISSUE THREAD

**Issue by roosevelt155** [quasar/QuasarRAT#690]
I have run both the debug and the release but there is no Quazar application showing up in my BIN folder. It says that I already have the .NET framework installed. Any ideas? 
![capture](https://user-images.githubusercontent.com/25397975/44126207-82b39f26-9ffc-11e8-86c1-a5016e487fdc.PNG)

**Comment by MaxXor** [comment]
Do you use the `.bat`-files to build Quasar or Visual Studio?

**Comment by MaxXor** [comment]
Hm, weird. Can you show the output when building Quasar in Visual Studio?

**Comment by SSNLL** [comment]
I have a similar problem, but when I run my build-release.bat it doesn't even create a bin file. It just says build failed.

**Comment by MaxXor** [comment]
Install Visual Studio and try again.

**Comment by SSNLL** [comment]
The same error still pops up

**Comment by SSNLL** [comment]
Have other people had this error before?

**Comment by MaxXor** [comment]
Then just use Visual Studio to compile it, the batch files will get removed soon anyways.

**Comment by 007DarkShadow** [comment]
In my Quasar rat folder build-release is not showing what to do
