### ISSUE TITLE
How can I change the version of net framework 4.0 to 3.5?

### ISSUE THREAD

**Issue by Kolyan1337** [quasar/QuasarRAT#691]
Hello, How can I change the client version of net framework 4.0 to 3.5? how to fix these errors?
![image](https://user-images.githubusercontent.com/15040527/44157573-73fba400-a0bb-11e8-883a-34846b2e90e6.png)
The fact is that 3.5 is more common than 4.0, and installed by default.

**Comment by MaxXor** [comment]
Windows 8+ has .NET 4.0 pre-installed and most Windows 7 users have it already. Also .NET 4.0 is the last version which still supports Windows XP, so it covers basically all important Windows versions. There is no need to downgrade.
