### ISSUE TITLE
Avoid Virus Detection

### ISSUE THREAD

**Issue by ajhalls** [quasar/QuasarRAT#693]
Which section of this software triggers the antivirus software? Of all the features listed, the only ones I am looking for are:

    TCP network stream (IPv4 & IPv6 support)
    Fast network serialization (NetSerializer)
    Compressed (QuickLZ) & Encrypted (AES-128) communication
    Multi-Threaded
    Task Manager
    File Manager
    Startup Manager
    Remote Desktop
    Remote Shell
    Download & Execute
    Upload & Execute
    System Information
    Computer Commands (Restart, Shutdown, Standby)
    Reverse Proxy (SOCKS5)

If I were to remove the others like keylogging, would it still be recognized as a virus?

**Comment by yankejustin** [comment]
"If I were to remove the others like keylogging, would it still be recognized as a virus?"

Yup.

**Comment by Vylcon** [comment]
I'm also having this issue, our antivirus programs deletes most of the files. How can we cope with this?

**Comment by MaxXor** [comment]
Add an exception to your AV?
