### ISSUE TITLE
quasar server keeps crashing

### ISSUE THREAD

**Issue by zioncorp77** [quasar/QuasarRAT#702]
Hi when I build the server and try to run it with default settings it crashes kind of bummed out cause it was working for me for awhile thank you for you time

**Comment by MaxXor** [comment]
Please use the stable release from [here](https://github.com/quasar/QuasarRAT/releases/tag/v1.3.0.0). The latest version from `master` or `dev` branch might be unstable.

**Comment by zioncorp77** [comment]
Thank you I appreciate the quick answer 👍 💯
