### ISSUE TITLE
Someone stolen and sell Your code

### ISSUE THREAD

**Issue by cyber7072** [quasar/QuasarRAT#706]
Hello.
I found on the Polish internet web page that somebody stolen Your code.
He is selling it for 39$ (45 days license) to 229$ (year license).
As I see there is no credits for You - author of QuasarRAT.
This man is doing it again as I read on google.
Before the stolen code was named Secretlogger, now it's SpyKey.

Website with offer: https://spykey.cc/
He is also administrator of haker.com.pl forum used for advertisements.

**Comment by MaxXor** [comment]
Thanks for informing me, sadly there is not much I can do about that. There was a similar case before: https://github.com/quasar/QuasarRAT/issues/677
