### ISSUE TITLE
What are you doing brother? Are you fine?

### ISSUE THREAD

**Issue by hasanalizxc** [quasar/QuasarRAT#707]
Hi there,

Hope you are fine. I saw many questions from 2017 and 2018.

When will you answer these questions? Why are you making this i couldn't understand. You updated binaries 5 days ago but you are not answering questions. Is there a reason for this? If you don't answer questions, archive this repo and make it read-only.

Thanks.

**Comment by yankejustin** [comment]
This is a side project with little or no monetary funding, so it just gets very little attention these days. MaxXor is probably doing fine but i'm sure he has little time for this project and to answer so many duplicate issues...

**Comment by MaxXor** [comment]
I'm doing well and I'm refactoring code for future work on the roadmap (see https://github.com/quasar/QuasarRAT/issues/674). I do not answer some issues because features like remote microphone or webcam gonna be removed in the future.
