### ISSUE TITLE
Admin rights

### ISSUE THREAD

**Issue by hasanalizxc** [quasar/QuasarRAT#708]
Hi there,

Is needed to admin rights for run? And how can we make non admin rights the solution?

**Comment by MaxXor** [comment]
No, it's not necessarily required. But you only have limited functionality.

**Comment by hasanalizxc** [comment]
Thank you for your reply. So how can i configure source for without admin rights but full functionality. As you know many users don't run with admin rights and many users have UAC. Is this bypass UAC?

Thanks.

**Comment by MaxXor** [comment]
That's not possible. You can elevate the permissions of the client to admin rights though, but the user has to accept the UAC prompt.
