### ISSUE TITLE
Cant build quasar in vs 2015 ?

### ISSUE THREAD

**Issue by kalari123** [quasar/QuasarRAT#710]
I open the sln file and change building mode to release but still when i build it get 33+ errors and many of the errors is in ; but idk how i can fix it ?

**Comment by kalari123** [comment]
If someone can help why i get syntax errors ? i got framework 4.0 ofc but i need this program the old one is so laggy but there has been fixed by maxor so i want i want it

**Comment by yankejustin** [comment]
post some of the error messages youre getting

**Comment by MaxXor** [comment]
You probably just need to convert such "newish" switch-statements to if-statements:

https://github.com/quasar/QuasarRAT/blob/2e77af9db94d85036b4ab5111dde4c1618e01b41/Quasar.Server/Core/Messages/FileManagerHandler.cs#L156-L170

**Comment by kalari123** [comment]
What i need to do ? Go to build settings or wut i get the errors when i build but if i change the build mode to release i get 33 syntax error in ; and error dat says quasar.exe doesnt locate in bin release... I want to fix it cause i need the  quasar for remote desktop. - i am so happy if u help me maxxor :)

**Comment by MaxXor** [comment]
Get the latest build from [here](https://ci.appveyor.com/project/MaxXor/quasarrat) or [here (stable)](https://github.com/quasar/QuasarRAT/releases) if you can't fix the errors.
