### ISSUE TITLE
Protobuf isn't built into client.bin

### ISSUE THREAD

**Issue by ooojustin** [quasar/QuasarRAT#716]
Since the last release of the project, you've switched .NET serialization to protobuf.
The code to build assemblies in the Quasar.Client.csproj has not been adapted to this: https://github.com/quasar/QuasarRAT/blob/master/Quasar.Client/Quasar.Client.csproj#L150

The built stub in the server can only be used if it is stored in the same directory as protobuf-net.dll.
Theoretically, this could be fixed by changing the following:
`"$(SolutionDir)packages\ILMerge.2.14.1208\tools\ILMerge.exe" /out:"$(TargetDir)$(TargetName).all.exe" "$(TargetPath)" "$(TargetDir)Gma.System.MouseKeyHook.dll" "$(TargetDir)Quasar.Common.dll" /target:WinExe /wildcards /internalize`
to
`"$(SolutionDir)packages\ILMerge.2.14.1208\tools\ILMerge.exe" /out:"$(TargetDir)$(TargetName).all.exe" "$(TargetPath)" "$(TargetDir)protobuf-net.dll" "$(TargetDir)Gma.System.MouseKeyHook.dll" "$(TargetDir)Quasar.Common.dll" /target:WinExe /wildcards /internalize`

I rebuilt the project, and was able to confirm that protobuf was successfully merged into client.bin - but for some reason, after doing this, the connection would not work. So in one scenario, it can connect but crashes without the dll; in the other scenario it doesn't crash but it wont connect.

**Comment by MaxXor** [comment]
Oh, thanks I forgot the DLL.

**Comment by MaxXor** [comment]
I think the crashes could be fixed by changing
https://github.com/quasar/QuasarRAT/blob/1bc20d38c0b2c73ae892cd7b171e19eedbbd7c1c/Quasar.Server/Build/Renamer.cs#L60
to
```csharp
if (!typeDef.Namespace.StartsWith("Quasar") || typeDef.HasInterfaces) 
```

Maybe you could report back and tell if it's working, I can only check this tomorrow.

**Comment by ooojustin** [comment]
> I think the crashes could be fixed by changing
> [QuasarRAT/Quasar.Server/Build/Renamer.cs](https://github.com/quasar/QuasarRAT/blob/1bc20d38c0b2c73ae892cd7b171e19eedbbd7c1c/Quasar.Server/Build/Renamer.cs#L60)
> 
> Line 60 in [1bc20d3](/quasar/QuasarRAT/commit/1bc20d38c0b2c73ae892cd7b171e19eedbbd7c1c)
> 
>  if (typeDef.HasInterfaces) 
> 
> to
> ```cs
> if (!typeDef.Namespace.StartsWith("Quasar") || typeDef.HasInterfaces) 
> ```
> 
> Maybe you could report back and tell if it's working, I can only check this tomorrow.

The crashing is fixed by merging the protobuf assembly, and checking if the namespace starts with Quasar in renamer seemed to fix the connection issue. All seems to be working normally now, good job.
