### ISSUE TITLE
Client Won't Connect

### ISSUE THREAD

**Issue by Hacker151** [quasar/QuasarRAT#719]
I have two problems...
1: Whenever I used the Installation Settings, the client would not connect. So I recompiled everything and now
2: The client won't connect at all, even when I use localhost.
I have downloaded the latest version of both quasar and visual studio. I was doing testing on windows 7 and my AV was disabled as well.

**Comment by MaxXor** [comment]
Use the current latest stable release: https://github.com/quasar/QuasarRAT/releases/tag/v1.3.0.0
