### ISSUE TITLE
I cant make this work

### ISSUE THREAD

**Issue by cnilsecure** [quasar/QuasarRAT#720]
Hi,

I d/l the github compiled it with vs2017 on release i start the server all is fine
making the client still fine running my build client on the same computer as server
whats happening is server is in listening mode but as soon as i run the client build
it goes to not listening (like crash or something)
anyone having the same issue? (btw tried both windows server 2008 and windfows 7 both same result)

**Comment by mystyq** [comment]
In release mode, the server stops listening as soon as a client connects.  Haven't tried debug mode yet.

**Comment by MaxXor** [comment]
https://github.com/quasar/QuasarRAT/issues/719

**Comment by cnilsecure** [comment]
the whole point is to compile myself that why its a github project no?
if i am to just d/l binaries someone else compiled what the point?
