### ISSUE TITLE
Please, Release a new version 

### ISSUE THREAD

**Issue by Abraham313** [quasar/QuasarRAT#723]
You have  released Quasar v1.3.0.0 in Sep 28, 2016 . And now you have updated many things , Please, Release a new version.It will be very helpful for us to test this awesome rat.Pardon me ,I do not know how to use github and where to write a request.But I need this useful rat to monitor my kids. Thanks for your philanthropic  work.

**Comment by MaxXor** [comment]
I understand your concern and there were many people asking for a new release already. But reality is there were many under-the-hood changes users wouldn't really notice. Most of the work was done in preparation for a plugin system and to improve the security. But I think a new release could be possible at the end of this year.

**Comment by Abraham313** [comment]
Thanks for your kind response
