### ISSUE TITLE
Platform exception

### ISSUE THREAD

**Issue by agent47007** [quasar/QuasarRAT#724]
Hello,
can i get help??? i have tried to test Quasar for 2 weeks now after downloading and building it using
visual studio 2017, but i keep getting an error and been trying to debug 
![bug](https://user-images.githubusercontent.com/30630122/47929825-802d1b80-deca-11e8-9b88-89b51f93fe8c.png)
![bug2](https://user-images.githubusercontent.com/30630122/47929837-891ded00-deca-11e8-93e9-7d3ab80cfdcd.png)

thanks

**Comment by MaxXor** [comment]
Please build in debug mode and then debug Quasar, the exception should appear there too. You can the just copy it here.

**Comment by agent47007** [comment]
Hello,
thank you very much for your reply.
should i build from screenshot selecting Mixed platform and Quasar.client or  All CPU and Quasar.server

thanks

**Comment by MaxXor** [comment]
Keep it at "Mixed Platforms", just change "Release" to "Debug" and then do a right click on "Quasar.Server" on the right list and click "Debug".

**Comment by agent47007** [comment]
Hello,
am using a windows 10 i have also disabled my antivirus. please see error below after debugging
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Quasar.Common.Helpers.PlatformHelper' threw an exception.

Inner Exception 1:
COMException: The specified service does not exist as an installed service. (Exception from HRESULT: 0x80070424)
![bug3](https://user-images.githubusercontent.com/30630122/47953783-68b16980-df82-11e8-8bc7-0f9d4768ec59.png)
thanks

**Comment by MaxXor** [comment]
Okay good, on the exception you showed me in the previous screenshot, can you click on `Copy Details` and paste it here?

**Comment by agent47007** [comment]
Hello,
i could not copy the error details but i found out the reason why i had that error and it was because of my anti-virus, my antivirus has auto-containment. but after disabling all features of the anti-virus. i got these errors 
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\agent47\QuasarRAT\packages\ILMerge.2.14.1208\tools\ILMerge.exe" /out:"C:\Users\agent47\QuasarRAT\bin\Debug\Client.all.exe" "C:\Users\agent47\QuasarRAT\bin\Debug\Client.exe" "C:\Users\agent47\QuasarRAT\bin\Debug\protobuf-net.dll" "C:\Users\agent47\QuasarRAT\bin\Debug\Gma.System.MouseKeyHook.dll" "C:\Users\agent47\QuasarRAT\bin\Debug\Quasar.Common.dll" /target:WinExe /wildcards /internalize
copy "C:\Users\agent47\QuasarRAT\bin\Debug\Client.all.exe" "C:\Users\agent47\QuasarRAT\bin\Debug\client.bin" /Y" exited with code 1.	Quasar.Client			
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0169	The field 'Client._typeIndex' is never used	Quasar.Client	C:\Users\agent47\QuasarRAT\Quasar.Client\Networking\Client.cs	197	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'protobuf-net' could not be found.	Quasar.Client			
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'Gma.System.MouseKeyHook' could not be found.	Quasar.Client

**Comment by MaxXor** [comment]
Oh, okay... you need to restore the NuGet packages first..

**Comment by agent47007** [comment]
please whats the NuGet packages because it was just a new cloned project from git

**Comment by MaxXor** [comment]
Check out this on how to restore NuGet packages in Visual Studio: https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore

**Comment by agent47007** [comment]
ok thanks will check it out

**Comment by agent47007** [comment]
hello,
did several tries on package restore and update and package cache clearing but still same result. then i noticed that when i switch off my comodo anti virus thats when that error occurs while building but when my antivirus is one is shows success, then when i opened Quaser.exe in the release folder and tried to build an .exe/build client file and using my IP as localhost. there was nowhere on my PC it stored the build 
1>------ Rebuild All started: Project: Quasar.Common, Configuration: Release Any CPU ------
1>  Quasar.Common -> C:\Users\agent47\Desktop\QuasarRAT-master\QuasarRAT-master\bin\Release\Quasar.Common.dll
2>------ Rebuild All started: Project: Quasar.Server, Configuration: Release Any CPU ------
3>------ Rebuild All started: Project: Quasar.Client, Configuration: Release x86 ------
4>------ Rebuild All started: Project: Quasar.Common.Tests, Configuration: Release Any CPU ------
2>  Quasar.Server -> C:\Users\agent47\Desktop\QuasarRAT-master\QuasarRAT-master\bin\Release\Quasar.exe
5>------ Rebuild All started: Project: Quasar.Server.Tests, Configuration: Release Any CPU ------
5>  Quasar.Server.Tests -> C:\Users\agent47\Desktop\QuasarRAT-master\QuasarRAT-master\bin\Release\Quasar.Server.Tests.dll
4>  Quasar.Common.Tests -> C:\Users\agent47\Desktop\QuasarRAT-master\QuasarRAT-master\bin\Release\Quasar.Common.Tests.dll
3>  Quasar.Client -> C:\Users\agent47\Desktop\QuasarRAT-master\QuasarRAT-master\bin\Release\Client.exe
3>          1 file(s) copied.
6>------ Rebuild All started: Project: Quasar.Client.Tests, Configuration: Release x86 ------
6>  Quasar.Client.Tests -> C:\Users\agent47\Desktop\QuasarRAT-master\QuasarRAT-master\bin\Release\Quasar.Client.Tests.dll
========== Rebuild All: 6 succeeded, 0 failed, 0 skipped ==========

**Comment by Sir4004** [comment]
how fix Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0169	The field 'Client._typeIndex' is never used	Quasar.Client	C:\Users\darkh\Desktop\Quasar-1.4.1\Quasar.Client\Networking\Client.cs	188	Active

**Comment by Sir4004** [comment]
Clint Builder is not available in DEBUG configuration 
Please build the project using RELEASE  configuration

**Comment by Sir4004** [comment]
Clint Builder is not available i
![Uploading Screenshot 2023-07-05 113455.png…]()
n DEBUG configuration 
Please build the project using RELEASE  configuration
