### ISSUE TITLE
Error while building in release mode

### ISSUE THREAD

**Issue by agent47007** [quasar/QuasarRAT#726]
**Describe the bug**
I initially had issues with package manager while building in debug mode but unistalled and re-installed MouseKeyHook package and updated ILMerge. then i moved on to create a release of Quasar RAT and it showed a successful build in my Visual studio 2017 environment
when i opened the quasar.exe it demanded i create a certificate which i did and then saved the certificate.
when the quasar sceeen came up proceeded to client builder 
1. changed client tag name in basic settings
2. added my IP address in connection settings
3. did not change anything in installation setting 
4. changed setting in surveillance settings and clicked on build client
5. got an error COULD NOT LOCATE "client.bin" file. it should be in the same directory as quasar

i run a windows 10 PC, kindly see screenshot below
![quasar-error](https://user-images.githubusercontent.com/30630122/48313747-f57ea780-e5c0-11e8-917c-b45ff71e7c85.png)

**Comment by MaxXor** [comment]
Most of the time the AV is deleting the file. Just add an exception to your AV.

**Comment by agent47007** [comment]
hello,
i added the folder as an exception to comodo antivirus 10. 
but i noticed that anytime i build a solution when my anti-virus is on i get a successful build but without the client.bin file
but when i build a solution when i have disabled of my antivirus setting i get the following error below.
i have already tried and tried package restore so many times and play around with package manager for hours and days without any resolve.
i also disabled most of my windows defender settings. can you do a build and send me
thanks
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\agent47\achike\QuasarRAT\packages\ILMerge.2.14.1208\tools\ILMerge.exe" /out:"C:\Users\agent47\achike\QuasarRAT\bin\Release\Client.all.exe" "C:\Users\agent47\achike\QuasarRAT\bin\Release\Client.exe" "C:\Users\agent47\achike\QuasarRAT\bin\Release\protobuf-net.dll" "C:\Users\agent47\achike\QuasarRAT\bin\Release\Gma.System.MouseKeyHook.dll" "C:\Users\agent47\achike\QuasarRAT\bin\Release\Quasar.Common.dll" /target:WinExe /wildcards /internalize
copy "C:\Users\agent47\achike\QuasarRAT\bin\Release\Client.all.exe" "C:\Users\agent47\achike\QuasarRAT\bin\Release\client.bin" /Y" exited with code 1.	Quasar.Client	
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0169	The field 'Client._typeIndex' is never used	Quasar.Client	C:\Users\agent47\achike\QuasarRAT\Quasar.Client\Networking\Client.cs	197	Active

**Comment by 15w34r0n3D4y** [comment]
Solution for this error: https://github.com/quasar/QuasarRAT/issues/727

**Comment by treshchev** [comment]
I have a similar problem, I can't fix it, can someone help me? I click on settings and this window pops up
![qua](https://github.com/quasar/Quasar/assets/113633658/7fa9b99c-6713-4072-96b5-9f9f545f2aa4)
