### ISSUE TITLE
client.bin is not existing

### ISSUE THREAD

**Issue by knuepple** [quasar/QuasarRAT#734]
I'm from Germany so sorry for bad English.. When i boot up the Build release, my Cmd tells me that the file is an Virus or else... that means that i can't build a client in Quasar because the file cannot be found... 

![not working](https://user-images.githubusercontent.com/45774695/49809575-9054d800-fd5f-11e8-8752-25acd702a2d2.png)

**Comment by MaxXor** [comment]
https://github.com/quasar/QuasarRAT/issues/727
