### ISSUE TITLE
make a tutorial how to compile from  the sourcecode 

### ISSUE THREAD

**Issue by isabella98** [quasar/QuasarRAT#735]
Hi ! I am very new in this section and I am very attracted to learn something new about  malware and their behaviour. Is their  anyone who can make a video tutorial about how to compile Quasar rat from it's source code ?. I am not asking for a new version release or something like that. I just want to learn about how to use GitHub C# source code with visual studio 2017.**I think  It will be helpful  to widen the horizon of my knowledge** 
**Thanks everyone**

**Comment by MaxXor** [comment]
The section "Compiling" in the [Readme](https://github.com/quasar/QuasarRAT/blob/master/README.md) basically describes the steps to compile the project. You just need to have Visual Studio 2017 with C# featureset installed.
