### ISSUE TITLE
is there a way to use this on my own network without having to port ford if so please tell me

### ISSUE THREAD

**Issue by rustywolf021** [quasar/QuasarRAT#740]
I have set up the build on how i want, i tested it on my own pc and it works so i uninstalled it from my pc, the next day i try use it on another pc i got (windows laptop and it has no anti virus installed) and it gets installed in the write places but when i go to see if there are any connections there are none.

**Comment by NetworkAdapter** [comment]
If you're using it on your LAN, get your local IPV4 address and input it into Quasar's host

**Comment by rustywolf021** [comment]
Where do I find that?

**Comment by NetworkAdapter** [comment]
Is the PC on your local network? Can the PC ping your local IP address?

**Comment by rustywolf021** [comment]
Yeah I think I've found it and fixed it I'll have to try lafter thow doing stuff thanks :)
