### ISSUE TITLE
Been Unable to Crypt Quasar on employee's PC 

### ISSUE THREAD

**Issue by noobshow** [quasar/QuasarRAT#743]
We bought 5 notebooks(Windows 10 x64 bit and Windows 7 x64 bit) for new staffs and somehow(based on the project stage and secrecy it currently needs) we need to monitor how they work with Organization Source Code and if, maybe they are violating any rules(Sharing Codes, Secrets, etc).

I, being the one in charge of Security and Group Policy have been unable to Crypt Quasar with almost 6 types of crypters in C# and C++, especially to load it in memory.
We couldn't disable their Security Essential, Defender for Other Security reasons.

Without Quasar being cryptable, even the most legitimate uses would have problems using it because all Antivirus would be quick to swallow the file(Coz it's too public) and users would always have to teach each other how to either disable or Allow Viruses even when it's not meant for illegitimate use...

Is Quasar not Encryptable?

[https://github.com/Axe-Usa/Example-Crypter](url)
[https://0x00sec.org/t/c-a-simple-runtime-crypter/519/7](url)
[https://github.com/ConnorPatterson/Pe-Loader-Sample](url)

I could see the responses here about not wanting to talk about crypters, but thinking with common sense would everyone be okay to share virus-easily-detected files, even for legitimate purposes?

**Comment by enkianu** [comment]
Ọmọ aiye!

**Comment by MaxXor** [comment]
There is no need to disable your Antivirus, simply add an exception for the Quasar client. Adding one exception for a known software doesn't make your system less secure. I can't do anything about the AV detections. (Quasar is indeed cryptable with crypters which support .NET 4.0 applications, the ones you linked don't support that)

**Comment by noobshow** [comment]
Wow!
Thanks for the tip, "don't support .NET 4.0 applications".

I think we need to work out the code and not use ready-made crypters..

Thanks so much @MaxXor for the heads-up.

Wish i could gather more guys(from work) to this great job you guys are doing...

Thanks once again,
noobshow.


> There is no need to disable your Antivirus, simply add an exception for the Quasar client. Adding one exception for a known software doesn't make your system less secure. I can't do anything about the AV detections. (Quasar is indeed cryptable with crypters which support .NET 4.0 applications, the ones you linked don't support that)

**Comment by MaxXor** [comment]
These tools usually just set the wrong .NET framework version. See here for the first link u mentioned:
https://github.com/Axe-Usa/Example-Crypter/blob/9080944f3bacc6c29fa57642d1ca168b5cea51a3/CrypterExample/Compiler.cs#L60-L63

**Comment by noobshow** [comment]
Thanks once again, we finished coding the Crypter and was able to make it run in memory(through some hacks) and it was working fine.

This is the biggest and the best open source Remote Administration Tool ever created, hopefully me and some at work(23 Sec. Development Team) might someday take a week or two weeks off work and run big things on this codebase(officially)....

Nice work done.

Thanks,
noobshow.

> These crypters usually just set the wrong .NET framework version. See here for the first link u mentioned:
> https://github.com/Axe-Usa/Example-Crypter/blob/9080944f3bacc6c29fa57642d1ca168b5cea51a3/CrypterExample/Compiler.cs#L60-L63

**Comment by xuxuedong** [comment]
@noobshow @MaxXor  pls, i have a problem, when i crypt the quasar client, and load assembly use another csharp utility, why the remote desktop can't display the full victim screen?

**Comment by xuxuedong** [comment]
@noobshow @MaxXor pls, i have a problem, when i crypt the quasar client use xor, and load assembly use another csharp utility, why the remote desktop can't display the full victim screen?

**Comment by xuxuedong** [comment]
i have another test, didn't crypt the assembly, just
byte[] plainBytes = File.ReadAllBytes(file);
then 
Assembly exeAssembly = Assembly.Load(encoded_file);
object[] parameters = new object[1];
exeAssembly.EntryPoint.Invoke(null, parameters);
but still can't display the full victim screen?

**Comment by noobshow** [comment]
> i have another test, didn't crypt the assembly, just
> byte[] plainBytes = File.ReadAllBytes(file);
> then
> Assembly exeAssembly = Assembly.Load(encoded_file);
> object[] parameters = new object[1];
> exeAssembly.EntryPoint.Invoke(null, parameters);
> but still can't display the full victim screen?

When you open and start the Remote Desktop, the Connection got restarted(like disconnect and reconnect), right?
I figured out the bug when i was personally testing this at home through Assembly.Load Invoke and since it wasn't in the same Project, i didn't find it easy to debug ad we weren't needing the RDP feature at work, so i just ignored it.
