### ISSUE TITLE
Release Configuration not available

### ISSUE THREAD

**Issue by Crypt0script** [quasar/QuasarRAT#745]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Server OS: [e.g. Windows 10]
 - Client OS: [e.g. Windows 7]
 - Quasar Version: [e.g. 1.3.0, commit-id]

**Additional context**

**Comment by MaxXor** [comment]
Please provide a clear description.

**Comment by Crypt0script** [comment]
after building the Sln.In the Bin only appears the Debug config but the release is not available.
![image](https://user-images.githubusercontent.com/46568928/50978641-7c190d80-14ba-11e9-85b1-45185a507260.png)

**Comment by MaxXor** [comment]
https://github.com/quasar/QuasarRAT#compiling
