### ISSUE TITLE
additional  remote connections

### ISSUE THREAD

**Issue by vtheomain** [quasar/QuasarRAT#746]
server .exe upon execution contacts two other ip addresses in addition to the one set in the builder

.exe 80	http	50.19.247.198	ec2-50-19-247-198.compute-1.amazonaws.com Established
.exe  80        http	104.26.15.73		Established

**Comment by MaxXor** [comment]
https://github.com/quasar/QuasarRAT/issues/637

**Comment by vtheomain** [comment]
#637 refers to the client. #746 is additional connections from the server i.e. exe build

IP: | 50.19.247.198
840169414
ec2-50-19-247-198.compute-1.amazonaws.com
14618
Amazon.com
Amazon.com
None detected


104.26.15.73
--
1746538313
104.26.15.73
13335
Cloudflare
Cloudflare
None detected

**Comment by xuxuedong** [comment]
yeah, i have the same question

发自我的 iPhone

在 2019年1月11日，00:49，vtheomain <notifications@github.com<mailto:notifications@github.com>> 写道：


#637<https://github.com/quasar/QuasarRAT/issues/637> refers to the client. #746<https://github.com/quasar/QuasarRAT/issues/746> is additional connections from the server i.e. exe build

IP: | 50.19.247.198
840169414
ec2-50-19-247-198.compute-1.amazonaws.com<http://ec2-50-19-247-198.compute-1.amazonaws.com>
14618
Amazon.com<http://Amazon.com>
Amazon.com<http://Amazon.com>
None detected

104.26.15.73

1746538313
104.26.15.73
13335
Cloudflare
Cloudflare
None detected

**Comment by MaxXor** [comment]
Which version are you using and where did you download it from?

**Comment by xuxuedong** [comment]
1.3.0, and i compiled by myself

发自我的 iPhone

在 2019年1月11日，01:53，MaxXor <notifications@github.com<mailto:notifications@github.com>> 写道：


Which version are you using and where did you download it from?

**Comment by xuxuedong** [comment]
download from the repo page instead of the release page

发自我的 iPhone

在 2019年1月11日，01:53，MaxXor <notifications@github.com<mailto:notifications@github.com>> 写道：


Which version are you using and where did you download it from?

**Comment by MaxXor** [comment]
There are absolutely zero connections. I've tried using the latest master branch and the binaries from GitHub v1.3.0.0. Please send me your binaries.

**Comment by xuxuedong** [comment]
i am sorry, i was misunderstanding, in fact, what i mean is, the client machine has two connections, it was resolved by #637
