### ISSUE TITLE
"powershell" in Remote shell, just got stuck

### ISSUE THREAD

**Issue by CaledoniaProject** [quasar/QuasarRAT#748]
Fresh compile from master branch, the remote shell isn't working well.

I typed `powershell -ep bypass` and it become like this:

![screen 2019-01-14 at 12 15 43](https://user-images.githubusercontent.com/1357701/51096291-52cbea80-17f6-11e9-98ae-1c2bba05eab7.jpg)

And the shell is no longer working, was it expected?

P.S I'm Running both client and server on Windows 8.1.

**Comment by MaxXor** [comment]
The shell implementation has some problems when other processes are opened inside it. :/

**Comment by CaledoniaProject** [comment]
Not really. Built a release with latest dev branch:

1. open shell
2. type whoami
3. type powershell -- Got eird display like in the screenshot
4. type cmd /c whoami -- No results, shell is broken

![screenshot 2019-01-27 at 1 52 37 pm](https://user-images.githubusercontent.com/1357701/51797261-127b5c00-223b-11e9-89d1-a2e3071309c7.jpg)

**Comment by MaxXor** [comment]
Could you trying entering some powershell command? For me it looks like this:

![powershell](https://user-images.githubusercontent.com/7271470/51798704-3a58c880-2217-11e9-9fff-677d202122dc.png)

**Comment by MaxXor** [comment]
What Powershell version are you using?

**Comment by CaledoniaProject** [comment]
I've installed the client on the following:

* Windows 2008 R2 - PS 2.X
* Windows 8.1 - PS 4.X

**Comment by MaxXor** [comment]
Okay thanks a lot for testing! I can confirm it on my Windows 7 machine with PS 2.X. I think it's most likely a problem with the old PS versions. When I test it with [ncat](https://nmap.org/ncat/) for example, which also spawns a new process and redirects input/ouput to the shell, it's working flawlessly.

I don't think it's worth it to add some complicated workaround for older Powershell versions.

**Comment by CaledoniaProject** [comment]
Yeah, metasploit has similar issue on Windows 7.

**Comment by MaxXor** [comment]
Maybe some issue with Windows versions < 10?
