### ISSUE TITLE
Keylogger skips keys or an entire portion randomly

### ISSUE THREAD

**Issue by ggregor** [quasar/QuasarRAT#749]
Keylogger skips pressed keys or an entire portion of the log randomly. The keylogger class seems to work fine, but when _WriteLogFile_ method is called the AES encryption seems to mess things up. If the log is written without AES encryption the keylogger works as expected.

**Comment by ggregor** [comment]
It's confirmed, this is happening because of creating too many new instances of Aes256 every time it is needed to encrypt or decrypt logging data. 

For example look at  _WriteLogFile_ at **FileHelper.cs**. It asks for log file to be decrypted using function _ReadLogFile_ which uses a fresh instance of Aes256 class, while immediately after that _WriteLogFile_ method itself creates again a new Aes256 instance to encrypt the entire file. And all this processing power is taking place every 15 seconds. 

I suspect this bug occurs when some logFile clearing is taking place before the current interval has the chance to finish these heavy cpu consumption operations, resulting in permanently losing that key logging portion. 

I fixed it by creating only one instance of Aes256 created by FileHelper constructor, and every encryption/decryption operation uses that same instance. Everything is working great now, and also Log retriever from Server side is much faster now, because again, server is not creating a new instance for each day file, but using a single instance to decrypt all dates.

**Comment by MaxXor** [comment]
Thanks, fixed.

**Comment by MaxXor** [comment]
The Aes256 constructor takes a while when deriving the key (it's using 50k iterations in PBKDF2) used for encryption & decryption. During these iterations the Keylogger might skip keys because it's waiting for the iterations to finish. Your solution was correct to make use of a single instance.
