### ISSUE TITLE
Question: Why was remote webcam function removed?

### ISSUE THREAD

**Issue by ggregor** [quasar/QuasarRAT#750]
I just noticed that old Quasar from the year 2016, 2017 included the remote webcam function, I am curious why was this function removed from recent versions? Thanks!

Edit: Also audio recording function is still not merged with the recent releases, even though it has been implemented from some pull back in 2017, will it be merged in the near future?

**Comment by MaxXor** [comment]
Check out the [roadmap](https://github.com/quasar/QuasarRAT/blob/master/ROADMAP.md). It's explained there. Please keep the discussion about it in this issue: https://github.com/quasar/QuasarRAT/issues/674

**Comment by NatoBoram** [comment]
To actually answer the question : 

>## [Remove features such as password recovery](https://github.com/quasar/QuasarRAT/blob/master/ROADMAP.md#remove-features-such-as-password-recovery)
>Features which could get abused too easily should get removed from Quasar.

**Comment by BurntDog** [comment]
> To actually answer the question :
> 
> > ## [Remove features such as password recovery](https://github.com/quasar/QuasarRAT/blob/master/ROADMAP.md#remove-features-such-as-password-recovery)
> > Features which could get abused too easily should get removed from Quasar.

Controlling what people have access to, it's called Communism....
