### ISSUE TITLE
When running build-release it only downloads Client.bin and Client.exe

### ISSUE THREAD

**Issue by Viktordude** [quasar/QuasarRAT#756]
When running build-release it only downloads Client.bin and Client.exe

**Expected behavior**
It should have downloaded a few other files
![udklip](https://user-images.githubusercontent.com/47610942/52739989-61aee400-2fd2-11e9-82f3-afca2bddb4bd.PNG)

**Screenshots**

**Comment by MaxXor** [comment]
Add an exception to your AV.

**Comment by Viktordude** [comment]
> Add an exception to your AV.

This didn't work
