### ISSUE TITLE
i haved a error  when  no debug on vs2017 

### ISSUE THREAD

**Issue by nbsp-null** [quasar/QuasarRAT#758]
private void SetBuildState(bool state)
        {
            try
            {
                // this.Invoke((MethodInvoker)delegate
                // {
                //FrmBuilder.btnBuild.Text = (state) ? "Build" : "Building...";
                
                   // FrmBuilder.btnBuild.Enabled = state;
                //});
            }
            catch (InvalidOperationException)
            {
            }
        }

**Comment by hieutvan** [comment]
*had
