### ISSUE TITLE
No release version

### ISSUE THREAD

**Issue by Trixelit** [quasar/QuasarRAT#761]
When I build it using vs 2017, it ONLY builds the debug version. How do I get the release version?

**Expected behavior**
The release version to be in the bin\ folder

**System**
 - Server OS: Windows 10
 - Client OS: N/A
 - Quasar Version: Latest

**Comment by MaxXor** [comment]
This should help you: https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-debug-and-release-configurations?view=vs-2017

**Comment by Trixelit** [comment]
Thank you!
It works now :)
