### ISSUE TITLE
Clients disappear when program is closed

### ISSUE THREAD

**Issue by DeliriousGod** [quasar/QuasarRAT#764]
The clients disappear when I close quasar.exe. How do I make sure all the clients stay on it?

**Comment by Archikle** [comment]
The fuck are you on about dude? Thats how a RAT program works lol

**Comment by jonrules48** [comment]
HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. I wonder why?
