### ISSUE TITLE
Keylogger issue

### ISSUE THREAD

**Issue by Bo0g1eMaN** [quasar/QuasarRAT#778]
hello, the keylogger logs seem to just show abunch of odd letters or symbols, I'm not quite sure if this is a bug or I am required to do some kind of conversion

**Comment by SkeltonMod** [comment]
Did the other features work? I had this before and it was the AV blocking the keylogger.

**Comment by Bo0g1eMaN** [comment]
yes all other features worked, AV was disabled

**Comment by Bo0g1eMaN** [comment]
issue appears to have fixed itself, the most recent logs have shown actual data instead of gibberish

**Comment by bbyte-lab** [comment]
> 
> 
> hello, the keylogger logs seem to just show abunch of odd letters or symbols, I'm not quite sure if this is a bug or I am required to do some kind of conversion

Hi, i have the same probleme:
result_log: Ò;hª¥š„{ ¹Z ˜¢þï@³Bðîé²…Š¸p§å’V•—Ø"7j)iú2ªž™­ Û,ã(/á™5v05ˆOƒL|eW×p½Â=ÿ£eu<Š¢ùw>¢jœ"™›•:- .""_K¯îu+k¤”ãÃðÜVVHÐ4ë gÐo2rùµ6 ^ÂUËêp«¶<pŸÜ::woÏ[I;“»jó‘í¶Ý [Ë¢(Ò©\8ÌT†‡k6.…íÞ<ÌJqÉž‚ZJÙ ™û¼‚Lá¾ºpÛx:^ÀY ==> is probleme for, i need patch, i'm trying on this and other thing too...

I'm working to translate this version in French version and little function added  but Alpha_Mode_Enable, i'm in testing nex function and implementation ...

Beta and Log Bug: https://i.imgur.com/OBdX3WE.png
I think we need to add an new Object or 2 ^^and Log_Cleaner function on Right_click to update or cleanup Logs !?

Quasar is a Good Project 👍

**Comment by sh1va73** [comment]
I am having same issue with keylogger today. Yesterday it worked fine, so I dont know what is causing the issue.

**Comment by jctmf** [comment]
Same problem today.

**Comment by MaxXor** [comment]
The problem is the update mechanism of the client. When a client version gets updated, the old log files can not be decrypted anymore. A static key must be used that remains the same between upgrades.
