### ISSUE TITLE
BUILD-RELEASE BAT FILE AND BUILD DEBUG MISSING

### ISSUE THREAD

**Issue by thee038** [quasar/QuasarRAT#779]
I really want to know how i can use this file on my windows, since the release bat file is no more available. Help Me please.

**Comment by jonrules48** [comment]
What version are you using? Is there a .sln file?

**Comment by thee038** [comment]
I am using version 1.3 but i would want to try the update

**Comment by jonrules48** [comment]
Is there a sln file?

**Comment by sriramvasan** [comment]
Yes there is an sln file
