### ISSUE TITLE
client.bin

### ISSUE THREAD

**Issue by TheRemi** [quasar/QuasarRAT#780]
There is no client.bin file and i cant figure out how to get it so it will not run

**Comment by marlkiller** [comment]
1. build Release Quasar.Server , you can get the 'Quasar.exe'
2. build Release Quasar.Client , you can get the 'client.bin'

**Comment by servin** [comment]
you can use the release version here 
https://github.com/quasar/QuasarRAT/releases

> There is no client.bin file and i cant figure out how to get it so it will not run
