### ISSUE TITLE
Server behind cloudflare is not receiving client

### ISSUE THREAD

**Issue by complana** [quasar/QuasarRAT#783]
**Describe the bug**
In the client builder, when a direct IP address is specified for the host (server), the client is connecting fine. But when a domain name (hosted on cloudflare) associated with the IP is used, the client is not connecting to the server.

**To Reproduce**
Use a domain name in the client builder. The domain name should be hosted on cloudflare.

**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Quasar Version: Latest pull

**Comment by 0xE232FE** [comment]
You do not know how cloudflare works.
Cloudflare is using Argo Tunnel to go through any service you want. Just enable Argo Tunnel on your Domain in Cloudflare and install Argo Tunnel Software on the client.

**Comment by complana** [comment]
Thanks, I have no idea how it works indeed.

Cheers
