### ISSUE TITLE
Latest version server works in linux?

### ISSUE THREAD

**Issue by complana** [quasar/QuasarRAT#784]
Hi, this is rather a question than bug. Is the latest Quasar server working in linux using Mono? I noticed that in some release information. However, I'm getting SystemNotIMplemented error when running in linux using Mono. Any suggestion as to why?

**Comment by MaxXor** [comment]
Version [1.3.0.0](https://github.com/quasar/QuasarRAT/releases/tag/v1.3.0.0) should work fine on Linux with Mono (except remote desktop).

**Comment by complana** [comment]
Hello @MaxXor. Thanks for taking time to answer. I know this is no longer maintained but just to inform you that using latest mono build the remote desktop worked flawlessly (even the mouse input). However the file manager is broken with GetDirectoryFailed error.

**Comment by MaxXor** [comment]
Thanks for the info!
