### ISSUE TITLE
Can´t connect

### ISSUE THREAD

**Issue by nugget-nugget** [quasar/QuasarRAT#785]
I can not connect with any pc. I put the same password+port to connect but it´s not working. I am trying to connect and I am waiting hours but it still not working

**System**
 - Server OS:  Windows 10
 - Client OS:  Windows 10
 - Quasar Version: 1.3.0

**Comment by Pernat1y** [comment]
LAN or via internet?
Connecting via domain or IP?
Static or dynamic IP?
Do you have ports forwarded on router?

**Comment by nugget-nugget** [comment]
LAN
Connecting via IP
i tryed both
yes

**Comment by Pernat1y** [comment]
You don't need port forwarding for LAN.
Maybe blocked by server/client's firewall?

**Comment by nugget-nugget** [comment]
It can´t be my firewall because I am turning it everytime off.
Ok thx well I will try it without port

**Comment by Biswajit165** [comment]
please add 3 functions to this QuasarRat application 
1. create a function where other application, video, photo, pdf, rar, zip, text, etc "combine" with a client.exe file and background run
2. [Not Combine client.exe file] normal client.exe file when victim clicks on the application, a message of my choice will be shown victim system(Example "application error")
3. Create a function that can recording voice directly from Victim
