### ISSUE TITLE
Quasar Rat won’t connect client to host

### ISSUE THREAD

**Issue by JuanTwoosh** [quasar/QuasarRAT#788]
I am experimenting with Quasar rat. I have successfully downloaded it and created multiple clients. I have attempted to install these on a windows 7 (I have windows 8.1) and I have used a usb to transfer the client. I have then clicked on the client after disabling the firewall and it loads than does nothing. (Probably normal). But my laptop doesn’t connect to it. I am listening on the same port that I have opened inbound on my computer and outbound in the other. They still don’t connect. It has to be something with the port and their connection; however In my files I can see the other computers drive, but when I click on it, it requires permission. From the media server on their computer. Someone please help!

**Comment by jonrules48** [comment]
Did you port foward?

**Comment by JuanTwoosh** [comment]
No

**Comment by AndyInvictus** [comment]
> Did you port foward?

Do you still have to portforward within your own internet?
Right now I am trying to RAT myself and my other computer doesn't seem to connect
