### ISSUE TITLE
Decrypt keylogger files

### ISSUE THREAD

**Issue by telar3** [quasar/QuasarRAT#796]
How can you decrypt the keylogger files stored on the client?

**Comment by jonrules48** [comment]
What version are you using?

**Comment by telar3** [comment]
Version 1.3.0.0

**Comment by jonrules48** [comment]
Weird, it shouldn't do that. Try uninstalling and reinstalling

**Comment by telar3** [comment]
I think issue #673 addresses my problem. Maxxor wrote the following solution:

> @kosta14 The log files on the client are stored encrypted. :) You can make it readable by decrypting it using this function and setting the right key here before.

But i can't seem to make it work...
