### ISSUE TITLE
How to make it undetected by AV?

### ISSUE THREAD

**Issue by AnimeniacSimey** [quasar/QuasarRAT#798]
When I build loader Avast detects it as RAT.... is there any way to circumvent this? Thanks!

**Comment by yankejustin** [comment]
Add an exception.

**Comment by AnimeniacSimey** [comment]
Not what meant -_-

**Comment by yankejustin** [comment]
It's easily-detectable for good reason. :)

**Comment by yellowishBlue** [comment]
QuasarRAT was not created with the intention of illegal use. If it was, then it would have not been open-source...

**Comment by Xayaan** [comment]
It is a RAT after all. Best to keep your BH questions to yourself.

**Comment by Evo993** [comment]
Think this is a obviously logical question, keep your bh answers to yourself, only answer when you KNOW the answer or can help
