### ISSUE TITLE
No .exe is created

### ISSUE THREAD

**Issue by 93493** [quasar/QuasarRAT#803]
Hello,

i have some Problems. First i get at start up and in the Builder itself a NET Framework Error and don't know if this related to the another problem

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.TypeInitializationException: Der Typeninitialisierer für "Quasar.Common.Helpers.PlatformHelper" hat eine Ausnahme verursacht. ---> System.Management.ManagementException: Nicht gefunden 
   bei System.Management.ThreadDispatch.Start()
   bei System.Management.ManagementScope.Initialize()
   bei System.Management.ManagementObjectSearcher.Initialize()
   bei System.Management.ManagementObjectSearcher.Get()
   bei Quasar.Common.Helpers.PlatformHelper..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Quasar.Common.Helpers.PlatformHelper.get_RunningOnMono()
   bei Quasar.Server.Controls.AeroListView.OnHandleCreated(EventArgs e)
   bei System.Windows.Forms.Control.WmCreate(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

The other problem is when i created the .exe in the Builder and start it, it's not in the location like preset before. For example C:\Users\PC\AppData\Roaming\8172\Client.exe. Nothing there! 

Can you help?

**Comment by 93493** [comment]
Hello??

**Comment by ValonK** [comment]
Open the Quasar Solution -> Clean -> Rebuild

**Comment by 93493** [comment]
Hello Valon. What do you mean?

**Comment by ValonK** [comment]
> 
> 
> Hello Valon. What do you mean?
> 
> Edit: I tried now Quasar v1.2.0.0. No NET errors here but the same like before with .exe file. I used before the main Site and cloned it in VS.

im sorry but i didnt understand what you mean`? what do you mean by "I used before the main Site and cloned in VS" ?

**Comment by 93493** [comment]
First i used the main URL from here and cloned it to Visual Studio. I get always NET Error and didn't know if it was related to the other problem. My guess was that the builded .exe was maybe corrupt BUT then i tried the pre-compiled one from the download section. Same problem here.

Let me explain again:

When i builded the .exe and click on it, it doesn't creates the .exe file on the Windows Hard Drive. Don't know why,

**Comment by ValonK** [comment]
This issue sounds like your AntiVirus is deleting the exe, make sure that you add Exceptions to Windows Defender.

**Comment by 93493** [comment]
I did. Exceptions and AV and FW disabled. The same.

**Comment by 93493** [comment]
I checked the Task Manager now when i started Client-built.exe. CPU goes high to 30% and exe disappears. Then it comes back goes up to 30% and dissappears.... The whole time till the point when i kill it.

**Comment by ValonK** [comment]
Have you tried debugging without stack traces or information is hard to tell

**Comment by 93493** [comment]
So. i tried it in Virtual Machine and it works! Dont know why its not working on my main PC. To your question: Dont know how i debug

**Comment by 93493** [comment]
I did now a debug on client.exe. Is this correct? here the result

"Client-built.exe" (Win32): "M:\Neuer Ordner (2)\Quasar v1.3.0.0\Client-built.exe" geladen. Das Modul wurde ohne Symbole erstellt.
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\ntdll.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\mscoree.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\kernel32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\KernelBase.dll" geladen. 
Der Thread 0x2ed0 hat mit Code 0 (0x0) geendet.
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\advapi32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\msvcrt.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\sechost.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\rpcrt4.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\sspicli.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\cryptbase.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\bcryptprimitives.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\shlwapi.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\combase.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\ucrtbase.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\gdi32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\win32u.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\gdi32full.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\msvcp_win.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\user32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\imm32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\kernel.appcore.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\version.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\vcruntime140_clr0400.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\ucrtbase_clr0400.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\psapi.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\psapi.dll" wurde entladen.
"Client-built.exe" (Win32): "C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\46c6217a2d77a20d9fff301af2e1d67e\mscorlib.ni.dll" geladen. 
"Client-built.exe" (CLR v4.0.30319: DefaultDomain): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\ole32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\uxtheme.dll" geladen. 
"Client-built.exe" (CLR v4.0.30319: DefaultDomain): "M:\Neuer Ordner (2)\Quasar v1.3.0.0\Client-built.exe" geladen. Das Modul wurde ohne Symbole erstellt.
"Client-built.exe" (Win32): "C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\oleaut32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\assembly\NativeImages_v4.0.30319_32\System\f3efcabd0ee45af4d0d9146029f0f860\System.ni.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Drawing\ab90ddf3011305b543d184172990f13c\System.Drawing.ni.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\3ec32c6321c16870e73110ebc87cfdaf\System.Windows.Forms.ni.dll" geladen. 
"Client-built.exe" (CLR v4.0.30319: Client-built.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"Client-built.exe" (CLR v4.0.30319: Client-built.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"Client-built.exe" (CLR v4.0.30319: Client-built.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\shell32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\cfgmgr32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\SHCore.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\windows.storage.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\profapi.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\powrprof.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\umpdc.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\cryptsp.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\bcrypt.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\rsaenh.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\f364e4396f858010442117cd31789bd4\System.Core.ni.dll" geladen. 
"Client-built.exe" (CLR v4.0.30319: Client-built.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"Client-built.exe" (Win32): "C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Management\66a1ecbc24b2fec57fc992fd9a891b58\System.Management.ni.dll" geladen. 
"Client-built.exe" (CLR v4.0.30319: Client-built.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\clbcatq.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\wbem\wmiutils.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\wbemcomn.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\ws2_32.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\wbem\wbemprox.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\Microsoft.NET\Framework\v4.0.30319\WMINet_Utils.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\wbem\wbemsvc.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\wbem\fastprox.dll" geladen. 
Der Thread 0x2a78 hat mit Code 0 (0x0) geendet.
"Client-built.exe" (Win32): "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\mscorlib.Resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"Client-built.exe" (Win32): "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\mscorlib.Resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"Client-built.exe" (Win32): "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\mscorlib.Resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" wurde entladen.
"Client-built.exe" (CLR v4.0.30319: Client-built.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\propsys.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\edputil.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\Windows.StateRepositoryPS.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\urlmon.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\iertutil.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\cldapi.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\fltLib.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\WinTypes.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\AppResolver.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\BCP47Langs.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\slc.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\userenv.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\sppc.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\OneCoreCommonProxyStub.dll" geladen. 
"Client-built.exe" (Win32): "C:\Windows\SysWOW64\OneCoreUAPCommonProxyStub.dll" geladen. 
Der Thread 0x2cd0 hat mit Code 0 (0x0) geendet.
Der Thread 0xc68 hat mit Code 0 (0x0) geendet.
Der Thread 0x2ee4 hat mit Code 0 (0x0) geendet.
Der Thread 0x27b0 hat mit Code 0 (0x0) geendet.
Der Thread 0x2f7c hat mit Code 0 (0x0) geendet.
Der Thread 0x2a70 hat mit Code 0 (0x0) geendet.
Der Thread 0x2e64 hat mit Code 0 (0x0) geendet.
Der Thread 0x1644 hat mit Code 0 (0x0) geendet.
Der Thread 0x2d54 hat mit Code 0 (0x0) geendet.
Der Thread 0x2154 hat mit Code 0 (0x0) geendet.
Der Thread 0x13e4 hat mit Code 0 (0x0) geendet.
Der Thread 0x738 hat mit Code 0 (0x0) geendet.
Der Thread 0x282c hat mit Code 0 (0x0) geendet.
Das Programm "[11960] Client-built.exe" wurde mit Code 0 (0x0) beendet.
