### ISSUE TITLE
QuasarRat not connecting.

### ISSUE THREAD

**Issue by WorkHardSolutions** [quasar/QuasarRAT#805]
Made the client, sent to target pc, ran it, no issues.
It doest seem to show up on the qhost, when checking outgoing connections on the targetpc it shows a completely different IP, what can i do to fix this?

**Comment by WorkHardSolutions** [comment]
I tried portforwarding but its still not connecting, any help?

**Comment by TomerGamerTV** [comment]
I think its an outdated project...

**Comment by Dazmed707** [comment]
If you want to know how they could be off the network so that the connection reaches them from anywhere in the world, write me a telegram @dazmed707

**Comment by bbyte-lab** [comment]
@TomerGamerTV: "I think its an outdated project..." ==> the project is good, i think you haven't downloaded the last project with "Models" folder, the dev reloaded content, or download last version 1.3(stable)

Last update: 2018 and good project i think!

**Comment by TomerGamerTV** [comment]
> @TomerGamerTV: "I think its an outdated project..." ==> the project is good, i think you haven't downloaded the last project with "Models" folder, the dev reloaded content, or download last version 1.3(stable)
> 
> 
> 
> Last update: 2018 and good project i think!

There is a way to make modern design? Or plugins

**Comment by bbyte-lab** [comment]
easy to change design: https://i.imgur.com/fCvJn6N.png (look on right-top the blue_rat), just add so little code..

you can do it!

**Comment by bbyte-lab** [comment]
i added in last version: escalade nt-authority, texttospeech, anti windef and ffirewall windows and little others things, i'm adding that to the last project.

You can to it too!

**Comment by jamesleesoniscool** [comment]
i gave it to someone and when they opened it it did nothing and didnt connect

**Comment by Dazmed707** [comment]
debes revisar la coneccion y el puerto, aparte de que la víctima debe tener net framework instalado
