### ISSUE TITLE
client not connecting

### ISSUE THREAD

**Issue by ianswami** [quasar/QuasarRAT#809]
**Is your feature request related to a problem? Please describe.**
hi, I am a student. 

created the client on virtual machine using the port forwarding through noip and vpn

host and port created successfully. checked the same on canyouseeme.org and found working.

then install the quaser rat and created the client successfully without an error.
but when i drop the client to another virtual machine and install.

but no connection was showing over listing the port.

please help where i am faulting.

Regards
**Describe the solution you'd like**

no connection to device

**Additional context**
done everything. do i need to crate a specific port. ( i have created port 1177)

kindly help

**Comment by bbyte-lab** [comment]
Hi,

i have the same probleme in Debug_mod but in Release, the connexion is ok

Check it!

**Comment by DanusMinimus** [comment]
If you are using VMware, the reason for that might be is that when you have more than one virtual machine - the second one is sharing the same IP as the host.
