### ISSUE TITLE
Not Connecting To A Diffrent IP

### ISSUE THREAD

**Issue by Cooldud400** [quasar/QuasarRAT#810]
Hello, so my issue today is that i can't get my builder to work on different ip's/computers, me and my friend we're try to see if we could get for 4 hours and weren't able to. It did work when i put the .exe on my desktop but that's about it.

**Comment by ianswami** [comment]
It's works with release only with simple knowledge

**Comment by RockOx553** [comment]
Yeah Im having the same problem too, and what do you mean "It's works with release only with simple knowledge" that doesn't really help.

**Comment by ianswami** [comment]
What's your email address?

**Comment by Cooldud400** [comment]
My email is "jimmydickson24@gmail.com"

**Comment by Cooldud400** [comment]
ianswami, its still not working after what you told me to do. Any other suggestions?

**Comment by ianswami** [comment]
We can work online
