### ISSUE TITLE
Can't find the Release configuration file to start installion

### ISSUE THREAD

**Issue by AHMEDALDOORI97** [quasar/QuasarRAT#811]
Hi and thank you about your Project , Can you help me to install it i can't find the 

Release configuration file to start installion.

Thank you

**Comment by ianswami** [comment]
What's yours email address

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by MaxXor** [comment]
See https://github.com/quasar/QuasarRAT#compiling
