### ISSUE TITLE
Not working when server and client are connected to different networks

### ISSUE THREAD

**Issue by svpaz7** [quasar/QuasarRAT#813]
Is this RAT supposed to be able to detect the client over different networks?
I've tried doing so and I can't detect the client. 
When connecting both server and client to the same network, however, everything works just fine - no problems.

**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Quasar Version: 1.3.0

**Comment by BurntDog** [comment]
Did you check to be sure you port forward the correct port?

**Comment by Hawax** [comment]
You have to do port forwarding check out https://ngrok.com/
