### ISSUE TITLE
error while building with VS2019

### ISSUE THREAD

**Issue by dexter-qjq** [quasar/QuasarRAT#814]
I have downloaded the source code from main page, and open .sln file with VS2019. I release-build service, that is ok. When release-build client, VS told me that cannt copy client.exe and client.bin . Then I looked at the dir and found client.exe, but no client.bin. What is the problem? And how I can fix it? Thanks in advance.

**Comment by ReactorCore17** [comment]
I have been having the same issue, and it wouldn't build in older versions of VScode either. I can scan around my saved files for a working copy and post it here, but I'd doubt you or anyone else would trust me (no worries if you don't).

**Comment by dexter-qjq** [comment]
> I have been having the same issue, and it wouldn't build in older versions of VScode either. I can scan around my saved files for a working copy and post it here, but I'd doubt you or anyone else would trust me (no worries if you don't).

thanks for your attention and help. How did you build your current working software? this is my email, qjq793437528@163.com. Maybe you can share me some other info about this project or even some running screenshots.

**Comment by ReactorCore17** [comment]
My working software is an older version before the recent update. Sorry I can’t be more help.

**Comment by ReactorCore17** [comment]
I am having recent issues with that as well.

**Comment by dexter-qjq** [comment]
By the way, there is a warning information that  CS0169 “Client._typeIndex” is never used.

**Comment by MaxXor** [comment]
What's the exact error message you're getting?

**Comment by ReactorCore17** [comment]
The issue is not the building of the solution (at least for me), but VScode gives me an error saying the project isn't valid. I'm running VS2019, and only got this error after the new update. All the projects say "not loaded" next to them.

**Comment by MaxXor** [comment]
Building the solution with VSCode is not officially supported. However I've converted the project files to the new .csproj format so be sure to have the .NET Core extensions installed in VSCode.

**Comment by ReactorCore17** [comment]
Alright - I make the changes. Thanks.

**Comment by ReactorCore17** [comment]
I made a silly mistake in my previous comments. I get the errors while building in Visual Studio, not in VSCode. I'm not sure why, but after the recent commit i got the errors.

**Comment by MaxXor** [comment]
Can you show the exact error message here?

**Comment by dexter-qjq** [comment]
thanks for your help, i've fix this problem.
