### ISSUE TITLE
Mono.Cecil.dll Error

### ISSUE THREAD

**Issue by SagexWasTaken** [quasar/QuasarRAT#815]
Hi there, im extremely new to making rats and building clients, whenever I press build it just gives out a error mentioning Mono.cecil.dll, tried to reinstall the dll didn't work.
![Screenshot_772](https://user-images.githubusercontent.com/65954052/82894394-2d5aff00-9f5b-11ea-9c09-4f3bde454213.png)

**Comment by MaxXor** [comment]
See https://github.com/quasar/QuasarRAT#compiling

And be sure to keep all the dlls files together with Quasar.exe. The client.exe doesn't need the separate dll files as they get merged during a release-configuration build.
