### ISSUE TITLE
MIT license but GPL for QuickLZ

### ISSUE THREAD

**Issue by TechInterMezzo** [quasar/QuasarRAT#816]
I see that this project is under the MIT license. But the following class is licensed under GPL if I understand correctly.

https://github.com/quasar/QuasarRAT/blob/master/Quasar.Common/IO/Compression/SafeQuickLZ.cs

So can the project even be under MIT license when it uses a source code component under GPL?

**Comment by MaxXor** [comment]
It's no problem. https://en.wikipedia.org/wiki/License_compatibility

**Comment by TechInterMezzo** [comment]
Isn't this meant for the other way around? I mean, GPL is more restrictive and MIT doesn't have those restrictions, effectively removing some of them by putting the project under MIT.

**Comment by MaxXor** [comment]
I'm not an expert in this area and after more research it seems like Quasar needs to have GPL too. However the code is currently unused and can be safely removed.
