### ISSUE TITLE
file transfer

### ISSUE THREAD

**Issue by souree666** [quasar/QuasarRAT#817]
How do i use the file transfer feature? I'm pretty sure it uses FTP but I cannot figure out how to get it working

**Comment by MaxXor** [comment]
It's not using FTP. Here are the important parts:

- [FileSplit](https://github.com/quasar/QuasarRAT/blob/master/Quasar.Common/IO/FileSplit.cs) class used to split files into 64kb parts and merge them again
- Server-side [FileManager](https://github.com/quasar/QuasarRAT/blob/master/Quasar.Server/Messages/FileManagerHandler.cs) class, only the server can initiate downloads or uploads.
- Client-side [FileManager](https://github.com/quasar/QuasarRAT/blob/master/Quasar.Client/Messages/FileManagerHandler.cs) class used to answer to file transfer requests
