### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by XomecStar** [quasar/QuasarRAT#820]
When I try to compile the file I get error telling me that I am missing .NET Framework version 4.5.2! I have already installed the framework it needed. Some help please?

**Comment by MaxXor** [comment]
Pleases follow these instructions: https://github.com/quasar/QuasarRAT#compiling

**Comment by XomecStar** [comment]
Not sure what I am doing wrong, but even following the instructions I get error compiling

**Comment by MaxXor** [comment]
Can you copy and paste the exact error message here?

**Comment by XomecStar** [comment]
<img width="721" alt="Capture" src="https://user-images.githubusercontent.com/39454607/83537885-74199d80-a4f5-11ea-9c44-e2b2392819b8.PNG">

**Comment by MaxXor** [comment]
It's not a .NET Core project. Use Visual Studio 2019 to compile it.
